// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_message.proto

/*
Package msg_client_message is a generated protocol buffer package.

It is generated from these files:
	client_message.proto

It has these top-level messages:
	C2S_TEST_COMMAND
	ItemInfo
	FriendInfo
	PlayerStageInfo
	S2CStagePass
	C2SLoginRequest
	ServerInfo
	S2CLoginResponse
	S2COtherPlaceLogin
	C2SSelectServerRequest
	S2CSelectServerResponse
	C2S_MSG_DATA
	S2C_MSG_DATA
	C2SEnterGameRequest
	S2CEnterGameResponse
	S2CEnterGameCompleteNotify
	C2SFriendSearch
	C2SFriendSearchById
	S2CFriendSearchResult
	C2SGetFriendList
	FriendReq
	S2CRetFriendListResult
	S2CFriendStateNotify
	S2CFriendReqNotify
	C2SAddFriendByPId
	C2SAddFriendByName
	S2CAddFriendResult
	C2SAgreeFriend
	S2CAgreeFriendResult
	C2SRefuseFriend
	S2CRefuseFriendResult
	C2SRemoveFriend
	S2CRemoveFriendResult
	C2SGiveFriendPoints
	FriendPointsResult
	S2CGiveFriendPointsResult
	C2SGetFriendPoints
	FriendPoints
	S2CGetFriendPointsResult
	C2SFriendChat
	S2CFriendChatResult
	C2SFriendGetUnreadMessageNum
	FriendUnreadMessageNumData
	S2CFriendGetUnreadMessageNumResult
	C2SFriendPullUnreadMessage
	FriendChatData
	S2CFriendPullUnreadMessageResult
	C2SFriendConfirmUnreadMessage
	S2CFriendConfirmUnreadMessageResult
	C2SGetOnlineFriends
	S2CRetOnlineFriends
	C2SShopItems
	S2CShopItem
	S2CShopItemsResult
	C2SBuyShopItem
	S2CBuyShopItemResult
	S2CShopNeedRefreshNotify
	DialyTaskData
	C2SGetDialyTaskInfo
	S2CSyncDialyTask
	S2CNotifyTaskValueChg
	AchieveData
	C2SGetAchieve
	S2CSyncAchieveData
	S2CNotifyAchieveValueChg
	C2SGetTaskReward
	S2CRetTaskReward
	C2SGetAchieveReward
	S2CRetAchieveReward
	C2SWorldChatSend
	S2CWorldChatSendResult
	C2SWorldChatMsgPull
	WorldChatItem
	S2CWorldChatMsgPullResult
	S2CWorldChatForbid
	S2CSyncGuideData
	C2SSaveGuideData
	S2CRetSaveGuideData
*/
package msg_client_message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type E_ERR int32

const (
	E_ERR_NONE                           E_ERR = 0
	E_ERR_INTERNAL                       E_ERR = -1
	E_ERR_PLAYER_ACC_OR_PASSWORD_ERROR   E_ERR = -2
	E_ERR_PLAYER_NOT_EXIST               E_ERR = -3
	E_ERR_PLAYER_ALREADY_LOGINED         E_ERR = -4
	E_ERR_PLAYER_OTHER_PLACE_LOGIN       E_ERR = -5
	E_ERR_PLAYER_TOKEN_ERROR             E_ERR = -6
	E_ERR_PLAYER_SELECT_SERVER_NOT_FOUND E_ERR = -7
	E_ERR_PLAYER_ALREADY_SELECTED_SERVER E_ERR = -8
	// 玩家
	E_ERR_PLAYER_ALREADY_ZAN_TODAY           E_ERR = -100000
	E_ERR_PLAYER_RENAME_NEW_CANT_SAME_TO_OLD E_ERR = -100001
	E_ERR_PLAYER_RENAME_NEW_CANT_EMPTY       E_ERR = -100002
	E_ERR_PLAYER_RENAME_REMOVE_OLD_FAILED    E_ERR = -100003
	E_ERR_PLAYER_RENAME_TOO_LONG_NAME        E_ERR = -100004
	E_ERR_PLAYER_RENAME_NOT_ENOUGH_DIAMOND   E_ERR = -100005
	E_ERR_CHARGE_ORDER_DATA_EMPTY            E_ERR = -200000
	E_ERR_CHARGE_ORDER_DATA_INVALID          E_ERR = -200001
	E_ERR_CHARGE_ORDER_SIGNATURE_INVALID     E_ERR = -200002
	E_ERR_CHARGE_ORDER_SN_EMPTY              E_ERR = -200003
	E_ERR_CHARGE_ORDER_SN_ALREDY_USED        E_ERR = -200004
	E_ERR_CHARGE_ORDER_VERIFY_FAILED         E_ERR = -200005
	E_ERR_FRIEND_MESSAGE_NUM_MAX             E_ERR = -300000
	E_ERR_FRIEND_NO_UNREAD_MESSAGE           E_ERR = -300001
	E_ERR_FRIEND_THE_PLAYER_ALREADY_FRIEND   E_ERR = -300002
	E_ERR_FRIEND_THE_PLAYER_REQUESTED        E_ERR = -300003
	E_ERR_FRIEND_REMOVE_FRIEND_FAILED        E_ERR = -300004
	E_ERR_FRIEND_GIVE_POINTS_FREQUENTLY      E_ERR = -300005
	E_ERR_FRIEND_TOO_MANY_FRIEND_GIVE_POINTS E_ERR = -300006
	E_ERR_FRIEND_GIVE_POINTS_MAX_NUM_LIMIT   E_ERR = -300007
	E_ERR_FRIEND_NO_THE_FRIEND               E_ERR = -300008
	E_ERR_FRIEND_MESSAGE_TOO_LONG            E_ERR = -300009
	E_ERR_FRIEND_CHAT_FAILED                 E_ERR = -300010
	E_ERR_SHOP_NOT_FOUND                     E_ERR = -400000
	E_ERR_SHOP_PURCHASED_FAILED              E_ERR = -400001
	E_ERR_SHOP_ITEM_NOT_FOUND                E_ERR = -400002
	E_ERR_SHOP_LIMITED_TYPE_INVALID          E_ERR = -400003
	E_ERR_SHOP_ITEM_NOT_ENOUGH               E_ERR = -400004
	// 任务错误码
	E_ERR_TASK_NOT_FOUND         E_ERR = -101600
	E_ERR_TASK_NOT_COMPLETE      E_ERR = -101601
	E_ERR_TASK_NOT_REWARD        E_ERR = -101602
	E_ERR_TASK_ALREADY_REWARDED  E_ERR = -101603
	E_ERR_TASK_LEVEL_NOT_ENOUGH  E_ERR = -101604
	E_ERR_TASK_PREV_NOT_COMPLETE E_ERR = -101605
	// 世界聊天
	E_ERR_WORLDCHAT_SEND_MSG_COOLING_DOWN   E_ERR = -102300
	E_ERR_WORLDCHAT_SEND_MSG_BYTES_TOO_LONG E_ERR = -102301
	E_ERR_WORLDCHAT_CANT_SEND_WITH_NO_FREE  E_ERR = -102302
	E_ERR_WORLDCHAT_PULL_COOLING_DOWN       E_ERR = -102303
	E_ERR_WORLDCHAT_SEND_MSG_BE_FORBIDEN    E_ERR = -102304
)

var E_ERR_name = map[int32]string{
	0:       "NONE",
	-1:      "INTERNAL",
	-2:      "PLAYER_ACC_OR_PASSWORD_ERROR",
	-3:      "PLAYER_NOT_EXIST",
	-4:      "PLAYER_ALREADY_LOGINED",
	-5:      "PLAYER_OTHER_PLACE_LOGIN",
	-6:      "PLAYER_TOKEN_ERROR",
	-7:      "PLAYER_SELECT_SERVER_NOT_FOUND",
	-8:      "PLAYER_ALREADY_SELECTED_SERVER",
	-100000: "PLAYER_ALREADY_ZAN_TODAY",
	-100001: "PLAYER_RENAME_NEW_CANT_SAME_TO_OLD",
	-100002: "PLAYER_RENAME_NEW_CANT_EMPTY",
	-100003: "PLAYER_RENAME_REMOVE_OLD_FAILED",
	-100004: "PLAYER_RENAME_TOO_LONG_NAME",
	-100005: "PLAYER_RENAME_NOT_ENOUGH_DIAMOND",
	-200000: "CHARGE_ORDER_DATA_EMPTY",
	-200001: "CHARGE_ORDER_DATA_INVALID",
	-200002: "CHARGE_ORDER_SIGNATURE_INVALID",
	-200003: "CHARGE_ORDER_SN_EMPTY",
	-200004: "CHARGE_ORDER_SN_ALREDY_USED",
	-200005: "CHARGE_ORDER_VERIFY_FAILED",
	-300000: "FRIEND_MESSAGE_NUM_MAX",
	-300001: "FRIEND_NO_UNREAD_MESSAGE",
	-300002: "FRIEND_THE_PLAYER_ALREADY_FRIEND",
	-300003: "FRIEND_THE_PLAYER_REQUESTED",
	-300004: "FRIEND_REMOVE_FRIEND_FAILED",
	-300005: "FRIEND_GIVE_POINTS_FREQUENTLY",
	-300006: "FRIEND_TOO_MANY_FRIEND_GIVE_POINTS",
	-300007: "FRIEND_GIVE_POINTS_MAX_NUM_LIMIT",
	-300008: "FRIEND_NO_THE_FRIEND",
	-300009: "FRIEND_MESSAGE_TOO_LONG",
	-300010: "FRIEND_CHAT_FAILED",
	-400000: "SHOP_NOT_FOUND",
	-400001: "SHOP_PURCHASED_FAILED",
	-400002: "SHOP_ITEM_NOT_FOUND",
	-400003: "SHOP_LIMITED_TYPE_INVALID",
	-400004: "SHOP_ITEM_NOT_ENOUGH",
	-101600: "TASK_NOT_FOUND",
	-101601: "TASK_NOT_COMPLETE",
	-101602: "TASK_NOT_REWARD",
	-101603: "TASK_ALREADY_REWARDED",
	-101604: "TASK_LEVEL_NOT_ENOUGH",
	-101605: "TASK_PREV_NOT_COMPLETE",
	-102300: "WORLDCHAT_SEND_MSG_COOLING_DOWN",
	-102301: "WORLDCHAT_SEND_MSG_BYTES_TOO_LONG",
	-102302: "WORLDCHAT_CANT_SEND_WITH_NO_FREE",
	-102303: "WORLDCHAT_PULL_COOLING_DOWN",
	-102304: "WORLDCHAT_SEND_MSG_BE_FORBIDEN",
}
var E_ERR_value = map[string]int32{
	"NONE":                               0,
	"INTERNAL":                           -1,
	"PLAYER_ACC_OR_PASSWORD_ERROR":       -2,
	"PLAYER_NOT_EXIST":                   -3,
	"PLAYER_ALREADY_LOGINED":             -4,
	"PLAYER_OTHER_PLACE_LOGIN":           -5,
	"PLAYER_TOKEN_ERROR":                 -6,
	"PLAYER_SELECT_SERVER_NOT_FOUND":     -7,
	"PLAYER_ALREADY_SELECTED_SERVER":     -8,
	"PLAYER_ALREADY_ZAN_TODAY":           -100000,
	"PLAYER_RENAME_NEW_CANT_SAME_TO_OLD": -100001,
	"PLAYER_RENAME_NEW_CANT_EMPTY":       -100002,
	"PLAYER_RENAME_REMOVE_OLD_FAILED":    -100003,
	"PLAYER_RENAME_TOO_LONG_NAME":        -100004,
	"PLAYER_RENAME_NOT_ENOUGH_DIAMOND":   -100005,
	"CHARGE_ORDER_DATA_EMPTY":            -200000,
	"CHARGE_ORDER_DATA_INVALID":          -200001,
	"CHARGE_ORDER_SIGNATURE_INVALID":     -200002,
	"CHARGE_ORDER_SN_EMPTY":              -200003,
	"CHARGE_ORDER_SN_ALREDY_USED":        -200004,
	"CHARGE_ORDER_VERIFY_FAILED":         -200005,
	"FRIEND_MESSAGE_NUM_MAX":             -300000,
	"FRIEND_NO_UNREAD_MESSAGE":           -300001,
	"FRIEND_THE_PLAYER_ALREADY_FRIEND":   -300002,
	"FRIEND_THE_PLAYER_REQUESTED":        -300003,
	"FRIEND_REMOVE_FRIEND_FAILED":        -300004,
	"FRIEND_GIVE_POINTS_FREQUENTLY":      -300005,
	"FRIEND_TOO_MANY_FRIEND_GIVE_POINTS": -300006,
	"FRIEND_GIVE_POINTS_MAX_NUM_LIMIT":   -300007,
	"FRIEND_NO_THE_FRIEND":               -300008,
	"FRIEND_MESSAGE_TOO_LONG":            -300009,
	"FRIEND_CHAT_FAILED":                 -300010,
	"SHOP_NOT_FOUND":                     -400000,
	"SHOP_PURCHASED_FAILED":              -400001,
	"SHOP_ITEM_NOT_FOUND":                -400002,
	"SHOP_LIMITED_TYPE_INVALID":          -400003,
	"SHOP_ITEM_NOT_ENOUGH":               -400004,
	"TASK_NOT_FOUND":                     -101600,
	"TASK_NOT_COMPLETE":                  -101601,
	"TASK_NOT_REWARD":                    -101602,
	"TASK_ALREADY_REWARDED":              -101603,
	"TASK_LEVEL_NOT_ENOUGH":              -101604,
	"TASK_PREV_NOT_COMPLETE":             -101605,
	"WORLDCHAT_SEND_MSG_COOLING_DOWN":    -102300,
	"WORLDCHAT_SEND_MSG_BYTES_TOO_LONG":  -102301,
	"WORLDCHAT_CANT_SEND_WITH_NO_FREE":   -102302,
	"WORLDCHAT_PULL_COOLING_DOWN":        -102303,
	"WORLDCHAT_SEND_MSG_BE_FORBIDEN":     -102304,
}

func (x E_ERR) String() string {
	return proto.EnumName(E_ERR_name, int32(x))
}
func (E_ERR) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 测试用消息
type C2S_TEST_COMMAND struct {
	Cmd  string   `protobuf:"bytes,1,opt,name=cmd" json:"cmd,omitempty"`
	Args []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
}

func (m *C2S_TEST_COMMAND) Reset()                    { *m = C2S_TEST_COMMAND{} }
func (m *C2S_TEST_COMMAND) String() string            { return proto.CompactTextString(m) }
func (*C2S_TEST_COMMAND) ProtoMessage()               {}
func (*C2S_TEST_COMMAND) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S_TEST_COMMAND) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *C2S_TEST_COMMAND) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

// 物品
type ItemInfo struct {
	ItemCfgId     int32 `protobuf:"varint,1,opt,name=ItemCfgId" json:"ItemCfgId,omitempty"`
	ItemNum       int32 `protobuf:"varint,2,opt,name=ItemNum" json:"ItemNum,omitempty"`
	RemainSeconds int32 `protobuf:"varint,3,opt,name=RemainSeconds" json:"RemainSeconds,omitempty"`
}

func (m *ItemInfo) Reset()                    { *m = ItemInfo{} }
func (m *ItemInfo) String() string            { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()               {}
func (*ItemInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ItemInfo) GetItemCfgId() int32 {
	if m != nil {
		return m.ItemCfgId
	}
	return 0
}

func (m *ItemInfo) GetItemNum() int32 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

func (m *ItemInfo) GetRemainSeconds() int32 {
	if m != nil {
		return m.RemainSeconds
	}
	return 0
}

// 好友信息
type FriendInfo struct {
	PlayerId         int32  `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Head             string `protobuf:"bytes,3,opt,name=Head" json:"Head,omitempty"`
	Level            int32  `protobuf:"varint,4,opt,name=Level" json:"Level,omitempty"`
	VipLevel         int32  `protobuf:"varint,5,opt,name=VipLevel" json:"VipLevel,omitempty"`
	LastLogin        int32  `protobuf:"varint,6,opt,name=LastLogin" json:"LastLogin,omitempty"`
	FriendPoints     int32  `protobuf:"varint,7,opt,name=FriendPoints" json:"FriendPoints,omitempty"`
	LeftGiveSeconds  int32  `protobuf:"varint,8,opt,name=LeftGiveSeconds" json:"LeftGiveSeconds,omitempty"`
	UnreadMessageNum int32  `protobuf:"varint,9,opt,name=UnreadMessageNum" json:"UnreadMessageNum,omitempty"`
	Zan              int32  `protobuf:"varint,10,opt,name=Zan" json:"Zan,omitempty"`
	IsZanToday       bool   `protobuf:"varint,11,opt,name=IsZanToday" json:"IsZanToday,omitempty"`
	IsOnline         bool   `protobuf:"varint,12,opt,name=IsOnline" json:"IsOnline,omitempty"`
	FosteredCatNum   int32  `protobuf:"varint,14,opt,name=FosteredCatNum" json:"FosteredCatNum,omitempty"`
	CanFosterCatNum  int32  `protobuf:"varint,15,opt,name=CanFosterCatNum" json:"CanFosterCatNum,omitempty"`
}

func (m *FriendInfo) Reset()                    { *m = FriendInfo{} }
func (m *FriendInfo) String() string            { return proto.CompactTextString(m) }
func (*FriendInfo) ProtoMessage()               {}
func (*FriendInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FriendInfo) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *FriendInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FriendInfo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *FriendInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *FriendInfo) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *FriendInfo) GetLastLogin() int32 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func (m *FriendInfo) GetFriendPoints() int32 {
	if m != nil {
		return m.FriendPoints
	}
	return 0
}

func (m *FriendInfo) GetLeftGiveSeconds() int32 {
	if m != nil {
		return m.LeftGiveSeconds
	}
	return 0
}

func (m *FriendInfo) GetUnreadMessageNum() int32 {
	if m != nil {
		return m.UnreadMessageNum
	}
	return 0
}

func (m *FriendInfo) GetZan() int32 {
	if m != nil {
		return m.Zan
	}
	return 0
}

func (m *FriendInfo) GetIsZanToday() bool {
	if m != nil {
		return m.IsZanToday
	}
	return false
}

func (m *FriendInfo) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *FriendInfo) GetFosteredCatNum() int32 {
	if m != nil {
		return m.FosteredCatNum
	}
	return 0
}

func (m *FriendInfo) GetCanFosterCatNum() int32 {
	if m != nil {
		return m.CanFosterCatNum
	}
	return 0
}

type PlayerStageInfo struct {
	PlayerId   int32  `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	Score      int32  `protobuf:"varint,2,opt,name=Score" json:"Score,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Lvl        int32  `protobuf:"varint,4,opt,name=Lvl" json:"Lvl,omitempty"`
	Icon       string `protobuf:"bytes,5,opt,name=Icon" json:"Icon,omitempty"`
	CustomIcon string `protobuf:"bytes,6,opt,name=CustomIcon" json:"CustomIcon,omitempty"`
}

func (m *PlayerStageInfo) Reset()                    { *m = PlayerStageInfo{} }
func (m *PlayerStageInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerStageInfo) ProtoMessage()               {}
func (*PlayerStageInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PlayerStageInfo) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerStageInfo) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *PlayerStageInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerStageInfo) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

func (m *PlayerStageInfo) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *PlayerStageInfo) GetCustomIcon() string {
	if m != nil {
		return m.CustomIcon
	}
	return ""
}

type S2CStagePass struct {
	StageId         int32              `protobuf:"varint,1,opt,name=StageId" json:"StageId,omitempty"`
	Stars           int32              `protobuf:"varint,2,opt,name=Stars" json:"Stars,omitempty"`
	Score           int32              `protobuf:"varint,3,opt,name=Score" json:"Score,omitempty"`
	TopScore        int32              `protobuf:"varint,4,opt,name=TopScore" json:"TopScore,omitempty"`
	UseItems        []*ItemInfo        `protobuf:"bytes,5,rep,name=UseItems" json:"UseItems,omitempty"`
	GetCoin         int32              `protobuf:"varint,6,opt,name=GetCoin" json:"GetCoin,omitempty"`
	Getitems        []*ItemInfo        `protobuf:"bytes,7,rep,name=Getitems" json:"Getitems,omitempty"`
	RankItems       []*PlayerStageInfo `protobuf:"bytes,8,rep,name=RankItems" json:"RankItems,omitempty"`
	FriendItems     []*PlayerStageInfo `protobuf:"bytes,9,rep,name=FriendItems" json:"FriendItems,omitempty"`
	Result          int32              `protobuf:"varint,12,opt,name=Result" json:"Result,omitempty"`
	GetitemsFirst   []*ItemInfo        `protobuf:"bytes,13,rep,name=GetitemsFirst" json:"GetitemsFirst,omitempty"`
	Getitems3Star   []*ItemInfo        `protobuf:"bytes,14,rep,name=Getitems3Star" json:"Getitems3Star,omitempty"`
	CatExtraAddCoin int32              `protobuf:"varint,15,opt,name=CatExtraAddCoin" json:"CatExtraAddCoin,omitempty"`
}

func (m *S2CStagePass) Reset()                    { *m = S2CStagePass{} }
func (m *S2CStagePass) String() string            { return proto.CompactTextString(m) }
func (*S2CStagePass) ProtoMessage()               {}
func (*S2CStagePass) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *S2CStagePass) GetStageId() int32 {
	if m != nil {
		return m.StageId
	}
	return 0
}

func (m *S2CStagePass) GetStars() int32 {
	if m != nil {
		return m.Stars
	}
	return 0
}

func (m *S2CStagePass) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *S2CStagePass) GetTopScore() int32 {
	if m != nil {
		return m.TopScore
	}
	return 0
}

func (m *S2CStagePass) GetUseItems() []*ItemInfo {
	if m != nil {
		return m.UseItems
	}
	return nil
}

func (m *S2CStagePass) GetGetCoin() int32 {
	if m != nil {
		return m.GetCoin
	}
	return 0
}

func (m *S2CStagePass) GetGetitems() []*ItemInfo {
	if m != nil {
		return m.Getitems
	}
	return nil
}

func (m *S2CStagePass) GetRankItems() []*PlayerStageInfo {
	if m != nil {
		return m.RankItems
	}
	return nil
}

func (m *S2CStagePass) GetFriendItems() []*PlayerStageInfo {
	if m != nil {
		return m.FriendItems
	}
	return nil
}

func (m *S2CStagePass) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *S2CStagePass) GetGetitemsFirst() []*ItemInfo {
	if m != nil {
		return m.GetitemsFirst
	}
	return nil
}

func (m *S2CStagePass) GetGetitems3Star() []*ItemInfo {
	if m != nil {
		return m.Getitems3Star
	}
	return nil
}

func (m *S2CStagePass) GetCatExtraAddCoin() int32 {
	if m != nil {
		return m.CatExtraAddCoin
	}
	return 0
}

// 登陆
type C2SLoginRequest struct {
	Acc      string `protobuf:"bytes,1,opt,name=Acc" json:"Acc,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
	Channel  string `protobuf:"bytes,3,opt,name=Channel" json:"Channel,omitempty"`
}

func (m *C2SLoginRequest) Reset()                    { *m = C2SLoginRequest{} }
func (m *C2SLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*C2SLoginRequest) ProtoMessage()               {}
func (*C2SLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *C2SLoginRequest) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *C2SLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *C2SLoginRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

// 服务器信息
type ServerInfo struct {
	Id   int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	IP   string `protobuf:"bytes,3,opt,name=IP" json:"IP,omitempty"`
}

func (m *ServerInfo) Reset()                    { *m = ServerInfo{} }
func (m *ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()               {}
func (*ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServerInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ServerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerInfo) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

// 登陆返回
type S2CLoginResponse struct {
	Acc     string        `protobuf:"bytes,1,opt,name=Acc" json:"Acc,omitempty"`
	Token   string        `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
	Servers []*ServerInfo `protobuf:"bytes,3,rep,name=Servers" json:"Servers,omitempty"`
}

func (m *S2CLoginResponse) Reset()                    { *m = S2CLoginResponse{} }
func (m *S2CLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*S2CLoginResponse) ProtoMessage()               {}
func (*S2CLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *S2CLoginResponse) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *S2CLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *S2CLoginResponse) GetServers() []*ServerInfo {
	if m != nil {
		return m.Servers
	}
	return nil
}

// / 其它地方登录
type S2COtherPlaceLogin struct {
}

func (m *S2COtherPlaceLogin) Reset()                    { *m = S2COtherPlaceLogin{} }
func (m *S2COtherPlaceLogin) String() string            { return proto.CompactTextString(m) }
func (*S2COtherPlaceLogin) ProtoMessage()               {}
func (*S2COtherPlaceLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// 选择服务器
type C2SSelectServerRequest struct {
	Acc      string `protobuf:"bytes,1,opt,name=Acc" json:"Acc,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
	ServerId int32  `protobuf:"varint,3,opt,name=ServerId" json:"ServerId,omitempty"`
}

func (m *C2SSelectServerRequest) Reset()                    { *m = C2SSelectServerRequest{} }
func (m *C2SSelectServerRequest) String() string            { return proto.CompactTextString(m) }
func (*C2SSelectServerRequest) ProtoMessage()               {}
func (*C2SSelectServerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *C2SSelectServerRequest) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *C2SSelectServerRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *C2SSelectServerRequest) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

// 选择服务器返回
type S2CSelectServerResponse struct {
	Acc   string `protobuf:"bytes,1,opt,name=Acc" json:"Acc,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
	IP    string `protobuf:"bytes,3,opt,name=IP" json:"IP,omitempty"`
}

func (m *S2CSelectServerResponse) Reset()                    { *m = S2CSelectServerResponse{} }
func (m *S2CSelectServerResponse) String() string            { return proto.CompactTextString(m) }
func (*S2CSelectServerResponse) ProtoMessage()               {}
func (*S2CSelectServerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *S2CSelectServerResponse) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *S2CSelectServerResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *S2CSelectServerResponse) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type C2S_MSG_DATA struct {
	PlayerId int32  `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
	MsgCode  int32  `protobuf:"varint,3,opt,name=MsgCode" json:"MsgCode,omitempty"`
	Data     []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *C2S_MSG_DATA) Reset()                    { *m = C2S_MSG_DATA{} }
func (m *C2S_MSG_DATA) String() string            { return proto.CompactTextString(m) }
func (*C2S_MSG_DATA) ProtoMessage()               {}
func (*C2S_MSG_DATA) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *C2S_MSG_DATA) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *C2S_MSG_DATA) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *C2S_MSG_DATA) GetMsgCode() int32 {
	if m != nil {
		return m.MsgCode
	}
	return 0
}

func (m *C2S_MSG_DATA) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type S2C_MSG_DATA struct {
	ErrorCode int32  `protobuf:"varint,1,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
	ErrorMsg  string `protobuf:"bytes,2,opt,name=ErrorMsg" json:"ErrorMsg,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *S2C_MSG_DATA) Reset()                    { *m = S2C_MSG_DATA{} }
func (m *S2C_MSG_DATA) String() string            { return proto.CompactTextString(m) }
func (*S2C_MSG_DATA) ProtoMessage()               {}
func (*S2C_MSG_DATA) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *S2C_MSG_DATA) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *S2C_MSG_DATA) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *S2C_MSG_DATA) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 进入游戏服务器
type C2SEnterGameRequest struct {
	Acc   string `protobuf:"bytes,1,opt,name=Acc" json:"Acc,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
}

func (m *C2SEnterGameRequest) Reset()                    { *m = C2SEnterGameRequest{} }
func (m *C2SEnterGameRequest) String() string            { return proto.CompactTextString(m) }
func (*C2SEnterGameRequest) ProtoMessage()               {}
func (*C2SEnterGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *C2SEnterGameRequest) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *C2SEnterGameRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 返回
type S2CEnterGameResponse struct {
	Acc      string `protobuf:"bytes,1,opt,name=Acc" json:"Acc,omitempty"`
	PlayerId int32  `protobuf:"varint,2,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *S2CEnterGameResponse) Reset()                    { *m = S2CEnterGameResponse{} }
func (m *S2CEnterGameResponse) String() string            { return proto.CompactTextString(m) }
func (*S2CEnterGameResponse) ProtoMessage()               {}
func (*S2CEnterGameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *S2CEnterGameResponse) GetAcc() string {
	if m != nil {
		return m.Acc
	}
	return ""
}

func (m *S2CEnterGameResponse) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 通知客户端进入游戏服务器完成
type S2CEnterGameCompleteNotify struct {
}

func (m *S2CEnterGameCompleteNotify) Reset()                    { *m = S2CEnterGameCompleteNotify{} }
func (m *S2CEnterGameCompleteNotify) String() string            { return proto.CompactTextString(m) }
func (*S2CEnterGameCompleteNotify) ProtoMessage()               {}
func (*S2CEnterGameCompleteNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

// 按昵称查找好友信息
type C2SFriendSearch struct {
	Key string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
}

func (m *C2SFriendSearch) Reset()                    { *m = C2SFriendSearch{} }
func (m *C2SFriendSearch) String() string            { return proto.CompactTextString(m) }
func (*C2SFriendSearch) ProtoMessage()               {}
func (*C2SFriendSearch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *C2SFriendSearch) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// 按ID查找好友
type C2SFriendSearchById struct {
	PlayerId int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *C2SFriendSearchById) Reset()                    { *m = C2SFriendSearchById{} }
func (m *C2SFriendSearchById) String() string            { return proto.CompactTextString(m) }
func (*C2SFriendSearchById) ProtoMessage()               {}
func (*C2SFriendSearchById) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *C2SFriendSearchById) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 返回好友信息
type S2CFriendSearchResult struct {
	Result []*FriendInfo `protobuf:"bytes,1,rep,name=Result" json:"Result,omitempty"`
}

func (m *S2CFriendSearchResult) Reset()                    { *m = S2CFriendSearchResult{} }
func (m *S2CFriendSearchResult) String() string            { return proto.CompactTextString(m) }
func (*S2CFriendSearchResult) ProtoMessage()               {}
func (*S2CFriendSearchResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *S2CFriendSearchResult) GetResult() []*FriendInfo {
	if m != nil {
		return m.Result
	}
	return nil
}

// 客户端向服务器获取好友相关列表
type C2SGetFriendList struct {
	HasFoster bool `protobuf:"varint,1,opt,name=HasFoster" json:"HasFoster,omitempty"`
}

func (m *C2SGetFriendList) Reset()                    { *m = C2SGetFriendList{} }
func (m *C2SGetFriendList) String() string            { return proto.CompactTextString(m) }
func (*C2SGetFriendList) ProtoMessage()               {}
func (*C2SGetFriendList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *C2SGetFriendList) GetHasFoster() bool {
	if m != nil {
		return m.HasFoster
	}
	return false
}

// 加好友请求信息
type FriendReq struct {
	PlayerId int32  `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Score    int32  `protobuf:"varint,3,opt,name=Score" json:"Score,omitempty"`
	Head     string `protobuf:"bytes,4,opt,name=Head" json:"Head,omitempty"`
}

func (m *FriendReq) Reset()                    { *m = FriendReq{} }
func (m *FriendReq) String() string            { return proto.CompactTextString(m) }
func (*FriendReq) ProtoMessage()               {}
func (*FriendReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *FriendReq) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *FriendReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FriendReq) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *FriendReq) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

// 服务器向客户端返回好友列表
type S2CRetFriendListResult struct {
	FriendType        int32         `protobuf:"varint,1,opt,name=FriendType" json:"FriendType,omitempty"`
	FriendList        []*FriendInfo `protobuf:"bytes,2,rep,name=FriendList" json:"FriendList,omitempty"`
	Reqs              []*FriendReq  `protobuf:"bytes,3,rep,name=Reqs" json:"Reqs,omitempty"`
	LeftGivePointsNum int32         `protobuf:"varint,4,opt,name=LeftGivePointsNum" json:"LeftGivePointsNum,omitempty"`
}

func (m *S2CRetFriendListResult) Reset()                    { *m = S2CRetFriendListResult{} }
func (m *S2CRetFriendListResult) String() string            { return proto.CompactTextString(m) }
func (*S2CRetFriendListResult) ProtoMessage()               {}
func (*S2CRetFriendListResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *S2CRetFriendListResult) GetFriendType() int32 {
	if m != nil {
		return m.FriendType
	}
	return 0
}

func (m *S2CRetFriendListResult) GetFriendList() []*FriendInfo {
	if m != nil {
		return m.FriendList
	}
	return nil
}

func (m *S2CRetFriendListResult) GetReqs() []*FriendReq {
	if m != nil {
		return m.Reqs
	}
	return nil
}

func (m *S2CRetFriendListResult) GetLeftGivePointsNum() int32 {
	if m != nil {
		return m.LeftGivePointsNum
	}
	return 0
}

// 服务器通知好友状态
type S2CFriendStateNotify struct {
	StateType int32       `protobuf:"varint,1,opt,name=StateType" json:"StateType,omitempty"`
	Info      *FriendInfo `protobuf:"bytes,2,opt,name=Info" json:"Info,omitempty"`
}

func (m *S2CFriendStateNotify) Reset()                    { *m = S2CFriendStateNotify{} }
func (m *S2CFriendStateNotify) String() string            { return proto.CompactTextString(m) }
func (*S2CFriendStateNotify) ProtoMessage()               {}
func (*S2CFriendStateNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *S2CFriendStateNotify) GetStateType() int32 {
	if m != nil {
		return m.StateType
	}
	return 0
}

func (m *S2CFriendStateNotify) GetInfo() *FriendInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 服务器通知好友请求
type S2CFriendReqNotify struct {
	Req *FriendReq `protobuf:"bytes,1,opt,name=Req" json:"Req,omitempty"`
}

func (m *S2CFriendReqNotify) Reset()                    { *m = S2CFriendReqNotify{} }
func (m *S2CFriendReqNotify) String() string            { return proto.CompactTextString(m) }
func (*S2CFriendReqNotify) ProtoMessage()               {}
func (*S2CFriendReqNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *S2CFriendReqNotify) GetReq() *FriendReq {
	if m != nil {
		return m.Req
	}
	return nil
}

// 客户端通过Id加好友
type C2SAddFriendByPId struct {
	PlayerId int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *C2SAddFriendByPId) Reset()                    { *m = C2SAddFriendByPId{} }
func (m *C2SAddFriendByPId) String() string            { return proto.CompactTextString(m) }
func (*C2SAddFriendByPId) ProtoMessage()               {}
func (*C2SAddFriendByPId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *C2SAddFriendByPId) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 客户端通过昵称加好友
type C2SAddFriendByName struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *C2SAddFriendByName) Reset()                    { *m = C2SAddFriendByName{} }
func (m *C2SAddFriendByName) String() string            { return proto.CompactTextString(m) }
func (*C2SAddFriendByName) ProtoMessage()               {}
func (*C2SAddFriendByName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *C2SAddFriendByName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 服务器回复添加好友
type S2CAddFriendResult struct {
	PlayerId int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *S2CAddFriendResult) Reset()                    { *m = S2CAddFriendResult{} }
func (m *S2CAddFriendResult) String() string            { return proto.CompactTextString(m) }
func (*S2CAddFriendResult) ProtoMessage()               {}
func (*S2CAddFriendResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *S2CAddFriendResult) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 客户端同意加好友
type C2SAgreeFriend struct {
	PlayerId int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *C2SAgreeFriend) Reset()                    { *m = C2SAgreeFriend{} }
func (m *C2SAgreeFriend) String() string            { return proto.CompactTextString(m) }
func (*C2SAgreeFriend) ProtoMessage()               {}
func (*C2SAgreeFriend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *C2SAgreeFriend) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 服务器返回增加好友回复
type S2CAgreeFriendResult struct {
	PlayerId  int32  `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Score     int32  `protobuf:"varint,3,opt,name=Score" json:"Score,omitempty"`
	Level     int32  `protobuf:"varint,4,opt,name=Level" json:"Level,omitempty"`
	Head      string `protobuf:"bytes,5,opt,name=Head" json:"Head,omitempty"`
	VipLevel  int32  `protobuf:"varint,6,opt,name=VipLevel" json:"VipLevel,omitempty"`
	LastLogin int32  `protobuf:"varint,7,opt,name=LastLogin" json:"LastLogin,omitempty"`
}

func (m *S2CAgreeFriendResult) Reset()                    { *m = S2CAgreeFriendResult{} }
func (m *S2CAgreeFriendResult) String() string            { return proto.CompactTextString(m) }
func (*S2CAgreeFriendResult) ProtoMessage()               {}
func (*S2CAgreeFriendResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *S2CAgreeFriendResult) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *S2CAgreeFriendResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *S2CAgreeFriendResult) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *S2CAgreeFriendResult) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *S2CAgreeFriendResult) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *S2CAgreeFriendResult) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *S2CAgreeFriendResult) GetLastLogin() int32 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

// 客户端拒绝加好友
type C2SRefuseFriend struct {
	PlayerId int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *C2SRefuseFriend) Reset()                    { *m = C2SRefuseFriend{} }
func (m *C2SRefuseFriend) String() string            { return proto.CompactTextString(m) }
func (*C2SRefuseFriend) ProtoMessage()               {}
func (*C2SRefuseFriend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *C2SRefuseFriend) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 服务器通知拒绝加好友
type S2CRefuseFriendResult struct {
	Name     string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	PlayerId int32  `protobuf:"varint,2,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *S2CRefuseFriendResult) Reset()                    { *m = S2CRefuseFriendResult{} }
func (m *S2CRefuseFriendResult) String() string            { return proto.CompactTextString(m) }
func (*S2CRefuseFriendResult) ProtoMessage()               {}
func (*S2CRefuseFriendResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *S2CRefuseFriendResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *S2CRefuseFriendResult) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 客户端删除好友
type C2SRemoveFriend struct {
	PlayerId int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *C2SRemoveFriend) Reset()                    { *m = C2SRemoveFriend{} }
func (m *C2SRemoveFriend) String() string            { return proto.CompactTextString(m) }
func (*C2SRemoveFriend) ProtoMessage()               {}
func (*C2SRemoveFriend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *C2SRemoveFriend) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 服务器通知客户端删除好友
type S2CRemoveFriendResult struct {
	PlayerId int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *S2CRemoveFriendResult) Reset()                    { *m = S2CRemoveFriendResult{} }
func (m *S2CRemoveFriendResult) String() string            { return proto.CompactTextString(m) }
func (*S2CRemoveFriendResult) ProtoMessage()               {}
func (*S2CRemoveFriendResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *S2CRemoveFriendResult) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 赠送友情点
type C2SGiveFriendPoints struct {
	FriendId []int32 `protobuf:"varint,1,rep,packed,name=FriendId" json:"FriendId,omitempty"`
}

func (m *C2SGiveFriendPoints) Reset()                    { *m = C2SGiveFriendPoints{} }
func (m *C2SGiveFriendPoints) String() string            { return proto.CompactTextString(m) }
func (*C2SGiveFriendPoints) ProtoMessage()               {}
func (*C2SGiveFriendPoints) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *C2SGiveFriendPoints) GetFriendId() []int32 {
	if m != nil {
		return m.FriendId
	}
	return nil
}

type FriendPointsResult struct {
	FriendId      int32 `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	Points        int32 `protobuf:"varint,2,opt,name=Points" json:"Points,omitempty"`
	Error         int32 `protobuf:"varint,3,opt,name=Error" json:"Error,omitempty"`
	RemainSeconds int32 `protobuf:"varint,4,opt,name=RemainSeconds" json:"RemainSeconds,omitempty"`
	IsTodayGive   bool  `protobuf:"varint,5,opt,name=IsTodayGive" json:"IsTodayGive,omitempty"`
	BackPoints    int32 `protobuf:"varint,6,opt,name=BackPoints" json:"BackPoints,omitempty"`
}

func (m *FriendPointsResult) Reset()                    { *m = FriendPointsResult{} }
func (m *FriendPointsResult) String() string            { return proto.CompactTextString(m) }
func (*FriendPointsResult) ProtoMessage()               {}
func (*FriendPointsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *FriendPointsResult) GetFriendId() int32 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *FriendPointsResult) GetPoints() int32 {
	if m != nil {
		return m.Points
	}
	return 0
}

func (m *FriendPointsResult) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *FriendPointsResult) GetRemainSeconds() int32 {
	if m != nil {
		return m.RemainSeconds
	}
	return 0
}

func (m *FriendPointsResult) GetIsTodayGive() bool {
	if m != nil {
		return m.IsTodayGive
	}
	return false
}

func (m *FriendPointsResult) GetBackPoints() int32 {
	if m != nil {
		return m.BackPoints
	}
	return 0
}

type S2CGiveFriendPointsResult struct {
	PointsData        []*FriendPointsResult `protobuf:"bytes,1,rep,name=PointsData" json:"PointsData,omitempty"`
	LeftGivePointsNum int32                 `protobuf:"varint,2,opt,name=LeftGivePointsNum" json:"LeftGivePointsNum,omitempty"`
}

func (m *S2CGiveFriendPointsResult) Reset()                    { *m = S2CGiveFriendPointsResult{} }
func (m *S2CGiveFriendPointsResult) String() string            { return proto.CompactTextString(m) }
func (*S2CGiveFriendPointsResult) ProtoMessage()               {}
func (*S2CGiveFriendPointsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *S2CGiveFriendPointsResult) GetPointsData() []*FriendPointsResult {
	if m != nil {
		return m.PointsData
	}
	return nil
}

func (m *S2CGiveFriendPointsResult) GetLeftGivePointsNum() int32 {
	if m != nil {
		return m.LeftGivePointsNum
	}
	return 0
}

// 收取友情点
type C2SGetFriendPoints struct {
	FriendId []int32 `protobuf:"varint,1,rep,packed,name=FriendId" json:"FriendId,omitempty"`
}

func (m *C2SGetFriendPoints) Reset()                    { *m = C2SGetFriendPoints{} }
func (m *C2SGetFriendPoints) String() string            { return proto.CompactTextString(m) }
func (*C2SGetFriendPoints) ProtoMessage()               {}
func (*C2SGetFriendPoints) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *C2SGetFriendPoints) GetFriendId() []int32 {
	if m != nil {
		return m.FriendId
	}
	return nil
}

type FriendPoints struct {
	FriendId int32 `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	Points   int32 `protobuf:"varint,2,opt,name=Points" json:"Points,omitempty"`
}

func (m *FriendPoints) Reset()                    { *m = FriendPoints{} }
func (m *FriendPoints) String() string            { return proto.CompactTextString(m) }
func (*FriendPoints) ProtoMessage()               {}
func (*FriendPoints) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *FriendPoints) GetFriendId() int32 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *FriendPoints) GetPoints() int32 {
	if m != nil {
		return m.Points
	}
	return 0
}

type S2CGetFriendPointsResult struct {
	PointsData []*FriendPoints `protobuf:"bytes,1,rep,name=PointsData" json:"PointsData,omitempty"`
}

func (m *S2CGetFriendPointsResult) Reset()                    { *m = S2CGetFriendPointsResult{} }
func (m *S2CGetFriendPointsResult) String() string            { return proto.CompactTextString(m) }
func (*S2CGetFriendPointsResult) ProtoMessage()               {}
func (*S2CGetFriendPointsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *S2CGetFriendPointsResult) GetPointsData() []*FriendPoints {
	if m != nil {
		return m.PointsData
	}
	return nil
}

// 客户端给好友发送消息
type C2SFriendChat struct {
	PlayerId int32  `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	Content  []byte `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (m *C2SFriendChat) Reset()                    { *m = C2SFriendChat{} }
func (m *C2SFriendChat) String() string            { return proto.CompactTextString(m) }
func (*C2SFriendChat) ProtoMessage()               {}
func (*C2SFriendChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *C2SFriendChat) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *C2SFriendChat) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type S2CFriendChatResult struct {
	PlayerId int32  `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	Content  []byte `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (m *S2CFriendChatResult) Reset()                    { *m = S2CFriendChatResult{} }
func (m *S2CFriendChatResult) String() string            { return proto.CompactTextString(m) }
func (*S2CFriendChatResult) ProtoMessage()               {}
func (*S2CFriendChatResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *S2CFriendChatResult) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *S2CFriendChatResult) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// 获取好友未读消息数量
type C2SFriendGetUnreadMessageNum struct {
	FriendIds []int32 `protobuf:"varint,1,rep,packed,name=FriendIds" json:"FriendIds,omitempty"`
}

func (m *C2SFriendGetUnreadMessageNum) Reset()                    { *m = C2SFriendGetUnreadMessageNum{} }
func (m *C2SFriendGetUnreadMessageNum) String() string            { return proto.CompactTextString(m) }
func (*C2SFriendGetUnreadMessageNum) ProtoMessage()               {}
func (*C2SFriendGetUnreadMessageNum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *C2SFriendGetUnreadMessageNum) GetFriendIds() []int32 {
	if m != nil {
		return m.FriendIds
	}
	return nil
}

type FriendUnreadMessageNumData struct {
	FriendId   int32 `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	MessageNum int32 `protobuf:"varint,2,opt,name=MessageNum" json:"MessageNum,omitempty"`
}

func (m *FriendUnreadMessageNumData) Reset()                    { *m = FriendUnreadMessageNumData{} }
func (m *FriendUnreadMessageNumData) String() string            { return proto.CompactTextString(m) }
func (*FriendUnreadMessageNumData) ProtoMessage()               {}
func (*FriendUnreadMessageNumData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *FriendUnreadMessageNumData) GetFriendId() int32 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *FriendUnreadMessageNumData) GetMessageNum() int32 {
	if m != nil {
		return m.MessageNum
	}
	return 0
}

type S2CFriendGetUnreadMessageNumResult struct {
	Data []*FriendUnreadMessageNumData `protobuf:"bytes,1,rep,name=Data" json:"Data,omitempty"`
}

func (m *S2CFriendGetUnreadMessageNumResult) Reset()         { *m = S2CFriendGetUnreadMessageNumResult{} }
func (m *S2CFriendGetUnreadMessageNumResult) String() string { return proto.CompactTextString(m) }
func (*S2CFriendGetUnreadMessageNumResult) ProtoMessage()    {}
func (*S2CFriendGetUnreadMessageNumResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{43}
}

func (m *S2CFriendGetUnreadMessageNumResult) GetData() []*FriendUnreadMessageNumData {
	if m != nil {
		return m.Data
	}
	return nil
}

// 拉取好友未读聊天消息
type C2SFriendPullUnreadMessage struct {
	FriendId int32 `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
}

func (m *C2SFriendPullUnreadMessage) Reset()                    { *m = C2SFriendPullUnreadMessage{} }
func (m *C2SFriendPullUnreadMessage) String() string            { return proto.CompactTextString(m) }
func (*C2SFriendPullUnreadMessage) ProtoMessage()               {}
func (*C2SFriendPullUnreadMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *C2SFriendPullUnreadMessage) GetFriendId() int32 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

type FriendChatData struct {
	Content  []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	SendTime int32  `protobuf:"varint,2,opt,name=SendTime" json:"SendTime,omitempty"`
}

func (m *FriendChatData) Reset()                    { *m = FriendChatData{} }
func (m *FriendChatData) String() string            { return proto.CompactTextString(m) }
func (*FriendChatData) ProtoMessage()               {}
func (*FriendChatData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *FriendChatData) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *FriendChatData) GetSendTime() int32 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

type S2CFriendPullUnreadMessageResult struct {
	FriendId int32             `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	Data     []*FriendChatData `protobuf:"bytes,2,rep,name=Data" json:"Data,omitempty"`
}

func (m *S2CFriendPullUnreadMessageResult) Reset()         { *m = S2CFriendPullUnreadMessageResult{} }
func (m *S2CFriendPullUnreadMessageResult) String() string { return proto.CompactTextString(m) }
func (*S2CFriendPullUnreadMessageResult) ProtoMessage()    {}
func (*S2CFriendPullUnreadMessageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{46}
}

func (m *S2CFriendPullUnreadMessageResult) GetFriendId() int32 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *S2CFriendPullUnreadMessageResult) GetData() []*FriendChatData {
	if m != nil {
		return m.Data
	}
	return nil
}

// 确认聊天未读消息
type C2SFriendConfirmUnreadMessage struct {
	FriendId   int32 `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	MessageNum int32 `protobuf:"varint,2,opt,name=MessageNum" json:"MessageNum,omitempty"`
}

func (m *C2SFriendConfirmUnreadMessage) Reset()                    { *m = C2SFriendConfirmUnreadMessage{} }
func (m *C2SFriendConfirmUnreadMessage) String() string            { return proto.CompactTextString(m) }
func (*C2SFriendConfirmUnreadMessage) ProtoMessage()               {}
func (*C2SFriendConfirmUnreadMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *C2SFriendConfirmUnreadMessage) GetFriendId() int32 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *C2SFriendConfirmUnreadMessage) GetMessageNum() int32 {
	if m != nil {
		return m.MessageNum
	}
	return 0
}

type S2CFriendConfirmUnreadMessageResult struct {
	FriendId   int32 `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	MessageNum int32 `protobuf:"varint,2,opt,name=MessageNum" json:"MessageNum,omitempty"`
}

func (m *S2CFriendConfirmUnreadMessageResult) Reset()         { *m = S2CFriendConfirmUnreadMessageResult{} }
func (m *S2CFriendConfirmUnreadMessageResult) String() string { return proto.CompactTextString(m) }
func (*S2CFriendConfirmUnreadMessageResult) ProtoMessage()    {}
func (*S2CFriendConfirmUnreadMessageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{48}
}

func (m *S2CFriendConfirmUnreadMessageResult) GetFriendId() int32 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *S2CFriendConfirmUnreadMessageResult) GetMessageNum() int32 {
	if m != nil {
		return m.MessageNum
	}
	return 0
}

// 客户端请求好友在线状态
type C2SGetOnlineFriends struct {
	Key int32 `protobuf:"varint,1,opt,name=Key" json:"Key,omitempty"`
}

func (m *C2SGetOnlineFriends) Reset()                    { *m = C2SGetOnlineFriends{} }
func (m *C2SGetOnlineFriends) String() string            { return proto.CompactTextString(m) }
func (*C2SGetOnlineFriends) ProtoMessage()               {}
func (*C2SGetOnlineFriends) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *C2SGetOnlineFriends) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

// 服务器返回在线好友
type S2CRetOnlineFriends struct {
	PlayerIds []int32 `protobuf:"varint,1,rep,packed,name=PlayerIds" json:"PlayerIds,omitempty"`
	Key       int32   `protobuf:"varint,2,opt,name=Key" json:"Key,omitempty"`
}

func (m *S2CRetOnlineFriends) Reset()                    { *m = S2CRetOnlineFriends{} }
func (m *S2CRetOnlineFriends) String() string            { return proto.CompactTextString(m) }
func (*S2CRetOnlineFriends) ProtoMessage()               {}
func (*S2CRetOnlineFriends) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *S2CRetOnlineFriends) GetPlayerIds() []int32 {
	if m != nil {
		return m.PlayerIds
	}
	return nil
}

func (m *S2CRetOnlineFriends) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

// //////////////// shop ///////////////////////
// 请求商店商品
type C2SShopItems struct {
	ShopId int32 `protobuf:"varint,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
}

func (m *C2SShopItems) Reset()                    { *m = C2SShopItems{} }
func (m *C2SShopItems) String() string            { return proto.CompactTextString(m) }
func (*C2SShopItems) ProtoMessage()               {}
func (*C2SShopItems) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *C2SShopItems) GetShopId() int32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type S2CShopItem struct {
	ItemId        int32 `protobuf:"varint,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	LeftNum       int32 `protobuf:"varint,2,opt,name=left_num,json=leftNum" json:"left_num,omitempty"`
	RemainSeconds int32 `protobuf:"varint,3,opt,name=remain_seconds,json=remainSeconds" json:"remain_seconds,omitempty"`
}

func (m *S2CShopItem) Reset()                    { *m = S2CShopItem{} }
func (m *S2CShopItem) String() string            { return proto.CompactTextString(m) }
func (*S2CShopItem) ProtoMessage()               {}
func (*S2CShopItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

func (m *S2CShopItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *S2CShopItem) GetLeftNum() int32 {
	if m != nil {
		return m.LeftNum
	}
	return 0
}

func (m *S2CShopItem) GetRemainSeconds() int32 {
	if m != nil {
		return m.RemainSeconds
	}
	return 0
}

type S2CShopItemsResult struct {
	ShopId int32          `protobuf:"varint,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Items  []*S2CShopItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *S2CShopItemsResult) Reset()                    { *m = S2CShopItemsResult{} }
func (m *S2CShopItemsResult) String() string            { return proto.CompactTextString(m) }
func (*S2CShopItemsResult) ProtoMessage()               {}
func (*S2CShopItemsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

func (m *S2CShopItemsResult) GetShopId() int32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *S2CShopItemsResult) GetItems() []*S2CShopItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 购买商店物品
type C2SBuyShopItem struct {
	ItemId  int32 `protobuf:"varint,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	ItemNum int32 `protobuf:"varint,2,opt,name=item_num,json=itemNum" json:"item_num,omitempty"`
}

func (m *C2SBuyShopItem) Reset()                    { *m = C2SBuyShopItem{} }
func (m *C2SBuyShopItem) String() string            { return proto.CompactTextString(m) }
func (*C2SBuyShopItem) ProtoMessage()               {}
func (*C2SBuyShopItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{54} }

func (m *C2SBuyShopItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *C2SBuyShopItem) GetItemNum() int32 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

// 购买返回的物品
type S2CBuyShopItemResult struct {
	ShopId  int32     `protobuf:"varint,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	ItemId  int32     `protobuf:"varint,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	ItemNum int32     `protobuf:"varint,3,opt,name=item_num,json=itemNum" json:"item_num,omitempty"`
	AddItem *ItemInfo `protobuf:"bytes,4,opt,name=add_item,json=addItem" json:"add_item,omitempty"`
}

func (m *S2CBuyShopItemResult) Reset()                    { *m = S2CBuyShopItemResult{} }
func (m *S2CBuyShopItemResult) String() string            { return proto.CompactTextString(m) }
func (*S2CBuyShopItemResult) ProtoMessage()               {}
func (*S2CBuyShopItemResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{55} }

func (m *S2CBuyShopItemResult) GetShopId() int32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *S2CBuyShopItemResult) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *S2CBuyShopItemResult) GetItemNum() int32 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

func (m *S2CBuyShopItemResult) GetAddItem() *ItemInfo {
	if m != nil {
		return m.AddItem
	}
	return nil
}

// 通知客户端商店需要刷新
type S2CShopNeedRefreshNotify struct {
}

func (m *S2CShopNeedRefreshNotify) Reset()                    { *m = S2CShopNeedRefreshNotify{} }
func (m *S2CShopNeedRefreshNotify) String() string            { return proto.CompactTextString(m) }
func (*S2CShopNeedRefreshNotify) ProtoMessage()               {}
func (*S2CShopNeedRefreshNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{56} }

// 日常任务数据
type DialyTaskData struct {
	TaskId    int32 `protobuf:"varint,1,opt,name=TaskId" json:"TaskId,omitempty"`
	TaskValue int32 `protobuf:"varint,2,opt,name=TaskValue" json:"TaskValue,omitempty"`
	TaskState int32 `protobuf:"varint,3,opt,name=TaskState" json:"TaskState,omitempty"`
}

func (m *DialyTaskData) Reset()                    { *m = DialyTaskData{} }
func (m *DialyTaskData) String() string            { return proto.CompactTextString(m) }
func (*DialyTaskData) ProtoMessage()               {}
func (*DialyTaskData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{57} }

func (m *DialyTaskData) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *DialyTaskData) GetTaskValue() int32 {
	if m != nil {
		return m.TaskValue
	}
	return 0
}

func (m *DialyTaskData) GetTaskState() int32 {
	if m != nil {
		return m.TaskState
	}
	return 0
}

// 客户端向服务器请求日常任务数据
type C2SGetDialyTaskInfo struct {
}

func (m *C2SGetDialyTaskInfo) Reset()                    { *m = C2SGetDialyTaskInfo{} }
func (m *C2SGetDialyTaskInfo) String() string            { return proto.CompactTextString(m) }
func (*C2SGetDialyTaskInfo) ProtoMessage()               {}
func (*C2SGetDialyTaskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{58} }

// 服务器向客户端发送任务数据
type S2CSyncDialyTask struct {
	TaskList []*DialyTaskData `protobuf:"bytes,1,rep,name=TaskList" json:"TaskList,omitempty"`
}

func (m *S2CSyncDialyTask) Reset()                    { *m = S2CSyncDialyTask{} }
func (m *S2CSyncDialyTask) String() string            { return proto.CompactTextString(m) }
func (*S2CSyncDialyTask) ProtoMessage()               {}
func (*S2CSyncDialyTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{59} }

func (m *S2CSyncDialyTask) GetTaskList() []*DialyTaskData {
	if m != nil {
		return m.TaskList
	}
	return nil
}

// 服务器向客户端通知任务值变化
type S2CNotifyTaskValueChg struct {
	TaskId    int32 `protobuf:"varint,1,opt,name=TaskId" json:"TaskId,omitempty"`
	TaskValue int32 `protobuf:"varint,2,opt,name=TaskValue" json:"TaskValue,omitempty"`
	TaskState int32 `protobuf:"varint,3,opt,name=TaskState" json:"TaskState,omitempty"`
}

func (m *S2CNotifyTaskValueChg) Reset()                    { *m = S2CNotifyTaskValueChg{} }
func (m *S2CNotifyTaskValueChg) String() string            { return proto.CompactTextString(m) }
func (*S2CNotifyTaskValueChg) ProtoMessage()               {}
func (*S2CNotifyTaskValueChg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{60} }

func (m *S2CNotifyTaskValueChg) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *S2CNotifyTaskValueChg) GetTaskValue() int32 {
	if m != nil {
		return m.TaskValue
	}
	return 0
}

func (m *S2CNotifyTaskValueChg) GetTaskState() int32 {
	if m != nil {
		return m.TaskState
	}
	return 0
}

// 成就数据
type AchieveData struct {
	AchieveId    int32 `protobuf:"varint,1,opt,name=AchieveId" json:"AchieveId,omitempty"`
	AchieveValue int32 `protobuf:"varint,2,opt,name=AchieveValue" json:"AchieveValue,omitempty"`
	AchieveState int32 `protobuf:"varint,3,opt,name=AchieveState" json:"AchieveState,omitempty"`
}

func (m *AchieveData) Reset()                    { *m = AchieveData{} }
func (m *AchieveData) String() string            { return proto.CompactTextString(m) }
func (*AchieveData) ProtoMessage()               {}
func (*AchieveData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{61} }

func (m *AchieveData) GetAchieveId() int32 {
	if m != nil {
		return m.AchieveId
	}
	return 0
}

func (m *AchieveData) GetAchieveValue() int32 {
	if m != nil {
		return m.AchieveValue
	}
	return 0
}

func (m *AchieveData) GetAchieveState() int32 {
	if m != nil {
		return m.AchieveState
	}
	return 0
}

// 客户端向服务器请求成就数据
type C2SGetAchieve struct {
}

func (m *C2SGetAchieve) Reset()                    { *m = C2SGetAchieve{} }
func (m *C2SGetAchieve) String() string            { return proto.CompactTextString(m) }
func (*C2SGetAchieve) ProtoMessage()               {}
func (*C2SGetAchieve) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{62} }

// 服务器向客户端发送成就数据
type S2CSyncAchieveData struct {
	AchieveList []*AchieveData `protobuf:"bytes,1,rep,name=AchieveList" json:"AchieveList,omitempty"`
}

func (m *S2CSyncAchieveData) Reset()                    { *m = S2CSyncAchieveData{} }
func (m *S2CSyncAchieveData) String() string            { return proto.CompactTextString(m) }
func (*S2CSyncAchieveData) ProtoMessage()               {}
func (*S2CSyncAchieveData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{63} }

func (m *S2CSyncAchieveData) GetAchieveList() []*AchieveData {
	if m != nil {
		return m.AchieveList
	}
	return nil
}

// 服务器向客户端通知成就值变化
type S2CNotifyAchieveValueChg struct {
	AchieveId    int32 `protobuf:"varint,1,opt,name=AchieveId" json:"AchieveId,omitempty"`
	AchieveValue int32 `protobuf:"varint,2,opt,name=AchieveValue" json:"AchieveValue,omitempty"`
	AchieveState int32 `protobuf:"varint,3,opt,name=AchieveState" json:"AchieveState,omitempty"`
}

func (m *S2CNotifyAchieveValueChg) Reset()                    { *m = S2CNotifyAchieveValueChg{} }
func (m *S2CNotifyAchieveValueChg) String() string            { return proto.CompactTextString(m) }
func (*S2CNotifyAchieveValueChg) ProtoMessage()               {}
func (*S2CNotifyAchieveValueChg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{64} }

func (m *S2CNotifyAchieveValueChg) GetAchieveId() int32 {
	if m != nil {
		return m.AchieveId
	}
	return 0
}

func (m *S2CNotifyAchieveValueChg) GetAchieveValue() int32 {
	if m != nil {
		return m.AchieveValue
	}
	return 0
}

func (m *S2CNotifyAchieveValueChg) GetAchieveState() int32 {
	if m != nil {
		return m.AchieveState
	}
	return 0
}

// 客户端向服务器请求日常任务奖励
type C2SGetTaskReward struct {
	TaskId int32 `protobuf:"varint,1,opt,name=TaskId" json:"TaskId,omitempty"`
}

func (m *C2SGetTaskReward) Reset()                    { *m = C2SGetTaskReward{} }
func (m *C2SGetTaskReward) String() string            { return proto.CompactTextString(m) }
func (*C2SGetTaskReward) ProtoMessage()               {}
func (*C2SGetTaskReward) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{65} }

func (m *C2SGetTaskReward) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

// 服务器向客户端发送任务结果
type S2CRetTaskReward struct {
	TaskId  int32 `protobuf:"varint,1,opt,name=TaskId" json:"TaskId,omitempty"`
	Coin    int32 `protobuf:"varint,2,opt,name=Coin" json:"Coin,omitempty"`
	Diamond int32 `protobuf:"varint,3,opt,name=Diamond" json:"Diamond,omitempty"`
	Exp     int32 `protobuf:"varint,4,opt,name=Exp" json:"Exp,omitempty"`
	CurLvl  int32 `protobuf:"varint,5,opt,name=CurLvl" json:"CurLvl,omitempty"`
}

func (m *S2CRetTaskReward) Reset()                    { *m = S2CRetTaskReward{} }
func (m *S2CRetTaskReward) String() string            { return proto.CompactTextString(m) }
func (*S2CRetTaskReward) ProtoMessage()               {}
func (*S2CRetTaskReward) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{66} }

func (m *S2CRetTaskReward) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *S2CRetTaskReward) GetCoin() int32 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *S2CRetTaskReward) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *S2CRetTaskReward) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *S2CRetTaskReward) GetCurLvl() int32 {
	if m != nil {
		return m.CurLvl
	}
	return 0
}

// 客户端向服务器请求成就奖励
type C2SGetAchieveReward struct {
	AchieveReward int32 `protobuf:"varint,1,opt,name=AchieveReward" json:"AchieveReward,omitempty"`
}

func (m *C2SGetAchieveReward) Reset()                    { *m = C2SGetAchieveReward{} }
func (m *C2SGetAchieveReward) String() string            { return proto.CompactTextString(m) }
func (*C2SGetAchieveReward) ProtoMessage()               {}
func (*C2SGetAchieveReward) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{67} }

func (m *C2SGetAchieveReward) GetAchieveReward() int32 {
	if m != nil {
		return m.AchieveReward
	}
	return 0
}

// 服务器向客户端完成成就
type S2CRetAchieveReward struct {
	TaskId  int32 `protobuf:"varint,1,opt,name=TaskId" json:"TaskId,omitempty"`
	Coin    int32 `protobuf:"varint,2,opt,name=Coin" json:"Coin,omitempty"`
	Diamond int32 `protobuf:"varint,3,opt,name=Diamond" json:"Diamond,omitempty"`
	Exp     int32 `protobuf:"varint,4,opt,name=Exp" json:"Exp,omitempty"`
	CurLvl  int32 `protobuf:"varint,5,opt,name=CurLvl" json:"CurLvl,omitempty"`
}

func (m *S2CRetAchieveReward) Reset()                    { *m = S2CRetAchieveReward{} }
func (m *S2CRetAchieveReward) String() string            { return proto.CompactTextString(m) }
func (*S2CRetAchieveReward) ProtoMessage()               {}
func (*S2CRetAchieveReward) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{68} }

func (m *S2CRetAchieveReward) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *S2CRetAchieveReward) GetCoin() int32 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *S2CRetAchieveReward) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *S2CRetAchieveReward) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *S2CRetAchieveReward) GetCurLvl() int32 {
	if m != nil {
		return m.CurLvl
	}
	return 0
}

// ----------------------------------------------------------------------------
// 发送世界聊天消息
type C2SWorldChatSend struct {
	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (m *C2SWorldChatSend) Reset()                    { *m = C2SWorldChatSend{} }
func (m *C2SWorldChatSend) String() string            { return proto.CompactTextString(m) }
func (*C2SWorldChatSend) ProtoMessage()               {}
func (*C2SWorldChatSend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{69} }

func (m *C2SWorldChatSend) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type S2CWorldChatSendResult struct {
	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (m *S2CWorldChatSendResult) Reset()                    { *m = S2CWorldChatSendResult{} }
func (m *S2CWorldChatSendResult) String() string            { return proto.CompactTextString(m) }
func (*S2CWorldChatSendResult) ProtoMessage()               {}
func (*S2CWorldChatSendResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{70} }

func (m *S2CWorldChatSendResult) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// 拉取世界聊天消息
type C2SWorldChatMsgPull struct {
}

func (m *C2SWorldChatMsgPull) Reset()                    { *m = C2SWorldChatMsgPull{} }
func (m *C2SWorldChatMsgPull) String() string            { return proto.CompactTextString(m) }
func (*C2SWorldChatMsgPull) ProtoMessage()               {}
func (*C2SWorldChatMsgPull) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{71} }

type WorldChatItem struct {
	Content     []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	PlayerId    int32  `protobuf:"varint,2,opt,name=PlayerId" json:"PlayerId,omitempty"`
	PlayerName  string `protobuf:"bytes,3,opt,name=PlayerName" json:"PlayerName,omitempty"`
	PlayerHead  string `protobuf:"bytes,4,opt,name=PlayerHead" json:"PlayerHead,omitempty"`
	PlayerLevel int32  `protobuf:"varint,5,opt,name=PlayerLevel" json:"PlayerLevel,omitempty"`
	IsZaned     int32  `protobuf:"varint,6,opt,name=IsZaned" json:"IsZaned,omitempty"`
	IsFriend    int32  `protobuf:"varint,7,opt,name=IsFriend" json:"IsFriend,omitempty"`
	SendTime    int32  `protobuf:"varint,8,opt,name=SendTime" json:"SendTime,omitempty"`
}

func (m *WorldChatItem) Reset()                    { *m = WorldChatItem{} }
func (m *WorldChatItem) String() string            { return proto.CompactTextString(m) }
func (*WorldChatItem) ProtoMessage()               {}
func (*WorldChatItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{72} }

func (m *WorldChatItem) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *WorldChatItem) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *WorldChatItem) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *WorldChatItem) GetPlayerHead() string {
	if m != nil {
		return m.PlayerHead
	}
	return ""
}

func (m *WorldChatItem) GetPlayerLevel() int32 {
	if m != nil {
		return m.PlayerLevel
	}
	return 0
}

func (m *WorldChatItem) GetIsZaned() int32 {
	if m != nil {
		return m.IsZaned
	}
	return 0
}

func (m *WorldChatItem) GetIsFriend() int32 {
	if m != nil {
		return m.IsFriend
	}
	return 0
}

func (m *WorldChatItem) GetSendTime() int32 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

type S2CWorldChatMsgPullResult struct {
	Items []*WorldChatItem `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
}

func (m *S2CWorldChatMsgPullResult) Reset()                    { *m = S2CWorldChatMsgPullResult{} }
func (m *S2CWorldChatMsgPullResult) String() string            { return proto.CompactTextString(m) }
func (*S2CWorldChatMsgPullResult) ProtoMessage()               {}
func (*S2CWorldChatMsgPullResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{73} }

func (m *S2CWorldChatMsgPullResult) GetItems() []*WorldChatItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 返回世界聊天封禁时间
type S2CWorldChatForbid struct {
	EndTime string `protobuf:"bytes,1,opt,name=EndTime" json:"EndTime,omitempty"`
}

func (m *S2CWorldChatForbid) Reset()                    { *m = S2CWorldChatForbid{} }
func (m *S2CWorldChatForbid) String() string            { return proto.CompactTextString(m) }
func (*S2CWorldChatForbid) ProtoMessage()               {}
func (*S2CWorldChatForbid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{74} }

func (m *S2CWorldChatForbid) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

// 服务器向客户端同步引导数据
type S2CSyncGuideData struct {
	GuideIds []int32 `protobuf:"varint,1,rep,packed,name=GuideIds" json:"GuideIds,omitempty"`
}

func (m *S2CSyncGuideData) Reset()                    { *m = S2CSyncGuideData{} }
func (m *S2CSyncGuideData) String() string            { return proto.CompactTextString(m) }
func (*S2CSyncGuideData) ProtoMessage()               {}
func (*S2CSyncGuideData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{75} }

func (m *S2CSyncGuideData) GetGuideIds() []int32 {
	if m != nil {
		return m.GuideIds
	}
	return nil
}

// 客户端向服务器存储引导数据
type C2SSaveGuideData struct {
	GuideId int32 `protobuf:"varint,1,opt,name=GuideId" json:"GuideId,omitempty"`
}

func (m *C2SSaveGuideData) Reset()                    { *m = C2SSaveGuideData{} }
func (m *C2SSaveGuideData) String() string            { return proto.CompactTextString(m) }
func (*C2SSaveGuideData) ProtoMessage()               {}
func (*C2SSaveGuideData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{76} }

func (m *C2SSaveGuideData) GetGuideId() int32 {
	if m != nil {
		return m.GuideId
	}
	return 0
}

// 服务器向客户端返回引导存储
type S2CRetSaveGuideData struct {
	GuideId int32 `protobuf:"varint,1,opt,name=GuideId" json:"GuideId,omitempty"`
}

func (m *S2CRetSaveGuideData) Reset()                    { *m = S2CRetSaveGuideData{} }
func (m *S2CRetSaveGuideData) String() string            { return proto.CompactTextString(m) }
func (*S2CRetSaveGuideData) ProtoMessage()               {}
func (*S2CRetSaveGuideData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{77} }

func (m *S2CRetSaveGuideData) GetGuideId() int32 {
	if m != nil {
		return m.GuideId
	}
	return 0
}

func init() {
	proto.RegisterType((*C2S_TEST_COMMAND)(nil), "msg.client_message.C2S_TEST_COMMAND")
	proto.RegisterType((*ItemInfo)(nil), "msg.client_message.ItemInfo")
	proto.RegisterType((*FriendInfo)(nil), "msg.client_message.FriendInfo")
	proto.RegisterType((*PlayerStageInfo)(nil), "msg.client_message.PlayerStageInfo")
	proto.RegisterType((*S2CStagePass)(nil), "msg.client_message.S2CStagePass")
	proto.RegisterType((*C2SLoginRequest)(nil), "msg.client_message.C2SLoginRequest")
	proto.RegisterType((*ServerInfo)(nil), "msg.client_message.ServerInfo")
	proto.RegisterType((*S2CLoginResponse)(nil), "msg.client_message.S2CLoginResponse")
	proto.RegisterType((*S2COtherPlaceLogin)(nil), "msg.client_message.S2COtherPlaceLogin")
	proto.RegisterType((*C2SSelectServerRequest)(nil), "msg.client_message.C2SSelectServerRequest")
	proto.RegisterType((*S2CSelectServerResponse)(nil), "msg.client_message.S2CSelectServerResponse")
	proto.RegisterType((*C2S_MSG_DATA)(nil), "msg.client_message.C2S_MSG_DATA")
	proto.RegisterType((*S2C_MSG_DATA)(nil), "msg.client_message.S2C_MSG_DATA")
	proto.RegisterType((*C2SEnterGameRequest)(nil), "msg.client_message.C2SEnterGameRequest")
	proto.RegisterType((*S2CEnterGameResponse)(nil), "msg.client_message.S2CEnterGameResponse")
	proto.RegisterType((*S2CEnterGameCompleteNotify)(nil), "msg.client_message.S2CEnterGameCompleteNotify")
	proto.RegisterType((*C2SFriendSearch)(nil), "msg.client_message.C2SFriendSearch")
	proto.RegisterType((*C2SFriendSearchById)(nil), "msg.client_message.C2SFriendSearchById")
	proto.RegisterType((*S2CFriendSearchResult)(nil), "msg.client_message.S2CFriendSearchResult")
	proto.RegisterType((*C2SGetFriendList)(nil), "msg.client_message.C2SGetFriendList")
	proto.RegisterType((*FriendReq)(nil), "msg.client_message.FriendReq")
	proto.RegisterType((*S2CRetFriendListResult)(nil), "msg.client_message.S2CRetFriendListResult")
	proto.RegisterType((*S2CFriendStateNotify)(nil), "msg.client_message.S2CFriendStateNotify")
	proto.RegisterType((*S2CFriendReqNotify)(nil), "msg.client_message.S2CFriendReqNotify")
	proto.RegisterType((*C2SAddFriendByPId)(nil), "msg.client_message.C2SAddFriendByPId")
	proto.RegisterType((*C2SAddFriendByName)(nil), "msg.client_message.C2SAddFriendByName")
	proto.RegisterType((*S2CAddFriendResult)(nil), "msg.client_message.S2CAddFriendResult")
	proto.RegisterType((*C2SAgreeFriend)(nil), "msg.client_message.C2SAgreeFriend")
	proto.RegisterType((*S2CAgreeFriendResult)(nil), "msg.client_message.S2CAgreeFriendResult")
	proto.RegisterType((*C2SRefuseFriend)(nil), "msg.client_message.C2SRefuseFriend")
	proto.RegisterType((*S2CRefuseFriendResult)(nil), "msg.client_message.S2CRefuseFriendResult")
	proto.RegisterType((*C2SRemoveFriend)(nil), "msg.client_message.C2SRemoveFriend")
	proto.RegisterType((*S2CRemoveFriendResult)(nil), "msg.client_message.S2CRemoveFriendResult")
	proto.RegisterType((*C2SGiveFriendPoints)(nil), "msg.client_message.C2SGiveFriendPoints")
	proto.RegisterType((*FriendPointsResult)(nil), "msg.client_message.FriendPointsResult")
	proto.RegisterType((*S2CGiveFriendPointsResult)(nil), "msg.client_message.S2CGiveFriendPointsResult")
	proto.RegisterType((*C2SGetFriendPoints)(nil), "msg.client_message.C2SGetFriendPoints")
	proto.RegisterType((*FriendPoints)(nil), "msg.client_message.FriendPoints")
	proto.RegisterType((*S2CGetFriendPointsResult)(nil), "msg.client_message.S2CGetFriendPointsResult")
	proto.RegisterType((*C2SFriendChat)(nil), "msg.client_message.C2SFriendChat")
	proto.RegisterType((*S2CFriendChatResult)(nil), "msg.client_message.S2CFriendChatResult")
	proto.RegisterType((*C2SFriendGetUnreadMessageNum)(nil), "msg.client_message.C2SFriendGetUnreadMessageNum")
	proto.RegisterType((*FriendUnreadMessageNumData)(nil), "msg.client_message.FriendUnreadMessageNumData")
	proto.RegisterType((*S2CFriendGetUnreadMessageNumResult)(nil), "msg.client_message.S2CFriendGetUnreadMessageNumResult")
	proto.RegisterType((*C2SFriendPullUnreadMessage)(nil), "msg.client_message.C2SFriendPullUnreadMessage")
	proto.RegisterType((*FriendChatData)(nil), "msg.client_message.FriendChatData")
	proto.RegisterType((*S2CFriendPullUnreadMessageResult)(nil), "msg.client_message.S2CFriendPullUnreadMessageResult")
	proto.RegisterType((*C2SFriendConfirmUnreadMessage)(nil), "msg.client_message.C2SFriendConfirmUnreadMessage")
	proto.RegisterType((*S2CFriendConfirmUnreadMessageResult)(nil), "msg.client_message.S2CFriendConfirmUnreadMessageResult")
	proto.RegisterType((*C2SGetOnlineFriends)(nil), "msg.client_message.C2SGetOnlineFriends")
	proto.RegisterType((*S2CRetOnlineFriends)(nil), "msg.client_message.S2CRetOnlineFriends")
	proto.RegisterType((*C2SShopItems)(nil), "msg.client_message.C2SShopItems")
	proto.RegisterType((*S2CShopItem)(nil), "msg.client_message.S2CShopItem")
	proto.RegisterType((*S2CShopItemsResult)(nil), "msg.client_message.S2CShopItemsResult")
	proto.RegisterType((*C2SBuyShopItem)(nil), "msg.client_message.C2SBuyShopItem")
	proto.RegisterType((*S2CBuyShopItemResult)(nil), "msg.client_message.S2CBuyShopItemResult")
	proto.RegisterType((*S2CShopNeedRefreshNotify)(nil), "msg.client_message.S2CShopNeedRefreshNotify")
	proto.RegisterType((*DialyTaskData)(nil), "msg.client_message.DialyTaskData")
	proto.RegisterType((*C2SGetDialyTaskInfo)(nil), "msg.client_message.C2SGetDialyTaskInfo")
	proto.RegisterType((*S2CSyncDialyTask)(nil), "msg.client_message.S2CSyncDialyTask")
	proto.RegisterType((*S2CNotifyTaskValueChg)(nil), "msg.client_message.S2CNotifyTaskValueChg")
	proto.RegisterType((*AchieveData)(nil), "msg.client_message.AchieveData")
	proto.RegisterType((*C2SGetAchieve)(nil), "msg.client_message.C2SGetAchieve")
	proto.RegisterType((*S2CSyncAchieveData)(nil), "msg.client_message.S2CSyncAchieveData")
	proto.RegisterType((*S2CNotifyAchieveValueChg)(nil), "msg.client_message.S2CNotifyAchieveValueChg")
	proto.RegisterType((*C2SGetTaskReward)(nil), "msg.client_message.C2SGetTaskReward")
	proto.RegisterType((*S2CRetTaskReward)(nil), "msg.client_message.S2CRetTaskReward")
	proto.RegisterType((*C2SGetAchieveReward)(nil), "msg.client_message.C2SGetAchieveReward")
	proto.RegisterType((*S2CRetAchieveReward)(nil), "msg.client_message.S2CRetAchieveReward")
	proto.RegisterType((*C2SWorldChatSend)(nil), "msg.client_message.C2SWorldChatSend")
	proto.RegisterType((*S2CWorldChatSendResult)(nil), "msg.client_message.S2CWorldChatSendResult")
	proto.RegisterType((*C2SWorldChatMsgPull)(nil), "msg.client_message.C2SWorldChatMsgPull")
	proto.RegisterType((*WorldChatItem)(nil), "msg.client_message.WorldChatItem")
	proto.RegisterType((*S2CWorldChatMsgPullResult)(nil), "msg.client_message.S2CWorldChatMsgPullResult")
	proto.RegisterType((*S2CWorldChatForbid)(nil), "msg.client_message.S2CWorldChatForbid")
	proto.RegisterType((*S2CSyncGuideData)(nil), "msg.client_message.S2CSyncGuideData")
	proto.RegisterType((*C2SSaveGuideData)(nil), "msg.client_message.C2SSaveGuideData")
	proto.RegisterType((*S2CRetSaveGuideData)(nil), "msg.client_message.S2CRetSaveGuideData")
	proto.RegisterEnum("msg.client_message.E_ERR", E_ERR_name, E_ERR_value)
}

func init() { proto.RegisterFile("client_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 3025 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x5a, 0x4b, 0x73, 0xdc, 0xd6,
	0x95, 0x9e, 0xe6, 0x43, 0x6c, 0x1e, 0x49, 0x14, 0x0c, 0x53, 0x52, 0x8b, 0xa2, 0x28, 0x0a, 0x92,
	0x65, 0x8e, 0x2c, 0x53, 0x36, 0x5d, 0x63, 0xab, 0x6a, 0xc6, 0x53, 0x06, 0xd1, 0x97, 0xcd, 0x2e,
	0x75, 0x03, 0xed, 0x0b, 0x90, 0x14, 0x35, 0xae, 0x42, 0xc1, 0xdd, 0x97, 0x64, 0x97, 0x48, 0x34,
	0xd5, 0x00, 0x69, 0x73, 0xe7, 0x9a, 0xaa, 0xf9, 0x01, 0xb3, 0x99, 0x49, 0xe2, 0xe7, 0xef, 0xc8,
	0xd3, 0xab, 0x2c, 0x92, 0x5d, 0x2a, 0x8b, 0xa4, 0xf2, 0x52, 0x5e, 0xce, 0x2a, 0x9b, 0x64, 0x13,
	0x27, 0x7e, 0xa4, 0xee, 0x0b, 0xf7, 0xa2, 0xd9, 0x4d, 0x52, 0xa9, 0x8a, 0xb5, 0x11, 0xce, 0xb9,
	0xdf, 0x39, 0xf7, 0xbc, 0xee, 0xc1, 0xb9, 0x68, 0xc2, 0x64, 0x73, 0xbb, 0x4d, 0xe2, 0x34, 0xdc,
	0x21, 0x49, 0x12, 0x6d, 0x92, 0xf9, 0xdd, 0x6e, 0x27, 0xed, 0x98, 0xe6, 0x4e, 0xb2, 0x39, 0x9f,
	0x5f, 0xb1, 0xee, 0x82, 0xe1, 0x2c, 0xf8, 0x61, 0x80, 0xfc, 0x20, 0x74, 0xbc, 0x7a, 0xdd, 0x76,
	0xcb, 0xa6, 0x01, 0xc3, 0xcd, 0x9d, 0x56, 0xa9, 0x30, 0x5b, 0x98, 0x1b, 0xc7, 0xf4, 0xd1, 0x34,
	0x61, 0x24, 0xea, 0x6e, 0x26, 0xa5, 0xa1, 0xd9, 0xe1, 0xb9, 0x71, 0xcc, 0x9e, 0xad, 0x2d, 0x28,
	0x56, 0x53, 0xb2, 0x53, 0x8d, 0x37, 0x3a, 0xe6, 0x34, 0x8c, 0xd3, 0x67, 0x67, 0x63, 0xb3, 0xca,
	0xe5, 0x46, 0xb1, 0x62, 0x98, 0x25, 0x18, 0xa3, 0x84, 0xbb, 0xb7, 0x53, 0x1a, 0x62, 0x6b, 0x92,
	0x34, 0x6f, 0xc0, 0x59, 0x4c, 0x76, 0xa2, 0x76, 0xec, 0x93, 0x66, 0x27, 0x6e, 0x25, 0xa5, 0x61,
	0xb6, 0x9e, 0x67, 0x5a, 0xdf, 0x1c, 0x06, 0x58, 0xea, 0xb6, 0x49, 0xdc, 0x62, 0x9b, 0x4d, 0x41,
	0xb1, 0xb1, 0x1d, 0x1d, 0x90, 0x6e, 0xb6, 0x57, 0x46, 0x53, 0x43, 0xdd, 0x68, 0x87, 0xb0, 0x7d,
	0xc6, 0x31, 0x7b, 0xa6, 0xbc, 0x65, 0x12, 0xb5, 0x98, 0xee, 0x71, 0xcc, 0x9e, 0xcd, 0x49, 0x18,
	0xad, 0x91, 0x7d, 0xb2, 0x5d, 0x1a, 0x61, 0x0a, 0x38, 0x41, 0x35, 0xaf, 0xb6, 0x77, 0xf9, 0xc2,
	0x28, 0xd7, 0x2c, 0x69, 0xea, 0x62, 0x2d, 0x4a, 0xd2, 0x5a, 0x67, 0xb3, 0x1d, 0x97, 0x4e, 0x71,
	0x17, 0x33, 0x86, 0x69, 0xc1, 0x19, 0x6e, 0x61, 0xa3, 0xd3, 0x8e, 0xd3, 0xa4, 0x34, 0xc6, 0x00,
	0x39, 0x9e, 0x39, 0x07, 0xe7, 0x6a, 0x64, 0x23, 0xad, 0xb4, 0xf7, 0x89, 0x74, 0xb7, 0xc8, 0x60,
	0xbd, 0x6c, 0xf3, 0x16, 0x18, 0x2b, 0x71, 0x97, 0x44, 0xad, 0x3a, 0xcf, 0x12, 0x8d, 0xdc, 0x38,
	0x83, 0x1e, 0xe2, 0xd3, 0x64, 0x3d, 0x88, 0xe2, 0x12, 0xb0, 0x65, 0xfa, 0x68, 0xce, 0x00, 0x54,
	0x93, 0x07, 0x51, 0x1c, 0x74, 0x5a, 0xd1, 0x41, 0xe9, 0xf4, 0x6c, 0x61, 0xae, 0x88, 0x35, 0x0e,
	0xf5, 0xb2, 0x9a, 0x78, 0xf1, 0x76, 0x3b, 0x26, 0xa5, 0x33, 0x6c, 0x35, 0xa3, 0xcd, 0x9b, 0x30,
	0xb1, 0xd4, 0x49, 0x52, 0xd2, 0x25, 0x2d, 0x27, 0x4a, 0xe9, 0xbe, 0x13, 0x4c, 0x71, 0x0f, 0x97,
	0xfa, 0xe2, 0x44, 0x31, 0x67, 0x0a, 0xe0, 0x39, 0xee, 0x4b, 0x0f, 0xdb, 0x7a, 0xbf, 0x00, 0xe7,
	0x78, 0x7a, 0xfc, 0x34, 0xda, 0x24, 0xc7, 0x66, 0x70, 0x12, 0x46, 0xfd, 0x66, 0xa7, 0x4b, 0x44,
	0xa9, 0x70, 0x22, 0xcb, 0xeb, 0xb0, 0x96, 0x57, 0x03, 0x86, 0x6b, 0xfb, 0x32, 0x83, 0xf4, 0x91,
	0xa2, 0xaa, 0xcd, 0x4e, 0xcc, 0x72, 0x37, 0x8e, 0xd9, 0x33, 0x8d, 0x86, 0xb3, 0x97, 0xa4, 0x9d,
	0x1d, 0xb6, 0x72, 0x8a, 0xad, 0x68, 0x1c, 0xeb, 0x47, 0x23, 0x70, 0xc6, 0x5f, 0x70, 0x98, 0x71,
	0x8d, 0x28, 0x49, 0x68, 0xb5, 0x72, 0x4b, 0xa5, 0x6d, 0x92, 0x64, 0xa6, 0xa5, 0x51, 0x37, 0xc9,
	0x4c, 0xa3, 0x84, 0x32, 0x78, 0x58, 0x37, 0x78, 0x0a, 0x8a, 0x41, 0x67, 0x97, 0x2f, 0x70, 0x0b,
	0x33, 0xda, 0xbc, 0x0b, 0xc5, 0x95, 0x84, 0xd0, 0x33, 0x90, 0x94, 0x46, 0x67, 0x87, 0xe7, 0x4e,
	0x2f, 0x4c, 0xcf, 0x1f, 0x3e, 0x9a, 0xf3, 0xf2, 0x74, 0xe1, 0x0c, 0x4d, 0x6d, 0xab, 0x90, 0xd4,
	0xe9, 0x64, 0x25, 0x28, 0x49, 0xaa, 0xb3, 0x42, 0xd2, 0x36, 0xd3, 0x39, 0x76, 0x12, 0x9d, 0x12,
	0x6d, 0xda, 0x30, 0x8e, 0xa3, 0xf8, 0x21, 0x37, 0xa7, 0xc8, 0x44, 0xaf, 0xf7, 0x13, 0xed, 0x49,
	0x22, 0x56, 0x52, 0x26, 0x82, 0xd3, 0xe2, 0x7c, 0x32, 0x25, 0xe3, 0x27, 0x57, 0xa2, 0xcb, 0x99,
	0x17, 0xe0, 0x14, 0x26, 0xc9, 0xde, 0x76, 0xca, 0xca, 0x72, 0x14, 0x0b, 0xca, 0x5c, 0x84, 0xb3,
	0xd2, 0xda, 0xa5, 0x76, 0x37, 0x49, 0x4b, 0x67, 0x4f, 0xe0, 0x60, 0x5e, 0x44, 0xd7, 0xf1, 0x12,
	0xcd, 0x5b, 0x69, 0xe2, 0x49, 0x74, 0x30, 0x11, 0x5e, 0xf4, 0x29, 0x7a, 0x3b, 0xed, 0x46, 0x76,
	0xab, 0xc5, 0xb2, 0x90, 0x15, 0x7d, 0x8e, 0x6d, 0xad, 0xc3, 0x39, 0x67, 0xc1, 0x67, 0xad, 0x01,
	0x93, 0x47, 0x7b, 0x24, 0x49, 0x69, 0xb5, 0xda, 0xcd, 0xa6, 0x6c, 0xaa, 0x76, 0xb3, 0xc9, 0x4e,
	0x41, 0x94, 0x24, 0x6f, 0x75, 0xba, 0x2d, 0xd1, 0xaf, 0x32, 0x9a, 0x26, 0xda, 0xd9, 0x8a, 0xe2,
	0x98, 0x6c, 0x8b, 0x92, 0x97, 0xa4, 0xf5, 0x1a, 0x80, 0x4f, 0xba, 0xfb, 0xa4, 0xcb, 0x4e, 0xd2,
	0x04, 0x0c, 0x65, 0x75, 0x3a, 0x34, 0xa0, 0xff, 0x51, 0x4c, 0x43, 0xa8, 0x19, 0xaa, 0x36, 0xac,
	0x14, 0x0c, 0x7f, 0xc1, 0x11, 0xc6, 0x25, 0xbb, 0x9d, 0x38, 0x21, 0x7d, 0xac, 0x9b, 0x84, 0xd1,
	0xa0, 0xf3, 0x90, 0xc4, 0x42, 0x15, 0x27, 0xcc, 0xbb, 0x30, 0xc6, 0x77, 0xa7, 0xad, 0x9a, 0x06,
	0x70, 0xa6, 0x5f, 0x00, 0x95, 0x81, 0x58, 0xc2, 0xad, 0x49, 0x30, 0xfd, 0x05, 0xc7, 0x4b, 0xb7,
	0x48, 0xb7, 0xb1, 0x1d, 0x35, 0x09, 0xdb, 0xdf, 0x7a, 0x03, 0x2e, 0x38, 0x0b, 0xbe, 0x4f, 0xb6,
	0x49, 0x33, 0xe5, 0xc8, 0xc1, 0xf1, 0xea, 0x6f, 0xd1, 0x14, 0x14, 0xc5, 0x76, 0x2d, 0x71, 0x02,
	0x33, 0xda, 0x7a, 0x1d, 0x2e, 0xd2, 0xa3, 0x9d, 0xd3, 0xfe, 0x84, 0x0e, 0xf7, 0x06, 0x2f, 0x86,
	0x33, 0xf4, 0x7d, 0x59, 0xf7, 0x2b, 0x61, 0xd9, 0x0e, 0xec, 0xe3, 0x5a, 0x59, 0x1f, 0x8d, 0x25,
	0x18, 0xab, 0x27, 0x9b, 0x4e, 0xa7, 0x25, 0x3b, 0x86, 0x24, 0x69, 0xf2, 0xca, 0x51, 0x1a, 0xb1,
	0x7e, 0x71, 0x06, 0xb3, 0x67, 0xeb, 0x0d, 0xd6, 0x9d, 0xd4, 0x7e, 0xd3, 0x30, 0x8e, 0xba, 0xdd,
	0x4e, 0x97, 0xc9, 0x8b, 0x37, 0x6d, 0xc6, 0xa0, 0xd6, 0x30, 0xa2, 0x9e, 0x6c, 0xca, 0x92, 0x92,
	0x74, 0xa6, 0x7d, 0x58, 0xd3, 0xfe, 0x2a, 0x3c, 0xed, 0x2c, 0xf8, 0x28, 0x4e, 0x49, 0xb7, 0x12,
	0xed, 0x90, 0x27, 0x8c, 0xbd, 0x55, 0x86, 0x49, 0x7f, 0xc1, 0xd1, 0xc4, 0x07, 0x06, 0x57, 0x0f,
	0xd3, 0x50, 0x3e, 0x4c, 0xd6, 0x34, 0x4c, 0xe9, 0x5a, 0x9c, 0xce, 0xce, 0xee, 0x36, 0x49, 0x89,
	0xdb, 0x49, 0xdb, 0x1b, 0x07, 0xd6, 0x75, 0x76, 0x94, 0x78, 0x9b, 0xf0, 0x49, 0xd4, 0x6d, 0x6e,
	0x51, 0xf5, 0xf7, 0xc8, 0x81, 0x54, 0x7f, 0x8f, 0x1c, 0x58, 0x2f, 0x32, 0x3f, 0x74, 0xd0, 0xe2,
	0x41, 0xb5, 0x75, 0x54, 0x72, 0x2c, 0x0f, 0xce, 0xfb, 0x0b, 0x8e, 0x2e, 0x22, 0xba, 0xcd, 0xcb,
	0x59, 0x17, 0x2a, 0x0c, 0xae, 0x70, 0x35, 0x8e, 0xc8, 0x2e, 0x65, 0xbd, 0xc0, 0x26, 0xa9, 0x0a,
	0x49, 0xf9, 0x5a, 0xad, 0x9d, 0xa4, 0x34, 0x5b, 0xcb, 0x51, 0xc2, 0xdf, 0x87, 0xcc, 0x82, 0x22,
	0x56, 0x0c, 0x8b, 0xc0, 0x38, 0xc7, 0x62, 0xf2, 0xe8, 0x89, 0xa7, 0x9a, 0xfe, 0xaf, 0x1d, 0x39,
	0xeb, 0x8c, 0xa8, 0x59, 0xc7, 0xfa, 0x69, 0x01, 0x2e, 0xf8, 0x0b, 0x0e, 0xd6, 0x2d, 0x13, 0xbe,
	0xce, 0xc8, 0xc1, 0x2a, 0x38, 0xd8, 0x95, 0xe5, 0xa4, 0x71, 0xcc, 0xff, 0x94, 0xeb, 0x54, 0x86,
	0x4d, 0x7f, 0xc7, 0xc7, 0x43, 0x93, 0x30, 0x5f, 0x84, 0x11, 0x4c, 0x1e, 0xc9, 0x5e, 0x71, 0x65,
	0xb0, 0x24, 0x26, 0x8f, 0x30, 0x83, 0x9a, 0xb7, 0xe1, 0x29, 0x39, 0x0e, 0xf1, 0xb9, 0x89, 0xce,
	0x16, 0xfc, 0x0d, 0x7a, 0x78, 0xc1, 0xda, 0x62, 0x15, 0x28, 0xb2, 0x98, 0x46, 0xb2, 0x6a, 0x68,
	0xe0, 0x19, 0xa9, 0xf9, 0xa5, 0x18, 0xe6, 0x02, 0x8c, 0x50, 0x53, 0x59, 0x3c, 0x8f, 0x77, 0x88,
	0x61, 0x2d, 0xc4, 0xfa, 0x57, 0x66, 0xad, 0xd8, 0xe7, 0x0e, 0x0c, 0x63, 0xf2, 0x88, 0xed, 0x70,
	0xac, 0x7f, 0x14, 0x69, 0xdd, 0x81, 0xa7, 0x9c, 0x05, 0xdf, 0x6e, 0xb5, 0x38, 0x7f, 0xf1, 0xa0,
	0x71, 0x4c, 0x9d, 0xce, 0x81, 0x99, 0x17, 0x90, 0x33, 0x2d, 0xab, 0x88, 0x82, 0xaa, 0x08, 0xeb,
	0x05, 0x66, 0x61, 0x86, 0x14, 0x29, 0x3e, 0x4a, 0xf7, 0x6d, 0x98, 0xa0, 0xba, 0x37, 0xbb, 0x84,
	0x70, 0x99, 0x23, 0xd1, 0x1f, 0x17, 0x58, 0xb0, 0x35, 0xf8, 0xf1, 0x5b, 0x3c, 0x41, 0xe9, 0xf6,
	0x1f, 0xc9, 0x65, 0x41, 0x8f, 0x6a, 0xc3, 0xbb, 0x3e, 0xa6, 0x9f, 0x3a, 0x6a, 0x4c, 0x1f, 0xeb,
	0x19, 0xd3, 0xad, 0xe7, 0x59, 0x33, 0xc1, 0x64, 0x63, 0x2f, 0x39, 0x89, 0xc7, 0x15, 0xd6, 0x23,
	0x74, 0xb8, 0xf0, 0xb8, 0x4f, 0xf8, 0x8f, 0x6c, 0x71, 0x72, 0xdf, 0x9d, 0xce, 0xfe, 0x49, 0xf6,
	0x7d, 0x49, 0xec, 0xab, 0xe0, 0x27, 0x48, 0x26, 0xef, 0x81, 0xf4, 0x78, 0xe4, 0x6e, 0x1d, 0x53,
	0x50, 0x14, 0xb5, 0xdc, 0x62, 0x0d, 0x6d, 0x14, 0x67, 0xb4, 0xf5, 0xfd, 0x02, 0x98, 0x3a, 0x58,
	0xed, 0xa2, 0x89, 0x14, 0x74, 0x11, 0x3a, 0xa3, 0x89, 0x2b, 0x0e, 0xf7, 0x51, 0x50, 0x34, 0x7b,
	0xec, 0x4d, 0x23, 0x73, 0xca, 0x88, 0xc3, 0xf7, 0xbb, 0x91, 0x3e, 0xf7, 0x3b, 0x73, 0x16, 0x4e,
	0x57, 0x13, 0x76, 0x37, 0xa1, 0xd6, 0xb3, 0x54, 0x17, 0xb1, 0xce, 0xa2, 0x7d, 0x6a, 0x31, 0x6a,
	0x3e, 0x14, 0x3b, 0xf3, 0x9c, 0x6b, 0x1c, 0xeb, 0x7f, 0x0b, 0x70, 0xc9, 0x5f, 0x70, 0x7a, 0x9d,
	0x17, 0xfe, 0x2c, 0x01, 0x70, 0x9a, 0xbd, 0xff, 0x78, 0x57, 0xbf, 0x39, 0xf8, 0xac, 0xea, 0xb2,
	0x58, 0x93, 0xec, 0xdf, 0x9a, 0x86, 0x06, 0xb5, 0xa6, 0x17, 0xd8, 0xc1, 0xcd, 0xde, 0x07, 0x27,
	0x48, 0xc7, 0x62, 0xfe, 0x12, 0xf9, 0x8f, 0xe4, 0xc1, 0x7a, 0x03, 0x4a, 0x34, 0x10, 0xf9, 0x5d,
	0x45, 0x1c, 0x5e, 0xeb, 0x13, 0x87, 0xd9, 0x63, 0xe3, 0xa0, 0xc9, 0x58, 0x08, 0xce, 0x66, 0xef,
	0x59, 0x67, 0x2b, 0x3a, 0xfa, 0xe8, 0xd3, 0x19, 0xb6, 0x13, 0xa7, 0x24, 0x4e, 0x99, 0x8d, 0x67,
	0xb0, 0x24, 0xad, 0x7b, 0xf0, 0x74, 0xd6, 0x4b, 0xa9, 0x9a, 0x13, 0xf4, 0x91, 0xc1, 0xca, 0xfe,
	0x03, 0xa6, 0x33, 0x9b, 0x2a, 0x24, 0x3d, 0x74, 0x41, 0x9e, 0x96, 0x6f, 0xd9, 0x6a, 0x2b, 0x11,
	0x21, 0x57, 0x0c, 0xeb, 0x3e, 0x4c, 0x71, 0xa2, 0x57, 0x8e, 0x65, 0xfc, 0xa8, 0x0c, 0xcc, 0x00,
	0x68, 0xd7, 0x73, 0x9e, 0x05, 0x8d, 0x63, 0x6d, 0x81, 0x95, 0x39, 0xd9, 0xc7, 0xae, 0xec, 0x6e,
	0x33, 0xa2, 0x65, 0x63, 0x7e, 0x70, 0x36, 0xfa, 0xd9, 0x27, 0xa6, 0xb8, 0xbb, 0x30, 0x95, 0x45,
	0xa0, 0xb1, 0xb7, 0xbd, 0x9d, 0x83, 0x1e, 0xe5, 0x83, 0xb5, 0x04, 0x13, 0x2a, 0x0b, 0xcc, 0x63,
	0x2d, 0xce, 0x85, 0x5c, 0x9c, 0xf9, 0xa0, 0x1d, 0xb7, 0x82, 0xf6, 0x8e, 0xbc, 0x9b, 0x67, 0xb4,
	0xb5, 0x0f, 0xb3, 0x99, 0xaf, 0x87, 0x2c, 0x38, 0x41, 0x57, 0x79, 0x59, 0x44, 0x81, 0x4f, 0x18,
	0xd6, 0xe0, 0x28, 0x48, 0x3b, 0x85, 0xe7, 0xff, 0x05, 0x57, 0x54, 0x3d, 0x76, 0xe2, 0x8d, 0x76,
	0x77, 0xe7, 0xc4, 0xce, 0x1f, 0x9b, 0xc0, 0x08, 0xae, 0xab, 0x2a, 0xed, 0xa3, 0xfc, 0x04, 0x7e,
	0x1d, 0xb7, 0xc5, 0xb3, 0xbc, 0x67, 0x93, 0x94, 0x7f, 0x7e, 0xe1, 0x72, 0x89, 0x3e, 0xe0, 0x8e,
	0xf2, 0x01, 0x17, 0xb1, 0x13, 0x83, 0x7b, 0x81, 0xd3, 0x30, 0x2e, 0x4f, 0x48, 0x56, 0xdb, 0x19,
	0x43, 0xaa, 0x19, 0x52, 0x6a, 0x9e, 0x65, 0xb7, 0x17, 0x7f, 0xab, 0xb3, 0xcb, 0x6f, 0xdc, 0x17,
	0x61, 0x2c, 0xd9, 0xea, 0xec, 0x86, 0x6d, 0x69, 0xfa, 0x29, 0x4a, 0x56, 0x5b, 0xd6, 0x16, 0x9c,
	0xa6, 0x37, 0x27, 0x01, 0xa4, 0x38, 0x7a, 0x0f, 0xd6, 0x70, 0x94, 0xac, 0xb6, 0xcc, 0x4b, 0x50,
	0xdc, 0x26, 0x1b, 0x69, 0x18, 0xab, 0x6f, 0x7b, 0x94, 0xa6, 0xe7, 0xee, 0x19, 0x98, 0xe8, 0xb2,
	0x36, 0x1f, 0x26, 0xf9, 0x8f, 0x7b, 0xdd, 0xdc, 0xc7, 0xbd, 0x16, 0x9b, 0x5a, 0x32, 0x93, 0x44,
	0x50, 0x07, 0x19, 0x66, 0xfe, 0x1b, 0x8c, 0xf2, 0x8f, 0x1c, 0xbc, 0x54, 0xae, 0xf6, 0xbd, 0x7e,
	0x2a, 0x7d, 0x98, 0xa3, 0xad, 0x32, 0x9b, 0x74, 0x16, 0xf7, 0x0e, 0x4e, 0xe4, 0x12, 0x5b, 0xd0,
	0x5c, 0x6a, 0xf3, 0xcf, 0x95, 0xd6, 0x7b, 0x7c, 0x02, 0xd2, 0xd4, 0x1c, 0x67, 0xae, 0xb6, 0xcb,
	0xd0, 0xc0, 0x5d, 0x86, 0x73, 0xbb, 0x98, 0xaf, 0x40, 0x31, 0x6a, 0xb5, 0x42, 0x4a, 0xb2, 0xf7,
	0xe5, 0x71, 0x5f, 0x29, 0xc6, 0xa2, 0x16, 0xfb, 0x80, 0x62, 0x4d, 0xb1, 0xde, 0x4f, 0x4d, 0x73,
	0x09, 0x69, 0x61, 0xb2, 0xd1, 0x25, 0xc9, 0x96, 0xb8, 0x46, 0x35, 0xe1, 0x6c, 0xb9, 0x1d, 0x6d,
	0x1f, 0x04, 0x51, 0xf2, 0x90, 0x1d, 0xf4, 0x0b, 0x70, 0x8a, 0x3e, 0x67, 0x45, 0x2b, 0x28, 0x5a,
	0x52, 0xf4, 0x69, 0x35, 0xda, 0xde, 0x93, 0xe7, 0x5c, 0x31, 0xe4, 0x2a, 0x1b, 0xa5, 0x85, 0xdd,
	0x8a, 0x61, 0x9d, 0x97, 0xe5, 0x9c, 0x6d, 0xc5, 0x46, 0xe7, 0xd7, 0xd9, 0x07, 0x07, 0xff, 0x20,
	0x6e, 0x66, 0x7c, 0xf3, 0x55, 0x28, 0xd2, 0xff, 0xd9, 0xbd, 0x82, 0xf7, 0xbe, 0x6b, 0xfd, 0x9c,
	0xcc, 0xd9, 0x8c, 0x33, 0x11, 0xeb, 0x21, 0x9b, 0x90, 0xb8, 0x6f, 0x99, 0x75, 0xce, 0xd6, 0xe6,
	0x3f, 0xc5, 0xad, 0x04, 0x4e, 0xdb, 0xcd, 0xad, 0x36, 0xd9, 0x27, 0x2c, 0x72, 0xd3, 0x30, 0x2e,
	0x48, 0xf5, 0xb1, 0x3b, 0x63, 0x98, 0x16, 0x9c, 0x11, 0x84, 0xbe, 0x57, 0x8e, 0xa7, 0x61, 0xf4,
	0x1d, 0x73, 0x3c, 0xeb, 0x1c, 0x7b, 0xd5, 0x56, 0x48, 0x2a, 0xb8, 0xd6, 0x1a, 0x3f, 0x28, 0x07,
	0x71, 0x53, 0x37, 0xc6, 0xce, 0x6c, 0xd3, 0x42, 0xd9, 0xf7, 0x54, 0x68, 0x52, 0x58, 0x97, 0xb1,
	0xde, 0x29, 0xb0, 0xba, 0xe1, 0xc1, 0xd4, 0xed, 0xa4, 0xf1, 0xfc, 0x6a, 0x9c, 0xbd, 0x25, 0xef,
	0xce, 0x34, 0xe8, 0x98, 0xbc, 0x15, 0x75, 0x5b, 0x83, 0x32, 0x69, 0xfd, 0x77, 0x81, 0x95, 0x13,
	0x3e, 0x09, 0x98, 0x0e, 0xea, 0xec, 0x3b, 0x1d, 0x37, 0x8c, 0x3d, 0xd3, 0x57, 0x5c, 0xb9, 0x1d,
	0xed, 0x74, 0x62, 0xf9, 0xc1, 0x48, 0x92, 0xb4, 0x61, 0xa2, 0xb7, 0x77, 0xe5, 0x17, 0x65, 0xf4,
	0xf6, 0x2e, 0xd5, 0xeb, 0xec, 0x75, 0x6b, 0xfb, 0xf2, 0xf7, 0x00, 0x41, 0x59, 0xff, 0x2e, 0x2b,
	0x5d, 0xb8, 0x21, 0xcc, 0xb8, 0x01, 0x67, 0x73, 0x0c, 0x61, 0x4d, 0x9e, 0x69, 0xfd, 0x4f, 0x41,
	0x76, 0xf3, 0xbc, 0xf4, 0x57, 0xed, 0xc4, 0x6d, 0x16, 0xf5, 0xb5, 0x4e, 0x77, 0x9b, 0xbd, 0x57,
	0xe9, 0xdb, 0x7c, 0xf0, 0xfb, 0xdf, 0x5a, 0x60, 0x5f, 0x11, 0x72, 0x68, 0xd1, 0xfd, 0x06, 0xcb,
	0xf0, 0x86, 0x90, 0xc9, 0xd4, 0x93, 0x4d, 0x3a, 0x1d, 0x58, 0x9f, 0x16, 0xe0, 0x6c, 0xc6, 0x64,
	0xdd, 0xf8, 0xc8, 0xb1, 0x63, 0xd0, 0xb5, 0x8a, 0xbe, 0x5e, 0xf9, 0xb3, 0xf6, 0xdb, 0x80, 0xc6,
	0x51, 0xeb, 0xda, 0x37, 0x11, 0x8d, 0x43, 0x2f, 0x1e, 0x9c, 0xd2, 0x7f, 0xf2, 0xd1, 0x59, 0xec,
	0xa7, 0xab, 0xe4, 0x41, 0x14, 0x93, 0x96, 0xfc, 0xe0, 0x2e, 0x48, 0xfe, 0x2b, 0x0a, 0x7f, 0x0f,
	0x8b, 0x7b, 0x66, 0x46, 0xe7, 0x46, 0xa5, 0x62, 0xcf, 0xa8, 0x14, 0xb0, 0x9b, 0x4a, 0x6f, 0x48,
	0x44, 0x24, 0x5f, 0x81, 0x51, 0xfe, 0x09, 0xfd, 0x88, 0x96, 0x98, 0x0b, 0x1c, 0xe6, 0x78, 0x6b,
	0x9e, 0x35, 0x87, 0x6c, 0x69, 0xa9, 0xd3, 0x7d, 0xb3, 0xcd, 0x92, 0x89, 0x84, 0x19, 0xfc, 0xa6,
	0x2a, 0x49, 0x6b, 0x3e, 0x6b, 0xc9, 0x95, 0xbd, 0x76, 0x8b, 0xc8, 0x61, 0x97, 0x11, 0x6a, 0x96,
	0xc8, 0x68, 0x51, 0x2a, 0x7e, 0xb4, 0x4f, 0x14, 0xbe, 0x04, 0x63, 0x62, 0x5d, 0xfe, 0x50, 0x22,
	0x48, 0xeb, 0x8e, 0xac, 0xef, 0x13, 0x0a, 0xdc, 0xfa, 0xf1, 0x04, 0x8c, 0xa2, 0x10, 0x61, 0x6c,
	0x16, 0x61, 0xc4, 0xf5, 0x5c, 0x64, 0xfc, 0x8b, 0x79, 0x1e, 0x8a, 0x55, 0x37, 0x40, 0xd8, 0xb5,
	0x6b, 0xc6, 0x97, 0xf2, 0x5f, 0xc1, 0xfc, 0x57, 0x98, 0x6e, 0xd4, 0xec, 0x75, 0x84, 0x43, 0xdb,
	0x71, 0x42, 0x0f, 0x87, 0x0d, 0xdb, 0xf7, 0xd7, 0x3c, 0x5c, 0xa6, 0xe2, 0x1e, 0x36, 0xbe, 0x50,
	0xd0, 0x2b, 0x60, 0x08, 0xa8, 0xeb, 0x05, 0x21, 0xba, 0x5f, 0xf5, 0x03, 0xe3, 0x73, 0xb5, 0x7c,
	0x1d, 0x2e, 0x48, 0x4d, 0x35, 0x8c, 0xec, 0xf2, 0x7a, 0x58, 0xf3, 0x2a, 0x55, 0x17, 0x95, 0x8d,
	0xcf, 0x14, 0xe8, 0x19, 0x28, 0x09, 0x90, 0x17, 0x2c, 0x23, 0x1c, 0x36, 0x6a, 0xb6, 0x83, 0x38,
	0xd0, 0xf8, 0x9b, 0x82, 0x5d, 0x05, 0x53, 0xc0, 0x02, 0xef, 0x1e, 0x72, 0x85, 0x2d, 0x7f, 0x55,
	0x80, 0xe7, 0x60, 0x46, 0x00, 0x7c, 0x54, 0x43, 0x4e, 0x10, 0xfa, 0x08, 0xaf, 0x0a, 0xcb, 0x96,
	0xbc, 0x15, 0xb7, 0x6c, 0x7c, 0xda, 0x0f, 0x2c, 0x2d, 0xe3, 0x42, 0xa8, 0x2c, 0xc4, 0x8c, 0xbf,
	0xf4, 0xb3, 0x50, 0x82, 0x1f, 0xd8, 0x6e, 0x18, 0x78, 0x65, 0x7b, 0xdd, 0x78, 0xfc, 0xa7, 0x4f,
	0x25, 0xec, 0x0e, 0x58, 0x02, 0x86, 0x91, 0x6b, 0xd7, 0x51, 0xe8, 0xa2, 0xb5, 0xd0, 0xb1, 0xdd,
	0x20, 0xf4, 0x29, 0x15, 0x78, 0xa1, 0x57, 0x2b, 0x1b, 0xbf, 0x52, 0x02, 0x2a, 0xd0, 0xbd, 0x02,
	0xa8, 0xde, 0x08, 0xd6, 0x8d, 0x5f, 0x2a, 0xe8, 0x6d, 0xb8, 0x9a, 0x87, 0x62, 0x54, 0xf7, 0x56,
	0x11, 0xd5, 0x18, 0x2e, 0xd9, 0xd5, 0x1a, 0x2a, 0x1b, 0xbf, 0x50, 0xe8, 0x39, 0xb8, 0x9c, 0x47,
	0x07, 0x9e, 0x17, 0xd6, 0x3c, 0xb7, 0x12, 0x52, 0xca, 0xf8, 0xb9, 0x42, 0x3e, 0x0f, 0xb3, 0x3d,
	0x26, 0xd0, 0x3c, 0xba, 0xde, 0x4a, 0x65, 0x39, 0x2c, 0x57, 0xed, 0xba, 0xe7, 0x96, 0x8d, 0x9f,
	0x29, 0xf8, 0x0d, 0xb8, 0xe8, 0x2c, 0xdb, 0xb8, 0x82, 0x42, 0x0f, 0x97, 0x11, 0x66, 0x1f, 0xcc,
	0x85, 0xb1, 0x1f, 0xff, 0xfe, 0xcf, 0x12, 0x75, 0x13, 0x2e, 0x1d, 0x46, 0x55, 0xdd, 0x55, 0xbb,
	0x56, 0x2d, 0x1b, 0xdf, 0x53, 0xb8, 0xe7, 0x60, 0x26, 0x87, 0xf3, 0xab, 0x15, 0xd7, 0x0e, 0x56,
	0x30, 0xca, 0xc0, 0xdf, 0x55, 0x60, 0x0b, 0xce, 0xe7, 0xc1, 0xae, 0xd8, 0xf8, 0x3b, 0x0a, 0x33,
	0x07, 0x97, 0x7b, 0x31, 0x34, 0x63, 0xe5, 0xf5, 0x70, 0xc5, 0x47, 0x65, 0xe3, 0xdb, 0x0a, 0xf9,
	0x2c, 0x4c, 0xe5, 0x90, 0xab, 0x08, 0x57, 0x97, 0xd6, 0x65, 0x28, 0xbf, 0xa5, 0x80, 0xd7, 0xe1,
	0xc2, 0x12, 0xae, 0x22, 0xb7, 0x1c, 0xd6, 0x91, 0xef, 0xdb, 0x15, 0x14, 0xba, 0x2b, 0xf5, 0xb0,
	0x6e, 0xdf, 0x37, 0x3e, 0xfa, 0xc9, 0x1f, 0xb5, 0x02, 0x11, 0x20, 0xd7, 0x0b, 0x57, 0x5c, 0x5a,
	0x23, 0x12, 0x6e, 0x7c, 0xa8, 0x60, 0xcf, 0xc3, 0xac, 0x80, 0x05, 0xcb, 0x28, 0xec, 0x29, 0x29,
	0xbe, 0x62, 0x7c, 0xa0, 0xe0, 0x73, 0x70, 0xf9, 0x30, 0x1c, 0xa3, 0xd7, 0x57, 0x90, 0x1f, 0xa0,
	0xb2, 0xf1, 0x7e, 0x3f, 0xa4, 0x28, 0x0b, 0x41, 0x09, 0x77, 0xde, 0x53, 0xc8, 0x5b, 0x70, 0x45,
	0xac, 0x55, 0xaa, 0xab, 0x28, 0x6c, 0x78, 0x55, 0x37, 0xf0, 0xc3, 0x25, 0xa6, 0xd5, 0x0d, 0x6a,
	0xeb, 0xc6, 0xbb, 0x0a, 0x7b, 0x07, 0x2c, 0xb9, 0xbf, 0xe7, 0x85, 0x75, 0xdb, 0x95, 0x46, 0xea,
	0xb2, 0xc6, 0x37, 0xfa, 0xf9, 0xa7, 0x2b, 0xaf, 0xdb, 0xf7, 0x59, 0xcc, 0x6a, 0xd5, 0x7a, 0x35,
	0x30, 0xbe, 0xae, 0xe0, 0xd7, 0x60, 0x52, 0x45, 0x8d, 0xba, 0x28, 0x42, 0xf0, 0x35, 0x05, 0xb9,
	0x01, 0x17, 0x7b, 0xa2, 0x2f, 0x2b, 0xd9, 0xf8, 0x7f, 0x85, 0xba, 0x0a, 0xa6, 0x40, 0x39, 0xcb,
	0x76, 0x20, 0xbd, 0xfe, 0x3f, 0x05, 0xb8, 0x0c, 0x13, 0xfe, 0xb2, 0xd7, 0xd0, 0x5a, 0xc1, 0x3b,
	0x3f, 0xfc, 0x83, 0x56, 0x58, 0x6c, 0xb1, 0xb1, 0x82, 0x9d, 0x65, 0xdb, 0x47, 0x59, 0xd8, 0xbe,
	0xfc, 0x41, 0x86, 0x99, 0x85, 0xa7, 0x19, 0xa6, 0x1a, 0xa0, 0xba, 0xa6, 0xe5, 0x0b, 0x85, 0xb8,
	0x09, 0x97, 0x18, 0x82, 0x79, 0x89, 0xca, 0x61, 0xb0, 0xde, 0x50, 0x65, 0xfc, 0xb9, 0xc2, 0x5d,
	0x83, 0xc9, 0xbc, 0x26, 0x7e, 0xd8, 0x8c, 0xcf, 0x14, 0xe4, 0x32, 0x4c, 0x04, 0xb6, 0x7f, 0x4f,
	0xdb, 0xe7, 0xa3, 0x4f, 0xb2, 0x13, 0x38, 0x03, 0x4f, 0x65, 0x8b, 0x8e, 0x57, 0x6f, 0xd4, 0x50,
	0x80, 0x8c, 0x0f, 0xd5, 0xfa, 0x34, 0x9c, 0xcb, 0xd6, 0x31, 0x5a, 0xb3, 0x71, 0xd9, 0xf8, 0x40,
	0xad, 0x5a, 0x70, 0x9e, 0xad, 0xca, 0xa2, 0xe3, 0x08, 0x5a, 0x4c, 0x87, 0x31, 0x35, 0xb4, 0x8a,
	0x6a, 0xba, 0x89, 0xef, 0x29, 0xcc, 0x75, 0xb8, 0xc0, 0x30, 0x0d, 0x8c, 0x56, 0xf3, 0xa6, 0xbc,
	0xfb, 0x89, 0xde, 0xb3, 0xd6, 0x3c, 0x5c, 0x2b, 0xb3, 0xa4, 0xf8, 0x2c, 0x89, 0x7e, 0x25, 0x74,
	0x3c, 0xaf, 0x56, 0x75, 0x2b, 0x61, 0xd9, 0x5b, 0x73, 0x8d, 0xdf, 0x3d, 0xce, 0xd0, 0xf3, 0x70,
	0xad, 0x0f, 0x7a, 0x71, 0x3d, 0x40, 0xbe, 0x4a, 0xfa, 0x6f, 0x1f, 0xeb, 0x9d, 0x4b, 0xe1, 0x79,
	0x97, 0xa5, 0x42, 0x6b, 0xd5, 0x60, 0x99, 0xd6, 0xd3, 0x12, 0x46, 0xc8, 0xf8, 0xcd, 0x63, 0xbd,
	0x25, 0x2a, 0x78, 0x63, 0xa5, 0x56, 0xcb, 0x1b, 0xf2, 0x6b, 0x85, 0x7c, 0x0e, 0x66, 0xfa, 0x19,
	0x82, 0xc2, 0x25, 0x0f, 0x2f, 0x56, 0xcb, 0xc8, 0x35, 0x1e, 0x67, 0xe0, 0x37, 0x4f, 0xb1, 0xbf,
	0xfb, 0x79, 0xe9, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xa2, 0x4e, 0x32, 0x0f, 0x24, 0x00,
	0x00,
}
