// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db_center.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db_center.proto

It has these top-level messages:
	HeroDesireParam
	SmallRankRecord
	CampFightRecord
	IdNum
	StageScoreRankRankRecords
	ServerRewardRewardInfo
	ServerRewardRewardInfoList
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeroDesireParam struct {
	TargetValue      *int32 `protobuf:"varint,1,opt,name=TargetValue" json:"TargetValue,omitempty"`
	Value1           *int32 `protobuf:"varint,2,opt,name=Value1" json:"Value1,omitempty"`
	Value2           *int32 `protobuf:"varint,3,opt,name=Value2" json:"Value2,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeroDesireParam) Reset()                    { *m = HeroDesireParam{} }
func (m *HeroDesireParam) String() string            { return proto.CompactTextString(m) }
func (*HeroDesireParam) ProtoMessage()               {}
func (*HeroDesireParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HeroDesireParam) GetTargetValue() int32 {
	if m != nil && m.TargetValue != nil {
		return *m.TargetValue
	}
	return 0
}

func (m *HeroDesireParam) GetValue1() int32 {
	if m != nil && m.Value1 != nil {
		return *m.Value1
	}
	return 0
}

func (m *HeroDesireParam) GetValue2() int32 {
	if m != nil && m.Value2 != nil {
		return *m.Value2
	}
	return 0
}

type SmallRankRecord struct {
	Rank             *int32  `protobuf:"varint,1,opt,name=Rank" json:"Rank,omitempty"`
	Id               *int32  `protobuf:"varint,2,opt,name=Id" json:"Id,omitempty"`
	Val              *int32  `protobuf:"varint,3,opt,name=Val" json:"Val,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
	Lvl              *int32  `protobuf:"varint,5,opt,name=Lvl" json:"Lvl,omitempty"`
	Icon             *int32  `protobuf:"varint,6,opt,name=Icon" json:"Icon,omitempty"`
	CustomIcon       *string `protobuf:"bytes,7,opt,name=CustomIcon" json:"CustomIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SmallRankRecord) Reset()                    { *m = SmallRankRecord{} }
func (m *SmallRankRecord) String() string            { return proto.CompactTextString(m) }
func (*SmallRankRecord) ProtoMessage()               {}
func (*SmallRankRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SmallRankRecord) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *SmallRankRecord) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SmallRankRecord) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

func (m *SmallRankRecord) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SmallRankRecord) GetLvl() int32 {
	if m != nil && m.Lvl != nil {
		return *m.Lvl
	}
	return 0
}

func (m *SmallRankRecord) GetIcon() int32 {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return 0
}

func (m *SmallRankRecord) GetCustomIcon() string {
	if m != nil && m.CustomIcon != nil {
		return *m.CustomIcon
	}
	return ""
}

type CampFightRecord struct {
	FightIdx         *int32 `protobuf:"varint,1,opt,name=FightIdx" json:"FightIdx,omitempty"`
	XScore           *int32 `protobuf:"varint,2,opt,name=XScore" json:"XScore,omitempty"`
	TScore           *int32 `protobuf:"varint,3,opt,name=TScore" json:"TScore,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CampFightRecord) Reset()                    { *m = CampFightRecord{} }
func (m *CampFightRecord) String() string            { return proto.CompactTextString(m) }
func (*CampFightRecord) ProtoMessage()               {}
func (*CampFightRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CampFightRecord) GetFightIdx() int32 {
	if m != nil && m.FightIdx != nil {
		return *m.FightIdx
	}
	return 0
}

func (m *CampFightRecord) GetXScore() int32 {
	if m != nil && m.XScore != nil {
		return *m.XScore
	}
	return 0
}

func (m *CampFightRecord) GetTScore() int32 {
	if m != nil && m.TScore != nil {
		return *m.TScore
	}
	return 0
}

type IdNum struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Num              *int32 `protobuf:"varint,2,opt,name=Num" json:"Num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IdNum) Reset()                    { *m = IdNum{} }
func (m *IdNum) String() string            { return proto.CompactTextString(m) }
func (*IdNum) ProtoMessage()               {}
func (*IdNum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IdNum) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *IdNum) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type StageScoreRankRankRecords struct {
	Records          []*SmallRankRecord `protobuf:"bytes,1,rep,name=Records" json:"Records,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *StageScoreRankRankRecords) Reset()                    { *m = StageScoreRankRankRecords{} }
func (m *StageScoreRankRankRecords) String() string            { return proto.CompactTextString(m) }
func (*StageScoreRankRankRecords) ProtoMessage()               {}
func (*StageScoreRankRankRecords) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StageScoreRankRankRecords) GetRecords() []*SmallRankRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type ServerRewardRewardInfo struct {
	RewardId         *int32   `protobuf:"varint,1,opt,name=RewardId" json:"RewardId,omitempty"`
	Items            []*IdNum `protobuf:"bytes,2,rep,name=Items" json:"Items,omitempty"`
	Channel          *string  `protobuf:"bytes,3,opt,name=Channel" json:"Channel,omitempty"`
	EndUnix          *int32   `protobuf:"varint,4,opt,name=EndUnix" json:"EndUnix,omitempty"`
	Content          *string  `protobuf:"bytes,5,opt,name=Content" json:"Content,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ServerRewardRewardInfo) Reset()                    { *m = ServerRewardRewardInfo{} }
func (m *ServerRewardRewardInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerRewardRewardInfo) ProtoMessage()               {}
func (*ServerRewardRewardInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServerRewardRewardInfo) GetRewardId() int32 {
	if m != nil && m.RewardId != nil {
		return *m.RewardId
	}
	return 0
}

func (m *ServerRewardRewardInfo) GetItems() []*IdNum {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ServerRewardRewardInfo) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *ServerRewardRewardInfo) GetEndUnix() int32 {
	if m != nil && m.EndUnix != nil {
		return *m.EndUnix
	}
	return 0
}

func (m *ServerRewardRewardInfo) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type ServerRewardRewardInfoList struct {
	List             []*ServerRewardRewardInfo `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ServerRewardRewardInfoList) Reset()                    { *m = ServerRewardRewardInfoList{} }
func (m *ServerRewardRewardInfoList) String() string            { return proto.CompactTextString(m) }
func (*ServerRewardRewardInfoList) ProtoMessage()               {}
func (*ServerRewardRewardInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServerRewardRewardInfoList) GetList() []*ServerRewardRewardInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*HeroDesireParam)(nil), "db.HeroDesireParam")
	proto.RegisterType((*SmallRankRecord)(nil), "db.SmallRankRecord")
	proto.RegisterType((*CampFightRecord)(nil), "db.CampFightRecord")
	proto.RegisterType((*IdNum)(nil), "db.IdNum")
	proto.RegisterType((*StageScoreRankRankRecords)(nil), "db.StageScoreRankRankRecords")
	proto.RegisterType((*ServerRewardRewardInfo)(nil), "db.ServerRewardRewardInfo")
	proto.RegisterType((*ServerRewardRewardInfoList)(nil), "db.ServerRewardRewardInfoList")
}

func init() { proto.RegisterFile("db_center.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0xd1, 0x8a, 0x13, 0x31,
	0x14, 0x65, 0xa6, 0x9d, 0xad, 0xbd, 0x0b, 0x56, 0x22, 0x2c, 0xb1, 0x0f, 0x5a, 0xe6, 0xa9, 0x3e,
	0x58, 0xb0, 0xbf, 0x50, 0x15, 0x47, 0x4a, 0x91, 0x74, 0x5d, 0x7c, 0x11, 0x49, 0x27, 0xd7, 0x6e,
	0x71, 0x92, 0x2c, 0x99, 0xb4, 0xee, 0xef, 0x88, 0x3f, 0x2a, 0xb9, 0xc9, 0x94, 0x61, 0xe9, 0xcb,
	0xcc, 0x39, 0x27, 0xe7, 0xde, 0xdc, 0x73, 0x03, 0x13, 0xb5, 0xfb, 0x59, 0xa3, 0xf1, 0xe8, 0x16,
	0x0f, 0xce, 0x7a, 0xcb, 0x72, 0xb5, 0x2b, 0x6b, 0x98, 0x7c, 0x46, 0x67, 0x3f, 0x60, 0x7b, 0x70,
	0xf8, 0x55, 0x3a, 0xa9, 0xd9, 0x0c, 0xae, 0x6f, 0xa5, 0xdb, 0xa3, 0xbf, 0x93, 0xcd, 0x11, 0x79,
	0x36, 0xcb, 0xe6, 0x85, 0xe8, 0x4b, 0xec, 0x06, 0xae, 0x08, 0xbc, 0xe7, 0x39, 0x1d, 0x26, 0x76,
	0xd6, 0x97, 0x7c, 0xd0, 0xd3, 0x97, 0xe5, 0xdf, 0x0c, 0x26, 0x5b, 0x2d, 0x9b, 0x46, 0x48, 0xf3,
	0x5b, 0x60, 0x6d, 0x9d, 0x62, 0x0c, 0x86, 0x81, 0xa5, 0xf6, 0x84, 0xd9, 0x73, 0xc8, 0x2b, 0x95,
	0x7a, 0xe6, 0x95, 0x62, 0x2f, 0x60, 0x70, 0x27, 0x9b, 0xd4, 0x2c, 0xc0, 0x50, 0xb5, 0x91, 0x1a,
	0xf9, 0x70, 0x96, 0xcd, 0xc7, 0x82, 0x70, 0x70, 0xad, 0x4f, 0x0d, 0x2f, 0xa2, 0x6b, 0x7d, 0x22,
	0x57, 0x55, 0x5b, 0xc3, 0xaf, 0x62, 0xef, 0x80, 0xd9, 0x6b, 0x80, 0xd5, 0xb1, 0xf5, 0x56, 0xd3,
	0xc9, 0x88, 0xea, 0x7b, 0x4a, 0xf9, 0x03, 0x26, 0x2b, 0xa9, 0x1f, 0x3e, 0x1d, 0xf6, 0xf7, 0x3e,
	0x8d, 0x38, 0x85, 0x67, 0x44, 0x2b, 0xf5, 0x98, 0xc6, 0x3c, 0xf3, 0x10, 0xf5, 0xfb, 0xb6, 0xb6,
	0x0e, 0xbb, 0x15, 0x44, 0x16, 0xf4, 0xdb, 0xa8, 0xa7, 0x15, 0x44, 0x56, 0xbe, 0x85, 0xa2, 0x52,
	0x9b, 0xa3, 0x4e, 0x19, 0xb3, 0x7e, 0xc6, 0xcd, 0x51, 0xa7, 0x2e, 0x01, 0x96, 0x5f, 0xe0, 0xd5,
	0xd6, 0xcb, 0x3d, 0x52, 0x21, 0x6d, 0xec, 0xbc, 0xb5, 0x96, 0xbd, 0x83, 0x51, 0x82, 0x3c, 0x9b,
	0x0d, 0xe6, 0xd7, 0xcb, 0x97, 0x0b, 0xb5, 0x5b, 0x3c, 0x59, 0xae, 0xe8, 0x3c, 0xe5, 0xbf, 0x0c,
	0x6e, 0xb6, 0xe8, 0x4e, 0xe8, 0x04, 0xfe, 0x91, 0x4e, 0xc5, 0x6f, 0x65, 0x7e, 0xd9, 0x90, 0x2e,
	0xb1, 0x6e, 0x9c, 0x33, 0x67, 0x6f, 0xa0, 0xa8, 0x3c, 0xea, 0x96, 0xe7, 0x74, 0xc7, 0x38, 0xdc,
	0x41, 0xe3, 0x8b, 0xa8, 0x33, 0x0e, 0xa3, 0xd5, 0xbd, 0x34, 0x06, 0xe3, 0xeb, 0x8c, 0x45, 0x47,
	0xc3, 0xc9, 0x47, 0xa3, 0xbe, 0x99, 0xc3, 0x23, 0x3d, 0x52, 0x21, 0x3a, 0x4a, 0x35, 0xd6, 0x78,
	0x34, 0x9e, 0xde, 0x2a, 0xd4, 0x44, 0x5a, 0xae, 0x61, 0x7a, 0x79, 0xc8, 0xf5, 0xa1, 0xf5, 0x6c,
	0x01, 0xc3, 0xf0, 0x4f, 0x79, 0xa7, 0x94, 0xf7, 0xa2, 0x5b, 0x90, 0xef, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x3d, 0xea, 0x7f, 0xa7, 0xe8, 0x02, 0x00, 0x00,
}
