// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db_hallsvr.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db_hallsvr.proto

It has these top-level messages:
	SmallRankRecord
	LimitShopItem
	PlayerInfo
	PlayerGlobal
	PlayerItem
	PlayerItemList
	PlayerRole
	PlayerRoleList
	PlayerRoleHandbook
	PlayerBattleTeam
	PlayerCampaignCommon
	PlayerCampaign
	PlayerCampaignList
	PlayerCampaignStaticIncome
	PlayerCampaignStaticIncomeList
	PlayerCampaignRandomIncome
	PlayerCampaignRandomIncomeList
	PlayerNotifyState
	PlayerNotifyStateList
	PlayerMailCommon
	PlayerMail
	PlayerMailList
	PlayerBattleSave
	PlayerBattleSaveList
	PlayerTalent
	PlayerTalentList
	PlayerTowerCommon
	PlayerTower
	PlayerTowerList
	PlayerDraw
	PlayerDrawList
	PlayerGoldHand
	PlayerShop
	PlayerShopList
	PlayerShopItem
	PlayerShopItemList
	PlayerArena
	PlayerEquip
	PlayerActiveStageCommon
	PlayerActiveStage
	PlayerActiveStageList
	PlayerFriendCommon
	PlayerFriend
	PlayerFriendList
	PlayerFriendRecommend
	PlayerFriendRecommendList
	PlayerFriendAsk
	PlayerFriendAskList
	PlayerFriendBoss
	PlayerFriendBossList
	PlayerTaskCommon
	PlayerTask
	PlayerTaskList
	PlayerFinishedTask
	PlayerFinishedTaskList
	PlayerDailyTaskAllDaily
	PlayerDailyTaskAllDailyList
	PlayerExploreCommon
	PlayerExplore
	PlayerExploreList
	PlayerExploreStory
	PlayerExploreStoryList
	PlayerSevenActivity
	PlayerSevenActivityList
	PlayerGuides
	PlayerGuidesList
	PlayerFriendChatUnreadId
	PlayerFriendChatUnreadIdList
	PlayerFriendChatUnreadMessage
	PlayerFriendChatUnreadMessageList
	PlayerHeadItem
	PlayerHeadItemList
	PlayerSuitAward
	PlayerSuitAwardList
	PlayerWorldChat
	PlayerAnouncement
	PlayerFirstDrawCard
	PlayerFirstDrawCardList
	BattleSaveData
	TowerFightSaveData
	TowerRankingListPlayers
	ArenaSeasonData
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SmallRankRecord struct {
	Rank             *int32  `protobuf:"varint,1,opt,name=Rank" json:"Rank,omitempty"`
	Id               *int32  `protobuf:"varint,2,opt,name=Id" json:"Id,omitempty"`
	Val              *int32  `protobuf:"varint,3,opt,name=Val" json:"Val,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SmallRankRecord) Reset()                    { *m = SmallRankRecord{} }
func (m *SmallRankRecord) String() string            { return proto.CompactTextString(m) }
func (*SmallRankRecord) ProtoMessage()               {}
func (*SmallRankRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SmallRankRecord) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *SmallRankRecord) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SmallRankRecord) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

func (m *SmallRankRecord) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type LimitShopItem struct {
	CommodityId      *int32 `protobuf:"varint,1,opt,name=CommodityId" json:"CommodityId,omitempty"`
	LeftNum          *int32 `protobuf:"varint,2,opt,name=LeftNum" json:"LeftNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LimitShopItem) Reset()                    { *m = LimitShopItem{} }
func (m *LimitShopItem) String() string            { return proto.CompactTextString(m) }
func (*LimitShopItem) ProtoMessage()               {}
func (*LimitShopItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LimitShopItem) GetCommodityId() int32 {
	if m != nil && m.CommodityId != nil {
		return *m.CommodityId
	}
	return 0
}

func (m *LimitShopItem) GetLeftNum() int32 {
	if m != nil && m.LeftNum != nil {
		return *m.LeftNum
	}
	return 0
}

type PlayerInfo struct {
	Lvl                 *int32  `protobuf:"varint,1,opt,name=Lvl" json:"Lvl,omitempty"`
	Exp                 *int32  `protobuf:"varint,2,opt,name=Exp" json:"Exp,omitempty"`
	CreateUnix          *int32  `protobuf:"varint,3,opt,name=CreateUnix" json:"CreateUnix,omitempty"`
	Gold                *int32  `protobuf:"varint,4,opt,name=Gold" json:"Gold,omitempty"`
	Diamond             *int32  `protobuf:"varint,5,opt,name=Diamond" json:"Diamond,omitempty"`
	LastDialyTaskUpUinx *int32  `protobuf:"varint,6,opt,name=LastDialyTaskUpUinx" json:"LastDialyTaskUpUinx,omitempty"`
	Icon                *string `protobuf:"bytes,7,opt,name=Icon" json:"Icon,omitempty"`
	LastLogout          *int32  `protobuf:"varint,9,opt,name=LastLogout" json:"LastLogout,omitempty"`
	LastLogin           *int32  `protobuf:"varint,10,opt,name=LastLogin" json:"LastLogin,omitempty"`
	VipLvl              *int32  `protobuf:"varint,16,opt,name=VipLvl" json:"VipLvl,omitempty"`
	Head                *int32  `protobuf:"varint,17,opt,name=Head" json:"Head,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerInfo) GetLvl() int32 {
	if m != nil && m.Lvl != nil {
		return *m.Lvl
	}
	return 0
}

func (m *PlayerInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *PlayerInfo) GetCreateUnix() int32 {
	if m != nil && m.CreateUnix != nil {
		return *m.CreateUnix
	}
	return 0
}

func (m *PlayerInfo) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *PlayerInfo) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *PlayerInfo) GetLastDialyTaskUpUinx() int32 {
	if m != nil && m.LastDialyTaskUpUinx != nil {
		return *m.LastDialyTaskUpUinx
	}
	return 0
}

func (m *PlayerInfo) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *PlayerInfo) GetLastLogout() int32 {
	if m != nil && m.LastLogout != nil {
		return *m.LastLogout
	}
	return 0
}

func (m *PlayerInfo) GetLastLogin() int32 {
	if m != nil && m.LastLogin != nil {
		return *m.LastLogin
	}
	return 0
}

func (m *PlayerInfo) GetVipLvl() int32 {
	if m != nil && m.VipLvl != nil {
		return *m.VipLvl
	}
	return 0
}

func (m *PlayerInfo) GetHead() int32 {
	if m != nil && m.Head != nil {
		return *m.Head
	}
	return 0
}

type PlayerGlobal struct {
	CurrentRoleId    *int32 `protobuf:"varint,1,opt,name=CurrentRoleId" json:"CurrentRoleId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerGlobal) Reset()                    { *m = PlayerGlobal{} }
func (m *PlayerGlobal) String() string            { return proto.CompactTextString(m) }
func (*PlayerGlobal) ProtoMessage()               {}
func (*PlayerGlobal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PlayerGlobal) GetCurrentRoleId() int32 {
	if m != nil && m.CurrentRoleId != nil {
		return *m.CurrentRoleId
	}
	return 0
}

type PlayerItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Count            *int32 `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerItem) Reset()                    { *m = PlayerItem{} }
func (m *PlayerItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerItem) ProtoMessage()               {}
func (*PlayerItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerItem) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type PlayerItemList struct {
	List             []*PlayerItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerItemList) Reset()                    { *m = PlayerItemList{} }
func (m *PlayerItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerItemList) ProtoMessage()               {}
func (*PlayerItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerItemList) GetList() []*PlayerItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerRole struct {
	Id               *int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	TableId          *int32  `protobuf:"varint,2,opt,name=TableId" json:"TableId,omitempty"`
	Rank             *int32  `protobuf:"varint,3,opt,name=Rank" json:"Rank,omitempty"`
	Level            *int32  `protobuf:"varint,4,opt,name=Level" json:"Level,omitempty"`
	Attr             []int32 `protobuf:"varint,5,rep,name=Attr" json:"Attr,omitempty"`
	Equip            []int32 `protobuf:"varint,6,rep,name=Equip" json:"Equip,omitempty"`
	IsLock           *int32  `protobuf:"varint,7,opt,name=IsLock" json:"IsLock,omitempty"`
	State            *int32  `protobuf:"varint,8,opt,name=State" json:"State,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerRole) Reset()                    { *m = PlayerRole{} }
func (m *PlayerRole) String() string            { return proto.CompactTextString(m) }
func (*PlayerRole) ProtoMessage()               {}
func (*PlayerRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlayerRole) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerRole) GetTableId() int32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *PlayerRole) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *PlayerRole) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerRole) GetAttr() []int32 {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *PlayerRole) GetEquip() []int32 {
	if m != nil {
		return m.Equip
	}
	return nil
}

func (m *PlayerRole) GetIsLock() int32 {
	if m != nil && m.IsLock != nil {
		return *m.IsLock
	}
	return 0
}

func (m *PlayerRole) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type PlayerRoleList struct {
	List             []*PlayerRole `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerRoleList) Reset()                    { *m = PlayerRoleList{} }
func (m *PlayerRoleList) String() string            { return proto.CompactTextString(m) }
func (*PlayerRoleList) ProtoMessage()               {}
func (*PlayerRoleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PlayerRoleList) GetList() []*PlayerRole {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerRoleHandbook struct {
	Role             []int32 `protobuf:"varint,1,rep,name=Role" json:"Role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerRoleHandbook) Reset()                    { *m = PlayerRoleHandbook{} }
func (m *PlayerRoleHandbook) String() string            { return proto.CompactTextString(m) }
func (*PlayerRoleHandbook) ProtoMessage()               {}
func (*PlayerRoleHandbook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PlayerRoleHandbook) GetRole() []int32 {
	if m != nil {
		return m.Role
	}
	return nil
}

type PlayerBattleTeam struct {
	AttackMembers    []int32 `protobuf:"varint,1,rep,name=AttackMembers" json:"AttackMembers,omitempty"`
	DefenseMembers   []int32 `protobuf:"varint,2,rep,name=DefenseMembers" json:"DefenseMembers,omitempty"`
	CampaignMembers  []int32 `protobuf:"varint,3,rep,name=CampaignMembers" json:"CampaignMembers,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerBattleTeam) Reset()                    { *m = PlayerBattleTeam{} }
func (m *PlayerBattleTeam) String() string            { return proto.CompactTextString(m) }
func (*PlayerBattleTeam) ProtoMessage()               {}
func (*PlayerBattleTeam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PlayerBattleTeam) GetAttackMembers() []int32 {
	if m != nil {
		return m.AttackMembers
	}
	return nil
}

func (m *PlayerBattleTeam) GetDefenseMembers() []int32 {
	if m != nil {
		return m.DefenseMembers
	}
	return nil
}

func (m *PlayerBattleTeam) GetCampaignMembers() []int32 {
	if m != nil {
		return m.CampaignMembers
	}
	return nil
}

type PlayerCampaignCommon struct {
	CurrentCampaignId              *int32 `protobuf:"varint,1,opt,name=CurrentCampaignId" json:"CurrentCampaignId,omitempty"`
	HangupLastDropStaticIncomeTime *int32 `protobuf:"varint,2,opt,name=HangupLastDropStaticIncomeTime" json:"HangupLastDropStaticIncomeTime,omitempty"`
	HangupLastDropRandomIncomeTime *int32 `protobuf:"varint,3,opt,name=HangupLastDropRandomIncomeTime" json:"HangupLastDropRandomIncomeTime,omitempty"`
	HangupCampaignId               *int32 `protobuf:"varint,4,opt,name=HangupCampaignId" json:"HangupCampaignId,omitempty"`
	RankSerialId                   *int32 `protobuf:"varint,5,opt,name=RankSerialId" json:"RankSerialId,omitempty"`
	XXX_unrecognized               []byte `json:"-"`
}

func (m *PlayerCampaignCommon) Reset()                    { *m = PlayerCampaignCommon{} }
func (m *PlayerCampaignCommon) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignCommon) ProtoMessage()               {}
func (*PlayerCampaignCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PlayerCampaignCommon) GetCurrentCampaignId() int32 {
	if m != nil && m.CurrentCampaignId != nil {
		return *m.CurrentCampaignId
	}
	return 0
}

func (m *PlayerCampaignCommon) GetHangupLastDropStaticIncomeTime() int32 {
	if m != nil && m.HangupLastDropStaticIncomeTime != nil {
		return *m.HangupLastDropStaticIncomeTime
	}
	return 0
}

func (m *PlayerCampaignCommon) GetHangupLastDropRandomIncomeTime() int32 {
	if m != nil && m.HangupLastDropRandomIncomeTime != nil {
		return *m.HangupLastDropRandomIncomeTime
	}
	return 0
}

func (m *PlayerCampaignCommon) GetHangupCampaignId() int32 {
	if m != nil && m.HangupCampaignId != nil {
		return *m.HangupCampaignId
	}
	return 0
}

func (m *PlayerCampaignCommon) GetRankSerialId() int32 {
	if m != nil && m.RankSerialId != nil {
		return *m.RankSerialId
	}
	return 0
}

type PlayerCampaign struct {
	CampaignId       *int32 `protobuf:"varint,1,opt,name=CampaignId" json:"CampaignId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerCampaign) Reset()                    { *m = PlayerCampaign{} }
func (m *PlayerCampaign) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaign) ProtoMessage()               {}
func (*PlayerCampaign) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PlayerCampaign) GetCampaignId() int32 {
	if m != nil && m.CampaignId != nil {
		return *m.CampaignId
	}
	return 0
}

type PlayerCampaignList struct {
	List             []*PlayerCampaign `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PlayerCampaignList) Reset()                    { *m = PlayerCampaignList{} }
func (m *PlayerCampaignList) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignList) ProtoMessage()               {}
func (*PlayerCampaignList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PlayerCampaignList) GetList() []*PlayerCampaign {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerCampaignStaticIncome struct {
	ItemId           *int32 `protobuf:"varint,1,opt,name=ItemId" json:"ItemId,omitempty"`
	ItemNum          *int32 `protobuf:"varint,2,opt,name=ItemNum" json:"ItemNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerCampaignStaticIncome) Reset()                    { *m = PlayerCampaignStaticIncome{} }
func (m *PlayerCampaignStaticIncome) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignStaticIncome) ProtoMessage()               {}
func (*PlayerCampaignStaticIncome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PlayerCampaignStaticIncome) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *PlayerCampaignStaticIncome) GetItemNum() int32 {
	if m != nil && m.ItemNum != nil {
		return *m.ItemNum
	}
	return 0
}

type PlayerCampaignStaticIncomeList struct {
	List             []*PlayerCampaignStaticIncome `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *PlayerCampaignStaticIncomeList) Reset()                    { *m = PlayerCampaignStaticIncomeList{} }
func (m *PlayerCampaignStaticIncomeList) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignStaticIncomeList) ProtoMessage()               {}
func (*PlayerCampaignStaticIncomeList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PlayerCampaignStaticIncomeList) GetList() []*PlayerCampaignStaticIncome {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerCampaignRandomIncome struct {
	ItemId           *int32 `protobuf:"varint,1,opt,name=ItemId" json:"ItemId,omitempty"`
	ItemNum          *int32 `protobuf:"varint,2,opt,name=ItemNum" json:"ItemNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerCampaignRandomIncome) Reset()                    { *m = PlayerCampaignRandomIncome{} }
func (m *PlayerCampaignRandomIncome) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignRandomIncome) ProtoMessage()               {}
func (*PlayerCampaignRandomIncome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PlayerCampaignRandomIncome) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *PlayerCampaignRandomIncome) GetItemNum() int32 {
	if m != nil && m.ItemNum != nil {
		return *m.ItemNum
	}
	return 0
}

type PlayerCampaignRandomIncomeList struct {
	List             []*PlayerCampaignRandomIncome `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *PlayerCampaignRandomIncomeList) Reset()                    { *m = PlayerCampaignRandomIncomeList{} }
func (m *PlayerCampaignRandomIncomeList) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignRandomIncomeList) ProtoMessage()               {}
func (*PlayerCampaignRandomIncomeList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PlayerCampaignRandomIncomeList) GetList() []*PlayerCampaignRandomIncome {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerNotifyState struct {
	ModuleType       *int32 `protobuf:"varint,1,opt,name=ModuleType" json:"ModuleType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerNotifyState) Reset()                    { *m = PlayerNotifyState{} }
func (m *PlayerNotifyState) String() string            { return proto.CompactTextString(m) }
func (*PlayerNotifyState) ProtoMessage()               {}
func (*PlayerNotifyState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PlayerNotifyState) GetModuleType() int32 {
	if m != nil && m.ModuleType != nil {
		return *m.ModuleType
	}
	return 0
}

type PlayerNotifyStateList struct {
	List             []*PlayerNotifyState `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *PlayerNotifyStateList) Reset()                    { *m = PlayerNotifyStateList{} }
func (m *PlayerNotifyStateList) String() string            { return proto.CompactTextString(m) }
func (*PlayerNotifyStateList) ProtoMessage()               {}
func (*PlayerNotifyStateList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PlayerNotifyStateList) GetList() []*PlayerNotifyState {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerMailCommon struct {
	CurrId                 *int32 `protobuf:"varint,1,opt,name=CurrId" json:"CurrId,omitempty"`
	LastSendPlayerMailTime *int32 `protobuf:"varint,2,opt,name=LastSendPlayerMailTime" json:"LastSendPlayerMailTime,omitempty"`
	XXX_unrecognized       []byte `json:"-"`
}

func (m *PlayerMailCommon) Reset()                    { *m = PlayerMailCommon{} }
func (m *PlayerMailCommon) String() string            { return proto.CompactTextString(m) }
func (*PlayerMailCommon) ProtoMessage()               {}
func (*PlayerMailCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PlayerMailCommon) GetCurrId() int32 {
	if m != nil && m.CurrId != nil {
		return *m.CurrId
	}
	return 0
}

func (m *PlayerMailCommon) GetLastSendPlayerMailTime() int32 {
	if m != nil && m.LastSendPlayerMailTime != nil {
		return *m.LastSendPlayerMailTime
	}
	return 0
}

type PlayerMail struct {
	Id               *int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Type             *int32  `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	Title            *string `protobuf:"bytes,3,opt,name=Title" json:"Title,omitempty"`
	Content          *string `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
	SendUnix         *int32  `protobuf:"varint,5,opt,name=SendUnix" json:"SendUnix,omitempty"`
	AttachItemIds    []int32 `protobuf:"varint,6,rep,name=AttachItemIds" json:"AttachItemIds,omitempty"`
	AttachItemNums   []int32 `protobuf:"varint,7,rep,name=AttachItemNums" json:"AttachItemNums,omitempty"`
	IsRead           *int32  `protobuf:"varint,8,opt,name=IsRead" json:"IsRead,omitempty"`
	IsGetAttached    *int32  `protobuf:"varint,11,opt,name=IsGetAttached" json:"IsGetAttached,omitempty"`
	SenderId         *int32  `protobuf:"varint,12,opt,name=SenderId" json:"SenderId,omitempty"`
	SenderName       *string `protobuf:"bytes,13,opt,name=SenderName" json:"SenderName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerMail) Reset()                    { *m = PlayerMail{} }
func (m *PlayerMail) String() string            { return proto.CompactTextString(m) }
func (*PlayerMail) ProtoMessage()               {}
func (*PlayerMail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *PlayerMail) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerMail) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *PlayerMail) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *PlayerMail) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *PlayerMail) GetSendUnix() int32 {
	if m != nil && m.SendUnix != nil {
		return *m.SendUnix
	}
	return 0
}

func (m *PlayerMail) GetAttachItemIds() []int32 {
	if m != nil {
		return m.AttachItemIds
	}
	return nil
}

func (m *PlayerMail) GetAttachItemNums() []int32 {
	if m != nil {
		return m.AttachItemNums
	}
	return nil
}

func (m *PlayerMail) GetIsRead() int32 {
	if m != nil && m.IsRead != nil {
		return *m.IsRead
	}
	return 0
}

func (m *PlayerMail) GetIsGetAttached() int32 {
	if m != nil && m.IsGetAttached != nil {
		return *m.IsGetAttached
	}
	return 0
}

func (m *PlayerMail) GetSenderId() int32 {
	if m != nil && m.SenderId != nil {
		return *m.SenderId
	}
	return 0
}

func (m *PlayerMail) GetSenderName() string {
	if m != nil && m.SenderName != nil {
		return *m.SenderName
	}
	return ""
}

type PlayerMailList struct {
	List             []*PlayerMail `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerMailList) Reset()                    { *m = PlayerMailList{} }
func (m *PlayerMailList) String() string            { return proto.CompactTextString(m) }
func (*PlayerMailList) ProtoMessage()               {}
func (*PlayerMailList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PlayerMailList) GetList() []*PlayerMail {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerBattleSave struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Side             *int32 `protobuf:"varint,2,opt,name=Side" json:"Side,omitempty"`
	SaveTime         *int32 `protobuf:"varint,3,opt,name=SaveTime" json:"SaveTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerBattleSave) Reset()                    { *m = PlayerBattleSave{} }
func (m *PlayerBattleSave) String() string            { return proto.CompactTextString(m) }
func (*PlayerBattleSave) ProtoMessage()               {}
func (*PlayerBattleSave) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *PlayerBattleSave) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerBattleSave) GetSide() int32 {
	if m != nil && m.Side != nil {
		return *m.Side
	}
	return 0
}

func (m *PlayerBattleSave) GetSaveTime() int32 {
	if m != nil && m.SaveTime != nil {
		return *m.SaveTime
	}
	return 0
}

type PlayerBattleSaveList struct {
	List             []*PlayerBattleSave `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PlayerBattleSaveList) Reset()                    { *m = PlayerBattleSaveList{} }
func (m *PlayerBattleSaveList) String() string            { return proto.CompactTextString(m) }
func (*PlayerBattleSaveList) ProtoMessage()               {}
func (*PlayerBattleSaveList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *PlayerBattleSaveList) GetList() []*PlayerBattleSave {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerTalent struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Level            *int32 `protobuf:"varint,2,opt,name=Level" json:"Level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerTalent) Reset()                    { *m = PlayerTalent{} }
func (m *PlayerTalent) String() string            { return proto.CompactTextString(m) }
func (*PlayerTalent) ProtoMessage()               {}
func (*PlayerTalent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *PlayerTalent) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerTalent) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type PlayerTalentList struct {
	List             []*PlayerTalent `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PlayerTalentList) Reset()                    { *m = PlayerTalentList{} }
func (m *PlayerTalentList) String() string            { return proto.CompactTextString(m) }
func (*PlayerTalentList) ProtoMessage()               {}
func (*PlayerTalentList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *PlayerTalentList) GetList() []*PlayerTalent {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerTowerCommon struct {
	CurrId            *int32 `protobuf:"varint,1,opt,name=CurrId" json:"CurrId,omitempty"`
	Keys              *int32 `protobuf:"varint,2,opt,name=Keys" json:"Keys,omitempty"`
	LastGetNewKeyTime *int32 `protobuf:"varint,3,opt,name=LastGetNewKeyTime" json:"LastGetNewKeyTime,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *PlayerTowerCommon) Reset()                    { *m = PlayerTowerCommon{} }
func (m *PlayerTowerCommon) String() string            { return proto.CompactTextString(m) }
func (*PlayerTowerCommon) ProtoMessage()               {}
func (*PlayerTowerCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *PlayerTowerCommon) GetCurrId() int32 {
	if m != nil && m.CurrId != nil {
		return *m.CurrId
	}
	return 0
}

func (m *PlayerTowerCommon) GetKeys() int32 {
	if m != nil && m.Keys != nil {
		return *m.Keys
	}
	return 0
}

func (m *PlayerTowerCommon) GetLastGetNewKeyTime() int32 {
	if m != nil && m.LastGetNewKeyTime != nil {
		return *m.LastGetNewKeyTime
	}
	return 0
}

type PlayerTower struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerTower) Reset()                    { *m = PlayerTower{} }
func (m *PlayerTower) String() string            { return proto.CompactTextString(m) }
func (*PlayerTower) ProtoMessage()               {}
func (*PlayerTower) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *PlayerTower) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type PlayerTowerList struct {
	List             []*PlayerTower `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PlayerTowerList) Reset()                    { *m = PlayerTowerList{} }
func (m *PlayerTowerList) String() string            { return proto.CompactTextString(m) }
func (*PlayerTowerList) ProtoMessage()               {}
func (*PlayerTowerList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *PlayerTowerList) GetList() []*PlayerTower {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerDraw struct {
	Type             *int32 `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	LastDrawTime     *int32 `protobuf:"varint,2,opt,name=LastDrawTime" json:"LastDrawTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerDraw) Reset()                    { *m = PlayerDraw{} }
func (m *PlayerDraw) String() string            { return proto.CompactTextString(m) }
func (*PlayerDraw) ProtoMessage()               {}
func (*PlayerDraw) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *PlayerDraw) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *PlayerDraw) GetLastDrawTime() int32 {
	if m != nil && m.LastDrawTime != nil {
		return *m.LastDrawTime
	}
	return 0
}

type PlayerDrawList struct {
	List             []*PlayerDraw `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerDrawList) Reset()                    { *m = PlayerDrawList{} }
func (m *PlayerDrawList) String() string            { return proto.CompactTextString(m) }
func (*PlayerDrawList) ProtoMessage()               {}
func (*PlayerDrawList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *PlayerDrawList) GetList() []*PlayerDraw {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerGoldHand struct {
	LastRefreshTime  *int32  `protobuf:"varint,1,opt,name=LastRefreshTime" json:"LastRefreshTime,omitempty"`
	LeftNum          []int32 `protobuf:"varint,2,rep,name=LeftNum" json:"LeftNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerGoldHand) Reset()                    { *m = PlayerGoldHand{} }
func (m *PlayerGoldHand) String() string            { return proto.CompactTextString(m) }
func (*PlayerGoldHand) ProtoMessage()               {}
func (*PlayerGoldHand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *PlayerGoldHand) GetLastRefreshTime() int32 {
	if m != nil && m.LastRefreshTime != nil {
		return *m.LastRefreshTime
	}
	return 0
}

func (m *PlayerGoldHand) GetLeftNum() []int32 {
	if m != nil {
		return m.LeftNum
	}
	return nil
}

type PlayerShop struct {
	Id                  *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	LastFreeRefreshTime *int32 `protobuf:"varint,2,opt,name=LastFreeRefreshTime" json:"LastFreeRefreshTime,omitempty"`
	LastAutoRefreshTime *int32 `protobuf:"varint,3,opt,name=LastAutoRefreshTime" json:"LastAutoRefreshTime,omitempty"`
	CurrAutoId          *int32 `protobuf:"varint,4,opt,name=CurrAutoId" json:"CurrAutoId,omitempty"`
	XXX_unrecognized    []byte `json:"-"`
}

func (m *PlayerShop) Reset()                    { *m = PlayerShop{} }
func (m *PlayerShop) String() string            { return proto.CompactTextString(m) }
func (*PlayerShop) ProtoMessage()               {}
func (*PlayerShop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *PlayerShop) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerShop) GetLastFreeRefreshTime() int32 {
	if m != nil && m.LastFreeRefreshTime != nil {
		return *m.LastFreeRefreshTime
	}
	return 0
}

func (m *PlayerShop) GetLastAutoRefreshTime() int32 {
	if m != nil && m.LastAutoRefreshTime != nil {
		return *m.LastAutoRefreshTime
	}
	return 0
}

func (m *PlayerShop) GetCurrAutoId() int32 {
	if m != nil && m.CurrAutoId != nil {
		return *m.CurrAutoId
	}
	return 0
}

type PlayerShopList struct {
	List             []*PlayerShop `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerShopList) Reset()                    { *m = PlayerShopList{} }
func (m *PlayerShopList) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopList) ProtoMessage()               {}
func (*PlayerShopList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *PlayerShopList) GetList() []*PlayerShop {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerShopItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	ShopItemId       *int32 `protobuf:"varint,2,opt,name=ShopItemId" json:"ShopItemId,omitempty"`
	LeftNum          *int32 `protobuf:"varint,3,opt,name=LeftNum" json:"LeftNum,omitempty"`
	ShopId           *int32 `protobuf:"varint,4,opt,name=ShopId" json:"ShopId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerShopItem) Reset()                    { *m = PlayerShopItem{} }
func (m *PlayerShopItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopItem) ProtoMessage()               {}
func (*PlayerShopItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PlayerShopItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerShopItem) GetShopItemId() int32 {
	if m != nil && m.ShopItemId != nil {
		return *m.ShopItemId
	}
	return 0
}

func (m *PlayerShopItem) GetLeftNum() int32 {
	if m != nil && m.LeftNum != nil {
		return *m.LeftNum
	}
	return 0
}

func (m *PlayerShopItem) GetShopId() int32 {
	if m != nil && m.ShopId != nil {
		return *m.ShopId
	}
	return 0
}

type PlayerShopItemList struct {
	List             []*PlayerShopItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PlayerShopItemList) Reset()                    { *m = PlayerShopItemList{} }
func (m *PlayerShopItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopItemList) ProtoMessage()               {}
func (*PlayerShopItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *PlayerShopItemList) GetList() []*PlayerShopItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerArena struct {
	RepeatedWinNum         *int32 `protobuf:"varint,1,opt,name=RepeatedWinNum" json:"RepeatedWinNum,omitempty"`
	RepeatedLoseNum        *int32 `protobuf:"varint,2,opt,name=RepeatedLoseNum" json:"RepeatedLoseNum,omitempty"`
	Score                  *int32 `protobuf:"varint,3,opt,name=Score" json:"Score,omitempty"`
	UpdateScoreTime        *int32 `protobuf:"varint,4,opt,name=UpdateScoreTime" json:"UpdateScoreTime,omitempty"`
	MatchedPlayerId        *int32 `protobuf:"varint,5,opt,name=MatchedPlayerId" json:"MatchedPlayerId,omitempty"`
	HistoryTopRank         *int32 `protobuf:"varint,6,opt,name=HistoryTopRank" json:"HistoryTopRank,omitempty"`
	FirstGetTicket         *int32 `protobuf:"varint,7,opt,name=FirstGetTicket" json:"FirstGetTicket,omitempty"`
	LastTicketsRefreshTime *int32 `protobuf:"varint,8,opt,name=LastTicketsRefreshTime" json:"LastTicketsRefreshTime,omitempty"`
	SerialId               *int32 `protobuf:"varint,9,opt,name=SerialId" json:"SerialId,omitempty"`
	XXX_unrecognized       []byte `json:"-"`
}

func (m *PlayerArena) Reset()                    { *m = PlayerArena{} }
func (m *PlayerArena) String() string            { return proto.CompactTextString(m) }
func (*PlayerArena) ProtoMessage()               {}
func (*PlayerArena) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *PlayerArena) GetRepeatedWinNum() int32 {
	if m != nil && m.RepeatedWinNum != nil {
		return *m.RepeatedWinNum
	}
	return 0
}

func (m *PlayerArena) GetRepeatedLoseNum() int32 {
	if m != nil && m.RepeatedLoseNum != nil {
		return *m.RepeatedLoseNum
	}
	return 0
}

func (m *PlayerArena) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *PlayerArena) GetUpdateScoreTime() int32 {
	if m != nil && m.UpdateScoreTime != nil {
		return *m.UpdateScoreTime
	}
	return 0
}

func (m *PlayerArena) GetMatchedPlayerId() int32 {
	if m != nil && m.MatchedPlayerId != nil {
		return *m.MatchedPlayerId
	}
	return 0
}

func (m *PlayerArena) GetHistoryTopRank() int32 {
	if m != nil && m.HistoryTopRank != nil {
		return *m.HistoryTopRank
	}
	return 0
}

func (m *PlayerArena) GetFirstGetTicket() int32 {
	if m != nil && m.FirstGetTicket != nil {
		return *m.FirstGetTicket
	}
	return 0
}

func (m *PlayerArena) GetLastTicketsRefreshTime() int32 {
	if m != nil && m.LastTicketsRefreshTime != nil {
		return *m.LastTicketsRefreshTime
	}
	return 0
}

func (m *PlayerArena) GetSerialId() int32 {
	if m != nil && m.SerialId != nil {
		return *m.SerialId
	}
	return 0
}

type PlayerEquip struct {
	TmpSaveLeftSlotRoleId *int32 `protobuf:"varint,1,opt,name=TmpSaveLeftSlotRoleId" json:"TmpSaveLeftSlotRoleId,omitempty"`
	TmpLeftSlotItemId     *int32 `protobuf:"varint,2,opt,name=TmpLeftSlotItemId" json:"TmpLeftSlotItemId,omitempty"`
	XXX_unrecognized      []byte `json:"-"`
}

func (m *PlayerEquip) Reset()                    { *m = PlayerEquip{} }
func (m *PlayerEquip) String() string            { return proto.CompactTextString(m) }
func (*PlayerEquip) ProtoMessage()               {}
func (*PlayerEquip) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *PlayerEquip) GetTmpSaveLeftSlotRoleId() int32 {
	if m != nil && m.TmpSaveLeftSlotRoleId != nil {
		return *m.TmpSaveLeftSlotRoleId
	}
	return 0
}

func (m *PlayerEquip) GetTmpLeftSlotItemId() int32 {
	if m != nil && m.TmpLeftSlotItemId != nil {
		return *m.TmpLeftSlotItemId
	}
	return 0
}

type PlayerActiveStageCommon struct {
	LastRefreshTime  *int32 `protobuf:"varint,1,opt,name=LastRefreshTime" json:"LastRefreshTime,omitempty"`
	GetPointsDay     *int32 `protobuf:"varint,2,opt,name=GetPointsDay" json:"GetPointsDay,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerActiveStageCommon) Reset()                    { *m = PlayerActiveStageCommon{} }
func (m *PlayerActiveStageCommon) String() string            { return proto.CompactTextString(m) }
func (*PlayerActiveStageCommon) ProtoMessage()               {}
func (*PlayerActiveStageCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *PlayerActiveStageCommon) GetLastRefreshTime() int32 {
	if m != nil && m.LastRefreshTime != nil {
		return *m.LastRefreshTime
	}
	return 0
}

func (m *PlayerActiveStageCommon) GetGetPointsDay() int32 {
	if m != nil && m.GetPointsDay != nil {
		return *m.GetPointsDay
	}
	return 0
}

type PlayerActiveStage struct {
	Type             *int32 `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	CanChallengeNum  *int32 `protobuf:"varint,2,opt,name=CanChallengeNum" json:"CanChallengeNum,omitempty"`
	PurchasedNum     *int32 `protobuf:"varint,3,opt,name=PurchasedNum" json:"PurchasedNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerActiveStage) Reset()                    { *m = PlayerActiveStage{} }
func (m *PlayerActiveStage) String() string            { return proto.CompactTextString(m) }
func (*PlayerActiveStage) ProtoMessage()               {}
func (*PlayerActiveStage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *PlayerActiveStage) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *PlayerActiveStage) GetCanChallengeNum() int32 {
	if m != nil && m.CanChallengeNum != nil {
		return *m.CanChallengeNum
	}
	return 0
}

func (m *PlayerActiveStage) GetPurchasedNum() int32 {
	if m != nil && m.PurchasedNum != nil {
		return *m.PurchasedNum
	}
	return 0
}

type PlayerActiveStageList struct {
	List             []*PlayerActiveStage `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *PlayerActiveStageList) Reset()                    { *m = PlayerActiveStageList{} }
func (m *PlayerActiveStageList) String() string            { return proto.CompactTextString(m) }
func (*PlayerActiveStageList) ProtoMessage()               {}
func (*PlayerActiveStageList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *PlayerActiveStageList) GetList() []*PlayerActiveStage {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendCommon struct {
	LastRecommendTime    *int32  `protobuf:"varint,1,opt,name=LastRecommendTime" json:"LastRecommendTime,omitempty"`
	LastBossRefreshTime  *int32  `protobuf:"varint,2,opt,name=LastBossRefreshTime" json:"LastBossRefreshTime,omitempty"`
	FriendBossTableId    *int32  `protobuf:"varint,3,opt,name=FriendBossTableId" json:"FriendBossTableId,omitempty"`
	FriendBossHpPercent  *int32  `protobuf:"varint,4,opt,name=FriendBossHpPercent" json:"FriendBossHpPercent,omitempty"`
	AttackBossPlayerList []int32 `protobuf:"varint,5,rep,name=AttackBossPlayerList" json:"AttackBossPlayerList,omitempty"`
	LastGetStaminaTime   *int32  `protobuf:"varint,6,opt,name=LastGetStaminaTime" json:"LastGetStaminaTime,omitempty"`
	AssistRoleId         *int32  `protobuf:"varint,7,opt,name=AssistRoleId" json:"AssistRoleId,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *PlayerFriendCommon) Reset()                    { *m = PlayerFriendCommon{} }
func (m *PlayerFriendCommon) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendCommon) ProtoMessage()               {}
func (*PlayerFriendCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *PlayerFriendCommon) GetLastRecommendTime() int32 {
	if m != nil && m.LastRecommendTime != nil {
		return *m.LastRecommendTime
	}
	return 0
}

func (m *PlayerFriendCommon) GetLastBossRefreshTime() int32 {
	if m != nil && m.LastBossRefreshTime != nil {
		return *m.LastBossRefreshTime
	}
	return 0
}

func (m *PlayerFriendCommon) GetFriendBossTableId() int32 {
	if m != nil && m.FriendBossTableId != nil {
		return *m.FriendBossTableId
	}
	return 0
}

func (m *PlayerFriendCommon) GetFriendBossHpPercent() int32 {
	if m != nil && m.FriendBossHpPercent != nil {
		return *m.FriendBossHpPercent
	}
	return 0
}

func (m *PlayerFriendCommon) GetAttackBossPlayerList() []int32 {
	if m != nil {
		return m.AttackBossPlayerList
	}
	return nil
}

func (m *PlayerFriendCommon) GetLastGetStaminaTime() int32 {
	if m != nil && m.LastGetStaminaTime != nil {
		return *m.LastGetStaminaTime
	}
	return 0
}

func (m *PlayerFriendCommon) GetAssistRoleId() int32 {
	if m != nil && m.AssistRoleId != nil {
		return *m.AssistRoleId
	}
	return 0
}

type PlayerFriend struct {
	PlayerId           *int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	LastGivePointsTime *int32 `protobuf:"varint,2,opt,name=LastGivePointsTime" json:"LastGivePointsTime,omitempty"`
	XXX_unrecognized   []byte `json:"-"`
}

func (m *PlayerFriend) Reset()                    { *m = PlayerFriend{} }
func (m *PlayerFriend) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriend) ProtoMessage()               {}
func (*PlayerFriend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *PlayerFriend) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *PlayerFriend) GetLastGivePointsTime() int32 {
	if m != nil && m.LastGivePointsTime != nil {
		return *m.LastGivePointsTime
	}
	return 0
}

type PlayerFriendList struct {
	List             []*PlayerFriend `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PlayerFriendList) Reset()                    { *m = PlayerFriendList{} }
func (m *PlayerFriendList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendList) ProtoMessage()               {}
func (*PlayerFriendList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *PlayerFriendList) GetList() []*PlayerFriend {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendRecommend struct {
	PlayerId         *int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFriendRecommend) Reset()                    { *m = PlayerFriendRecommend{} }
func (m *PlayerFriendRecommend) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendRecommend) ProtoMessage()               {}
func (*PlayerFriendRecommend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *PlayerFriendRecommend) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type PlayerFriendRecommendList struct {
	List             []*PlayerFriendRecommend `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *PlayerFriendRecommendList) Reset()                    { *m = PlayerFriendRecommendList{} }
func (m *PlayerFriendRecommendList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendRecommendList) ProtoMessage()               {}
func (*PlayerFriendRecommendList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *PlayerFriendRecommendList) GetList() []*PlayerFriendRecommend {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendAsk struct {
	PlayerId         *int32 `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFriendAsk) Reset()                    { *m = PlayerFriendAsk{} }
func (m *PlayerFriendAsk) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendAsk) ProtoMessage()               {}
func (*PlayerFriendAsk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *PlayerFriendAsk) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type PlayerFriendAskList struct {
	List             []*PlayerFriendAsk `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PlayerFriendAskList) Reset()                    { *m = PlayerFriendAskList{} }
func (m *PlayerFriendAskList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendAskList) ProtoMessage()               {}
func (*PlayerFriendAskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *PlayerFriendAskList) GetList() []*PlayerFriendAsk {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendBoss struct {
	MonsterPos       *int32 `protobuf:"varint,1,opt,name=MonsterPos" json:"MonsterPos,omitempty"`
	MonsterId        *int32 `protobuf:"varint,2,opt,name=MonsterId" json:"MonsterId,omitempty"`
	MonsterHp        *int32 `protobuf:"varint,3,opt,name=MonsterHp" json:"MonsterHp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFriendBoss) Reset()                    { *m = PlayerFriendBoss{} }
func (m *PlayerFriendBoss) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendBoss) ProtoMessage()               {}
func (*PlayerFriendBoss) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *PlayerFriendBoss) GetMonsterPos() int32 {
	if m != nil && m.MonsterPos != nil {
		return *m.MonsterPos
	}
	return 0
}

func (m *PlayerFriendBoss) GetMonsterId() int32 {
	if m != nil && m.MonsterId != nil {
		return *m.MonsterId
	}
	return 0
}

func (m *PlayerFriendBoss) GetMonsterHp() int32 {
	if m != nil && m.MonsterHp != nil {
		return *m.MonsterHp
	}
	return 0
}

type PlayerFriendBossList struct {
	List             []*PlayerFriendBoss `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PlayerFriendBossList) Reset()                    { *m = PlayerFriendBossList{} }
func (m *PlayerFriendBossList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendBossList) ProtoMessage()               {}
func (*PlayerFriendBossList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *PlayerFriendBossList) GetList() []*PlayerFriendBoss {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerTaskCommon struct {
	LastRefreshTime  *int32 `protobuf:"varint,1,opt,name=LastRefreshTime" json:"LastRefreshTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerTaskCommon) Reset()                    { *m = PlayerTaskCommon{} }
func (m *PlayerTaskCommon) String() string            { return proto.CompactTextString(m) }
func (*PlayerTaskCommon) ProtoMessage()               {}
func (*PlayerTaskCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *PlayerTaskCommon) GetLastRefreshTime() int32 {
	if m != nil && m.LastRefreshTime != nil {
		return *m.LastRefreshTime
	}
	return 0
}

type PlayerTask struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	State            *int32 `protobuf:"varint,3,opt,name=State" json:"State,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerTask) Reset()                    { *m = PlayerTask{} }
func (m *PlayerTask) String() string            { return proto.CompactTextString(m) }
func (*PlayerTask) ProtoMessage()               {}
func (*PlayerTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *PlayerTask) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerTask) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *PlayerTask) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type PlayerTaskList struct {
	List             []*PlayerTask `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerTaskList) Reset()                    { *m = PlayerTaskList{} }
func (m *PlayerTaskList) String() string            { return proto.CompactTextString(m) }
func (*PlayerTaskList) ProtoMessage()               {}
func (*PlayerTaskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

func (m *PlayerTaskList) GetList() []*PlayerTask {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFinishedTask struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFinishedTask) Reset()                    { *m = PlayerFinishedTask{} }
func (m *PlayerFinishedTask) String() string            { return proto.CompactTextString(m) }
func (*PlayerFinishedTask) ProtoMessage()               {}
func (*PlayerFinishedTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

func (m *PlayerFinishedTask) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type PlayerFinishedTaskList struct {
	List             []*PlayerFinishedTask `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PlayerFinishedTaskList) Reset()                    { *m = PlayerFinishedTaskList{} }
func (m *PlayerFinishedTaskList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFinishedTaskList) ProtoMessage()               {}
func (*PlayerFinishedTaskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{54} }

func (m *PlayerFinishedTaskList) GetList() []*PlayerFinishedTask {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerDailyTaskAllDaily struct {
	CompleteTaskId   *int32 `protobuf:"varint,1,opt,name=CompleteTaskId" json:"CompleteTaskId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerDailyTaskAllDaily) Reset()                    { *m = PlayerDailyTaskAllDaily{} }
func (m *PlayerDailyTaskAllDaily) String() string            { return proto.CompactTextString(m) }
func (*PlayerDailyTaskAllDaily) ProtoMessage()               {}
func (*PlayerDailyTaskAllDaily) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{55} }

func (m *PlayerDailyTaskAllDaily) GetCompleteTaskId() int32 {
	if m != nil && m.CompleteTaskId != nil {
		return *m.CompleteTaskId
	}
	return 0
}

type PlayerDailyTaskAllDailyList struct {
	List             []*PlayerDailyTaskAllDaily `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *PlayerDailyTaskAllDailyList) Reset()                    { *m = PlayerDailyTaskAllDailyList{} }
func (m *PlayerDailyTaskAllDailyList) String() string            { return proto.CompactTextString(m) }
func (*PlayerDailyTaskAllDailyList) ProtoMessage()               {}
func (*PlayerDailyTaskAllDailyList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{56} }

func (m *PlayerDailyTaskAllDailyList) GetList() []*PlayerDailyTaskAllDaily {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerExploreCommon struct {
	LastRefreshTime  *int32 `protobuf:"varint,1,opt,name=LastRefreshTime" json:"LastRefreshTime,omitempty"`
	CurrentId        *int32 `protobuf:"varint,2,opt,name=CurrentId" json:"CurrentId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerExploreCommon) Reset()                    { *m = PlayerExploreCommon{} }
func (m *PlayerExploreCommon) String() string            { return proto.CompactTextString(m) }
func (*PlayerExploreCommon) ProtoMessage()               {}
func (*PlayerExploreCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{57} }

func (m *PlayerExploreCommon) GetLastRefreshTime() int32 {
	if m != nil && m.LastRefreshTime != nil {
		return *m.LastRefreshTime
	}
	return 0
}

func (m *PlayerExploreCommon) GetCurrentId() int32 {
	if m != nil && m.CurrentId != nil {
		return *m.CurrentId
	}
	return 0
}

type PlayerExplore struct {
	Id               *int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	TaskId           *int32  `protobuf:"varint,2,opt,name=TaskId" json:"TaskId,omitempty"`
	State            *int32  `protobuf:"varint,3,opt,name=State" json:"State,omitempty"`
	RoleCampsCanSel  []int32 `protobuf:"varint,4,rep,name=RoleCampsCanSel" json:"RoleCampsCanSel,omitempty"`
	RoleTypesCanSel  []int32 `protobuf:"varint,5,rep,name=RoleTypesCanSel" json:"RoleTypesCanSel,omitempty"`
	RoleId4TaskTitle *int32  `protobuf:"varint,6,opt,name=RoleId4TaskTitle" json:"RoleId4TaskTitle,omitempty"`
	NameId4TaskTitle *int32  `protobuf:"varint,7,opt,name=NameId4TaskTitle" json:"NameId4TaskTitle,omitempty"`
	StartTime        *int32  `protobuf:"varint,8,opt,name=StartTime" json:"StartTime,omitempty"`
	RoleIds          []int32 `protobuf:"varint,9,rep,name=RoleIds" json:"RoleIds,omitempty"`
	IsLock           *int32  `protobuf:"varint,10,opt,name=IsLock" json:"IsLock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerExplore) Reset()                    { *m = PlayerExplore{} }
func (m *PlayerExplore) String() string            { return proto.CompactTextString(m) }
func (*PlayerExplore) ProtoMessage()               {}
func (*PlayerExplore) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{58} }

func (m *PlayerExplore) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerExplore) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *PlayerExplore) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *PlayerExplore) GetRoleCampsCanSel() []int32 {
	if m != nil {
		return m.RoleCampsCanSel
	}
	return nil
}

func (m *PlayerExplore) GetRoleTypesCanSel() []int32 {
	if m != nil {
		return m.RoleTypesCanSel
	}
	return nil
}

func (m *PlayerExplore) GetRoleId4TaskTitle() int32 {
	if m != nil && m.RoleId4TaskTitle != nil {
		return *m.RoleId4TaskTitle
	}
	return 0
}

func (m *PlayerExplore) GetNameId4TaskTitle() int32 {
	if m != nil && m.NameId4TaskTitle != nil {
		return *m.NameId4TaskTitle
	}
	return 0
}

func (m *PlayerExplore) GetStartTime() int32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *PlayerExplore) GetRoleIds() []int32 {
	if m != nil {
		return m.RoleIds
	}
	return nil
}

func (m *PlayerExplore) GetIsLock() int32 {
	if m != nil && m.IsLock != nil {
		return *m.IsLock
	}
	return 0
}

type PlayerExploreList struct {
	List             []*PlayerExplore `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PlayerExploreList) Reset()                    { *m = PlayerExploreList{} }
func (m *PlayerExploreList) String() string            { return proto.CompactTextString(m) }
func (*PlayerExploreList) ProtoMessage()               {}
func (*PlayerExploreList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{59} }

func (m *PlayerExploreList) GetList() []*PlayerExplore {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerExploreStory struct {
	TaskId           *int32  `protobuf:"varint,1,opt,name=TaskId" json:"TaskId,omitempty"`
	State            *int32  `protobuf:"varint,2,opt,name=State" json:"State,omitempty"`
	RoleCampsCanSel  []int32 `protobuf:"varint,3,rep,name=RoleCampsCanSel" json:"RoleCampsCanSel,omitempty"`
	RoleTypesCanSel  []int32 `protobuf:"varint,4,rep,name=RoleTypesCanSel" json:"RoleTypesCanSel,omitempty"`
	StartTime        *int32  `protobuf:"varint,5,opt,name=StartTime" json:"StartTime,omitempty"`
	RoleIds          []int32 `protobuf:"varint,6,rep,name=RoleIds" json:"RoleIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerExploreStory) Reset()                    { *m = PlayerExploreStory{} }
func (m *PlayerExploreStory) String() string            { return proto.CompactTextString(m) }
func (*PlayerExploreStory) ProtoMessage()               {}
func (*PlayerExploreStory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{60} }

func (m *PlayerExploreStory) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *PlayerExploreStory) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *PlayerExploreStory) GetRoleCampsCanSel() []int32 {
	if m != nil {
		return m.RoleCampsCanSel
	}
	return nil
}

func (m *PlayerExploreStory) GetRoleTypesCanSel() []int32 {
	if m != nil {
		return m.RoleTypesCanSel
	}
	return nil
}

func (m *PlayerExploreStory) GetStartTime() int32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *PlayerExploreStory) GetRoleIds() []int32 {
	if m != nil {
		return m.RoleIds
	}
	return nil
}

type PlayerExploreStoryList struct {
	List             []*PlayerExploreStory `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PlayerExploreStoryList) Reset()                    { *m = PlayerExploreStoryList{} }
func (m *PlayerExploreStoryList) String() string            { return proto.CompactTextString(m) }
func (*PlayerExploreStoryList) ProtoMessage()               {}
func (*PlayerExploreStoryList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{61} }

func (m *PlayerExploreStoryList) GetList() []*PlayerExploreStory {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerSevenActivity struct {
	ActivityId       *int32 `protobuf:"varint,1,opt,name=ActivityId" json:"ActivityId,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	RewardUnix       *int32 `protobuf:"varint,3,opt,name=RewardUnix" json:"RewardUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerSevenActivity) Reset()                    { *m = PlayerSevenActivity{} }
func (m *PlayerSevenActivity) String() string            { return proto.CompactTextString(m) }
func (*PlayerSevenActivity) ProtoMessage()               {}
func (*PlayerSevenActivity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{62} }

func (m *PlayerSevenActivity) GetActivityId() int32 {
	if m != nil && m.ActivityId != nil {
		return *m.ActivityId
	}
	return 0
}

func (m *PlayerSevenActivity) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *PlayerSevenActivity) GetRewardUnix() int32 {
	if m != nil && m.RewardUnix != nil {
		return *m.RewardUnix
	}
	return 0
}

type PlayerSevenActivityList struct {
	List             []*PlayerSevenActivity `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PlayerSevenActivityList) Reset()                    { *m = PlayerSevenActivityList{} }
func (m *PlayerSevenActivityList) String() string            { return proto.CompactTextString(m) }
func (*PlayerSevenActivityList) ProtoMessage()               {}
func (*PlayerSevenActivityList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{63} }

func (m *PlayerSevenActivityList) GetList() []*PlayerSevenActivity {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerGuides struct {
	GuideId          *int32 `protobuf:"varint,1,opt,name=GuideId" json:"GuideId,omitempty"`
	SetUnix          *int32 `protobuf:"varint,2,opt,name=SetUnix" json:"SetUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerGuides) Reset()                    { *m = PlayerGuides{} }
func (m *PlayerGuides) String() string            { return proto.CompactTextString(m) }
func (*PlayerGuides) ProtoMessage()               {}
func (*PlayerGuides) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{64} }

func (m *PlayerGuides) GetGuideId() int32 {
	if m != nil && m.GuideId != nil {
		return *m.GuideId
	}
	return 0
}

func (m *PlayerGuides) GetSetUnix() int32 {
	if m != nil && m.SetUnix != nil {
		return *m.SetUnix
	}
	return 0
}

type PlayerGuidesList struct {
	List             []*PlayerGuides `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PlayerGuidesList) Reset()                    { *m = PlayerGuidesList{} }
func (m *PlayerGuidesList) String() string            { return proto.CompactTextString(m) }
func (*PlayerGuidesList) ProtoMessage()               {}
func (*PlayerGuidesList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{65} }

func (m *PlayerGuidesList) GetList() []*PlayerGuides {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendChatUnreadId struct {
	FriendId         *int32  `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	MessageIds       []int32 `protobuf:"varint,2,rep,name=MessageIds" json:"MessageIds,omitempty"`
	CurrMessageId    *int32  `protobuf:"varint,3,opt,name=CurrMessageId" json:"CurrMessageId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerFriendChatUnreadId) Reset()                    { *m = PlayerFriendChatUnreadId{} }
func (m *PlayerFriendChatUnreadId) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadId) ProtoMessage()               {}
func (*PlayerFriendChatUnreadId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{66} }

func (m *PlayerFriendChatUnreadId) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

func (m *PlayerFriendChatUnreadId) GetMessageIds() []int32 {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *PlayerFriendChatUnreadId) GetCurrMessageId() int32 {
	if m != nil && m.CurrMessageId != nil {
		return *m.CurrMessageId
	}
	return 0
}

type PlayerFriendChatUnreadIdList struct {
	List             []*PlayerFriendChatUnreadId `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *PlayerFriendChatUnreadIdList) Reset()                    { *m = PlayerFriendChatUnreadIdList{} }
func (m *PlayerFriendChatUnreadIdList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadIdList) ProtoMessage()               {}
func (*PlayerFriendChatUnreadIdList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{67} }

func (m *PlayerFriendChatUnreadIdList) GetList() []*PlayerFriendChatUnreadId {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendChatUnreadMessage struct {
	PlayerMessageId  *int64 `protobuf:"varint,1,opt,name=PlayerMessageId" json:"PlayerMessageId,omitempty"`
	Message          []byte `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	SendTime         *int32 `protobuf:"varint,3,opt,name=SendTime" json:"SendTime,omitempty"`
	IsRead           *int32 `protobuf:"varint,4,opt,name=IsRead" json:"IsRead,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFriendChatUnreadMessage) Reset()                    { *m = PlayerFriendChatUnreadMessage{} }
func (m *PlayerFriendChatUnreadMessage) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadMessage) ProtoMessage()               {}
func (*PlayerFriendChatUnreadMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{68} }

func (m *PlayerFriendChatUnreadMessage) GetPlayerMessageId() int64 {
	if m != nil && m.PlayerMessageId != nil {
		return *m.PlayerMessageId
	}
	return 0
}

func (m *PlayerFriendChatUnreadMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PlayerFriendChatUnreadMessage) GetSendTime() int32 {
	if m != nil && m.SendTime != nil {
		return *m.SendTime
	}
	return 0
}

func (m *PlayerFriendChatUnreadMessage) GetIsRead() int32 {
	if m != nil && m.IsRead != nil {
		return *m.IsRead
	}
	return 0
}

type PlayerFriendChatUnreadMessageList struct {
	List             []*PlayerFriendChatUnreadMessage `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *PlayerFriendChatUnreadMessageList) Reset()         { *m = PlayerFriendChatUnreadMessageList{} }
func (m *PlayerFriendChatUnreadMessageList) String() string { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadMessageList) ProtoMessage()    {}
func (*PlayerFriendChatUnreadMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{69}
}

func (m *PlayerFriendChatUnreadMessageList) GetList() []*PlayerFriendChatUnreadMessage {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerHeadItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerHeadItem) Reset()                    { *m = PlayerHeadItem{} }
func (m *PlayerHeadItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerHeadItem) ProtoMessage()               {}
func (*PlayerHeadItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{70} }

func (m *PlayerHeadItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type PlayerHeadItemList struct {
	List             []*PlayerHeadItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PlayerHeadItemList) Reset()                    { *m = PlayerHeadItemList{} }
func (m *PlayerHeadItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerHeadItemList) ProtoMessage()               {}
func (*PlayerHeadItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{71} }

func (m *PlayerHeadItemList) GetList() []*PlayerHeadItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerSuitAward struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	AwardTime        *int32 `protobuf:"varint,2,opt,name=AwardTime" json:"AwardTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerSuitAward) Reset()                    { *m = PlayerSuitAward{} }
func (m *PlayerSuitAward) String() string            { return proto.CompactTextString(m) }
func (*PlayerSuitAward) ProtoMessage()               {}
func (*PlayerSuitAward) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{72} }

func (m *PlayerSuitAward) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerSuitAward) GetAwardTime() int32 {
	if m != nil && m.AwardTime != nil {
		return *m.AwardTime
	}
	return 0
}

type PlayerSuitAwardList struct {
	List             []*PlayerSuitAward `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PlayerSuitAwardList) Reset()                    { *m = PlayerSuitAwardList{} }
func (m *PlayerSuitAwardList) String() string            { return proto.CompactTextString(m) }
func (*PlayerSuitAwardList) ProtoMessage()               {}
func (*PlayerSuitAwardList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{73} }

func (m *PlayerSuitAwardList) GetList() []*PlayerSuitAward {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerWorldChat struct {
	LastChatTime     *int32 `protobuf:"varint,1,opt,name=LastChatTime" json:"LastChatTime,omitempty"`
	LastPullTime     *int32 `protobuf:"varint,2,opt,name=LastPullTime" json:"LastPullTime,omitempty"`
	LastMsgIndex     *int32 `protobuf:"varint,3,opt,name=LastMsgIndex" json:"LastMsgIndex,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerWorldChat) Reset()                    { *m = PlayerWorldChat{} }
func (m *PlayerWorldChat) String() string            { return proto.CompactTextString(m) }
func (*PlayerWorldChat) ProtoMessage()               {}
func (*PlayerWorldChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{74} }

func (m *PlayerWorldChat) GetLastChatTime() int32 {
	if m != nil && m.LastChatTime != nil {
		return *m.LastChatTime
	}
	return 0
}

func (m *PlayerWorldChat) GetLastPullTime() int32 {
	if m != nil && m.LastPullTime != nil {
		return *m.LastPullTime
	}
	return 0
}

func (m *PlayerWorldChat) GetLastMsgIndex() int32 {
	if m != nil && m.LastMsgIndex != nil {
		return *m.LastMsgIndex
	}
	return 0
}

type PlayerAnouncement struct {
	LastSendTime     *int32 `protobuf:"varint,1,opt,name=LastSendTime" json:"LastSendTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerAnouncement) Reset()                    { *m = PlayerAnouncement{} }
func (m *PlayerAnouncement) String() string            { return proto.CompactTextString(m) }
func (*PlayerAnouncement) ProtoMessage()               {}
func (*PlayerAnouncement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{75} }

func (m *PlayerAnouncement) GetLastSendTime() int32 {
	if m != nil && m.LastSendTime != nil {
		return *m.LastSendTime
	}
	return 0
}

type PlayerFirstDrawCard struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Drawed           *int32 `protobuf:"varint,2,opt,name=Drawed" json:"Drawed,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFirstDrawCard) Reset()                    { *m = PlayerFirstDrawCard{} }
func (m *PlayerFirstDrawCard) String() string            { return proto.CompactTextString(m) }
func (*PlayerFirstDrawCard) ProtoMessage()               {}
func (*PlayerFirstDrawCard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{76} }

func (m *PlayerFirstDrawCard) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerFirstDrawCard) GetDrawed() int32 {
	if m != nil && m.Drawed != nil {
		return *m.Drawed
	}
	return 0
}

type PlayerFirstDrawCardList struct {
	List             []*PlayerFirstDrawCard `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PlayerFirstDrawCardList) Reset()                    { *m = PlayerFirstDrawCardList{} }
func (m *PlayerFirstDrawCardList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFirstDrawCardList) ProtoMessage()               {}
func (*PlayerFirstDrawCardList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{77} }

func (m *PlayerFirstDrawCardList) GetList() []*PlayerFirstDrawCard {
	if m != nil {
		return m.List
	}
	return nil
}

type BattleSaveData struct {
	Data             []byte `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BattleSaveData) Reset()                    { *m = BattleSaveData{} }
func (m *BattleSaveData) String() string            { return proto.CompactTextString(m) }
func (*BattleSaveData) ProtoMessage()               {}
func (*BattleSaveData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{78} }

func (m *BattleSaveData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TowerFightSaveData struct {
	Data             []byte `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TowerFightSaveData) Reset()                    { *m = TowerFightSaveData{} }
func (m *TowerFightSaveData) String() string            { return proto.CompactTextString(m) }
func (*TowerFightSaveData) ProtoMessage()               {}
func (*TowerFightSaveData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{79} }

func (m *TowerFightSaveData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TowerRankingListPlayers struct {
	Ids              []int32 `protobuf:"varint,1,rep,name=Ids" json:"Ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TowerRankingListPlayers) Reset()                    { *m = TowerRankingListPlayers{} }
func (m *TowerRankingListPlayers) String() string            { return proto.CompactTextString(m) }
func (*TowerRankingListPlayers) ProtoMessage()               {}
func (*TowerRankingListPlayers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{80} }

func (m *TowerRankingListPlayers) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ArenaSeasonData struct {
	LastDayResetTime    *int32 `protobuf:"varint,1,opt,name=LastDayResetTime" json:"LastDayResetTime,omitempty"`
	LastSeasonResetTime *int32 `protobuf:"varint,2,opt,name=LastSeasonResetTime" json:"LastSeasonResetTime,omitempty"`
	XXX_unrecognized    []byte `json:"-"`
}

func (m *ArenaSeasonData) Reset()                    { *m = ArenaSeasonData{} }
func (m *ArenaSeasonData) String() string            { return proto.CompactTextString(m) }
func (*ArenaSeasonData) ProtoMessage()               {}
func (*ArenaSeasonData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{81} }

func (m *ArenaSeasonData) GetLastDayResetTime() int32 {
	if m != nil && m.LastDayResetTime != nil {
		return *m.LastDayResetTime
	}
	return 0
}

func (m *ArenaSeasonData) GetLastSeasonResetTime() int32 {
	if m != nil && m.LastSeasonResetTime != nil {
		return *m.LastSeasonResetTime
	}
	return 0
}

func init() {
	proto.RegisterType((*SmallRankRecord)(nil), "db.SmallRankRecord")
	proto.RegisterType((*LimitShopItem)(nil), "db.LimitShopItem")
	proto.RegisterType((*PlayerInfo)(nil), "db.PlayerInfo")
	proto.RegisterType((*PlayerGlobal)(nil), "db.PlayerGlobal")
	proto.RegisterType((*PlayerItem)(nil), "db.PlayerItem")
	proto.RegisterType((*PlayerItemList)(nil), "db.PlayerItemList")
	proto.RegisterType((*PlayerRole)(nil), "db.PlayerRole")
	proto.RegisterType((*PlayerRoleList)(nil), "db.PlayerRoleList")
	proto.RegisterType((*PlayerRoleHandbook)(nil), "db.PlayerRoleHandbook")
	proto.RegisterType((*PlayerBattleTeam)(nil), "db.PlayerBattleTeam")
	proto.RegisterType((*PlayerCampaignCommon)(nil), "db.PlayerCampaignCommon")
	proto.RegisterType((*PlayerCampaign)(nil), "db.PlayerCampaign")
	proto.RegisterType((*PlayerCampaignList)(nil), "db.PlayerCampaignList")
	proto.RegisterType((*PlayerCampaignStaticIncome)(nil), "db.PlayerCampaignStaticIncome")
	proto.RegisterType((*PlayerCampaignStaticIncomeList)(nil), "db.PlayerCampaignStaticIncomeList")
	proto.RegisterType((*PlayerCampaignRandomIncome)(nil), "db.PlayerCampaignRandomIncome")
	proto.RegisterType((*PlayerCampaignRandomIncomeList)(nil), "db.PlayerCampaignRandomIncomeList")
	proto.RegisterType((*PlayerNotifyState)(nil), "db.PlayerNotifyState")
	proto.RegisterType((*PlayerNotifyStateList)(nil), "db.PlayerNotifyStateList")
	proto.RegisterType((*PlayerMailCommon)(nil), "db.PlayerMailCommon")
	proto.RegisterType((*PlayerMail)(nil), "db.PlayerMail")
	proto.RegisterType((*PlayerMailList)(nil), "db.PlayerMailList")
	proto.RegisterType((*PlayerBattleSave)(nil), "db.PlayerBattleSave")
	proto.RegisterType((*PlayerBattleSaveList)(nil), "db.PlayerBattleSaveList")
	proto.RegisterType((*PlayerTalent)(nil), "db.PlayerTalent")
	proto.RegisterType((*PlayerTalentList)(nil), "db.PlayerTalentList")
	proto.RegisterType((*PlayerTowerCommon)(nil), "db.PlayerTowerCommon")
	proto.RegisterType((*PlayerTower)(nil), "db.PlayerTower")
	proto.RegisterType((*PlayerTowerList)(nil), "db.PlayerTowerList")
	proto.RegisterType((*PlayerDraw)(nil), "db.PlayerDraw")
	proto.RegisterType((*PlayerDrawList)(nil), "db.PlayerDrawList")
	proto.RegisterType((*PlayerGoldHand)(nil), "db.PlayerGoldHand")
	proto.RegisterType((*PlayerShop)(nil), "db.PlayerShop")
	proto.RegisterType((*PlayerShopList)(nil), "db.PlayerShopList")
	proto.RegisterType((*PlayerShopItem)(nil), "db.PlayerShopItem")
	proto.RegisterType((*PlayerShopItemList)(nil), "db.PlayerShopItemList")
	proto.RegisterType((*PlayerArena)(nil), "db.PlayerArena")
	proto.RegisterType((*PlayerEquip)(nil), "db.PlayerEquip")
	proto.RegisterType((*PlayerActiveStageCommon)(nil), "db.PlayerActiveStageCommon")
	proto.RegisterType((*PlayerActiveStage)(nil), "db.PlayerActiveStage")
	proto.RegisterType((*PlayerActiveStageList)(nil), "db.PlayerActiveStageList")
	proto.RegisterType((*PlayerFriendCommon)(nil), "db.PlayerFriendCommon")
	proto.RegisterType((*PlayerFriend)(nil), "db.PlayerFriend")
	proto.RegisterType((*PlayerFriendList)(nil), "db.PlayerFriendList")
	proto.RegisterType((*PlayerFriendRecommend)(nil), "db.PlayerFriendRecommend")
	proto.RegisterType((*PlayerFriendRecommendList)(nil), "db.PlayerFriendRecommendList")
	proto.RegisterType((*PlayerFriendAsk)(nil), "db.PlayerFriendAsk")
	proto.RegisterType((*PlayerFriendAskList)(nil), "db.PlayerFriendAskList")
	proto.RegisterType((*PlayerFriendBoss)(nil), "db.PlayerFriendBoss")
	proto.RegisterType((*PlayerFriendBossList)(nil), "db.PlayerFriendBossList")
	proto.RegisterType((*PlayerTaskCommon)(nil), "db.PlayerTaskCommon")
	proto.RegisterType((*PlayerTask)(nil), "db.PlayerTask")
	proto.RegisterType((*PlayerTaskList)(nil), "db.PlayerTaskList")
	proto.RegisterType((*PlayerFinishedTask)(nil), "db.PlayerFinishedTask")
	proto.RegisterType((*PlayerFinishedTaskList)(nil), "db.PlayerFinishedTaskList")
	proto.RegisterType((*PlayerDailyTaskAllDaily)(nil), "db.PlayerDailyTaskAllDaily")
	proto.RegisterType((*PlayerDailyTaskAllDailyList)(nil), "db.PlayerDailyTaskAllDailyList")
	proto.RegisterType((*PlayerExploreCommon)(nil), "db.PlayerExploreCommon")
	proto.RegisterType((*PlayerExplore)(nil), "db.PlayerExplore")
	proto.RegisterType((*PlayerExploreList)(nil), "db.PlayerExploreList")
	proto.RegisterType((*PlayerExploreStory)(nil), "db.PlayerExploreStory")
	proto.RegisterType((*PlayerExploreStoryList)(nil), "db.PlayerExploreStoryList")
	proto.RegisterType((*PlayerSevenActivity)(nil), "db.PlayerSevenActivity")
	proto.RegisterType((*PlayerSevenActivityList)(nil), "db.PlayerSevenActivityList")
	proto.RegisterType((*PlayerGuides)(nil), "db.PlayerGuides")
	proto.RegisterType((*PlayerGuidesList)(nil), "db.PlayerGuidesList")
	proto.RegisterType((*PlayerFriendChatUnreadId)(nil), "db.PlayerFriendChatUnreadId")
	proto.RegisterType((*PlayerFriendChatUnreadIdList)(nil), "db.PlayerFriendChatUnreadIdList")
	proto.RegisterType((*PlayerFriendChatUnreadMessage)(nil), "db.PlayerFriendChatUnreadMessage")
	proto.RegisterType((*PlayerFriendChatUnreadMessageList)(nil), "db.PlayerFriendChatUnreadMessageList")
	proto.RegisterType((*PlayerHeadItem)(nil), "db.PlayerHeadItem")
	proto.RegisterType((*PlayerHeadItemList)(nil), "db.PlayerHeadItemList")
	proto.RegisterType((*PlayerSuitAward)(nil), "db.PlayerSuitAward")
	proto.RegisterType((*PlayerSuitAwardList)(nil), "db.PlayerSuitAwardList")
	proto.RegisterType((*PlayerWorldChat)(nil), "db.PlayerWorldChat")
	proto.RegisterType((*PlayerAnouncement)(nil), "db.PlayerAnouncement")
	proto.RegisterType((*PlayerFirstDrawCard)(nil), "db.PlayerFirstDrawCard")
	proto.RegisterType((*PlayerFirstDrawCardList)(nil), "db.PlayerFirstDrawCardList")
	proto.RegisterType((*BattleSaveData)(nil), "db.BattleSaveData")
	proto.RegisterType((*TowerFightSaveData)(nil), "db.TowerFightSaveData")
	proto.RegisterType((*TowerRankingListPlayers)(nil), "db.TowerRankingListPlayers")
	proto.RegisterType((*ArenaSeasonData)(nil), "db.ArenaSeasonData")
}

func init() { proto.RegisterFile("db_hallsvr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x59, 0x5f, 0x6f, 0x1b, 0xb9,
	0x11, 0x87, 0x24, 0xcb, 0x89, 0x19, 0x27, 0x71, 0xf6, 0x1c, 0x67, 0xef, 0xce, 0x67, 0xf8, 0xb6,
	0xe9, 0xd5, 0xcd, 0xf5, 0xd2, 0x20, 0x4d, 0xaf, 0x45, 0x71, 0xfd, 0xa3, 0x48, 0xb1, 0xad, 0xc6,
	0x36, 0x8c, 0x95, 0x9c, 0x03, 0xae, 0x28, 0x0a, 0x5a, 0x4b, 0xcb, 0x0b, 0xed, 0x92, 0xba, 0x5d,
	0xca, 0x8e, 0x80, 0xf6, 0x0b, 0xf4, 0x0b, 0xf4, 0xb5, 0x0f, 0x7d, 0xee, 0x73, 0x3f, 0x40, 0x5f,
	0xfa, 0xd2, 0x4f, 0xd0, 0xaf, 0xd0, 0xef, 0x50, 0x0c, 0xff, 0x2c, 0xc9, 0xdd, 0xf5, 0x26, 0x07,
	0xf4, 0x49, 0x3b, 0x3f, 0x0e, 0x39, 0xc3, 0x99, 0xe1, 0xcc, 0x90, 0x42, 0x1b, 0xd1, 0xf9, 0x1f,
	0x2e, 0x71, 0x92, 0xe4, 0x57, 0xd9, 0xd3, 0x79, 0xc6, 0x38, 0xf3, 0xda, 0xd1, 0x79, 0xf0, 0x3b,
	0x74, 0x7f, 0x94, 0xe2, 0x24, 0x09, 0x31, 0x9d, 0x85, 0x64, 0xc2, 0xb2, 0xc8, 0xf3, 0xd0, 0x0a,
	0x50, 0x7e, 0x6b, 0xb7, 0xb5, 0xd7, 0x0d, 0xc5, 0xb7, 0x77, 0x0f, 0xb5, 0x87, 0x91, 0xdf, 0x16,
	0x48, 0x7b, 0x18, 0x79, 0x1b, 0xa8, 0xf3, 0x06, 0x27, 0x7e, 0x47, 0x00, 0xf0, 0x09, 0xb3, 0x4e,
	0x70, 0x4a, 0xfc, 0x95, 0xdd, 0xd6, 0xde, 0x5a, 0x28, 0xbe, 0x83, 0xd7, 0xe8, 0xee, 0x51, 0x9c,
	0xc6, 0x7c, 0x74, 0xc9, 0xe6, 0x43, 0x4e, 0x52, 0x6f, 0x17, 0xdd, 0xe9, 0xb3, 0x34, 0x65, 0x51,
	0xcc, 0x97, 0xc3, 0x48, 0x49, 0xb0, 0x21, 0xcf, 0x47, 0xb7, 0x8e, 0xc8, 0x05, 0x3f, 0x59, 0xa4,
	0x4a, 0x9a, 0x26, 0x83, 0xbf, 0xb7, 0x11, 0x3a, 0x4d, 0xf0, 0x92, 0x64, 0x43, 0x7a, 0xc1, 0x40,
	0x83, 0xa3, 0xab, 0x44, 0x2d, 0x01, 0x9f, 0x80, 0xbc, 0x7a, 0x3b, 0x57, 0xd3, 0xe0, 0xd3, 0xdb,
	0x41, 0xa8, 0x9f, 0x11, 0xcc, 0xc9, 0x19, 0x8d, 0xdf, 0x2a, 0x65, 0x2d, 0x04, 0x74, 0x3e, 0x60,
	0x49, 0x24, 0x74, 0xee, 0x86, 0xe2, 0x1b, 0x14, 0x18, 0xc4, 0x38, 0x65, 0x34, 0xf2, 0xbb, 0x52,
	0x01, 0x45, 0x7a, 0xcf, 0xd0, 0x07, 0x47, 0x38, 0xe7, 0x83, 0x18, 0x27, 0xcb, 0x31, 0xce, 0x67,
	0x67, 0xf3, 0xb3, 0x98, 0xbe, 0xf5, 0x57, 0x05, 0x57, 0xdd, 0x10, 0xac, 0x3f, 0x9c, 0x30, 0xea,
	0xdf, 0x92, 0x36, 0x81, 0x6f, 0xd0, 0x09, 0x58, 0x8f, 0xd8, 0x94, 0x2d, 0xb8, 0xbf, 0x26, 0x75,
	0x32, 0x88, 0xb7, 0x8d, 0xd6, 0x14, 0x15, 0x53, 0x1f, 0x89, 0x61, 0x03, 0x78, 0x5b, 0x68, 0xf5,
	0x4d, 0x3c, 0x87, 0x8d, 0x6f, 0x88, 0x21, 0x45, 0x81, 0xa4, 0x43, 0x82, 0x23, 0xff, 0x81, 0xdc,
	0x09, 0x7c, 0x07, 0x2f, 0xd0, 0xba, 0xb4, 0xd7, 0x41, 0xc2, 0xce, 0x71, 0xe2, 0x3d, 0x46, 0x77,
	0xfb, 0x8b, 0x2c, 0x23, 0x94, 0x87, 0x2c, 0x21, 0x85, 0xf9, 0x5d, 0x30, 0x78, 0x5e, 0x58, 0x19,
	0x1c, 0x26, 0xfd, 0xde, 0x2a, 0xfc, 0xbe, 0x89, 0xba, 0x7d, 0xb6, 0xa0, 0x5c, 0x59, 0x59, 0x12,
	0xc1, 0x0b, 0x74, 0xcf, 0xcc, 0x39, 0x8a, 0x73, 0xee, 0x05, 0x68, 0x05, 0x7e, 0xfd, 0xd6, 0x6e,
	0x67, 0xef, 0xce, 0xf3, 0x7b, 0x4f, 0xa3, 0xf3, 0xa7, 0x86, 0x23, 0x14, 0x63, 0xc1, 0x3f, 0x5a,
	0x5a, 0x14, 0x88, 0xae, 0x88, 0xf2, 0xd1, 0xad, 0x31, 0x3e, 0x17, 0x8a, 0xaa, 0x48, 0x50, 0x64,
	0x11, 0xa0, 0x1d, 0x2b, 0x40, 0x37, 0x51, 0xf7, 0x88, 0x5c, 0x91, 0x44, 0xf9, 0x52, 0x12, 0xc0,
	0xd9, 0xe3, 0x3c, 0xf3, 0xbb, 0xbb, 0x1d, 0xe0, 0x84, 0x6f, 0xe0, 0x7c, 0xf5, 0xed, 0x22, 0x9e,
	0xfb, 0xab, 0x02, 0x94, 0x04, 0x18, 0x76, 0x98, 0x1f, 0xb1, 0xc9, 0x4c, 0x38, 0xab, 0x1b, 0x2a,
	0x0a, 0xb8, 0x47, 0x1c, 0x73, 0xe2, 0xdf, 0x96, 0xeb, 0x0a, 0xc2, 0x6c, 0x18, 0x34, 0x6f, 0xde,
	0x30, 0x70, 0xa8, 0x0d, 0xef, 0x21, 0xcf, 0x60, 0x87, 0x98, 0x46, 0xe7, 0x8c, 0xcd, 0xc4, 0x6e,
	0x58, 0x42, 0xc4, 0x4c, 0xd8, 0x0d, 0x4b, 0x48, 0xf0, 0xe7, 0x16, 0xda, 0x90, 0xac, 0x2f, 0x31,
	0xe7, 0x09, 0x19, 0x13, 0x9c, 0x82, 0xff, 0x7a, 0x9c, 0xe3, 0xc9, 0xec, 0x98, 0xa4, 0xe7, 0x24,
	0xcb, 0xd5, 0x0c, 0x17, 0xf4, 0x3e, 0x43, 0xf7, 0x06, 0xe4, 0x82, 0xd0, 0x9c, 0x68, 0xb6, 0xb6,
	0x60, 0x2b, 0xa1, 0xde, 0x1e, 0xba, 0xdf, 0xc7, 0xe9, 0x1c, 0xc7, 0x53, 0xaa, 0x19, 0x3b, 0x82,
	0xb1, 0x0c, 0x07, 0x7f, 0x6b, 0xa3, 0x4d, 0xa9, 0x8c, 0x1e, 0x11, 0x07, 0x96, 0x7a, 0x3f, 0x42,
	0x0f, 0x54, 0xec, 0xe8, 0x81, 0xc2, 0x81, 0xd5, 0x01, 0x6f, 0x1f, 0xed, 0x1c, 0x62, 0x3a, 0x5d,
	0xcc, 0xc5, 0x49, 0xc9, 0xd8, 0x1c, 0x4c, 0x19, 0x4f, 0x86, 0x74, 0xc2, 0x52, 0x32, 0x8e, 0x53,
	0xa2, 0xdc, 0xfc, 0x0e, 0xae, 0xea, 0x3a, 0x21, 0xa6, 0x11, 0x4b, 0xad, 0x75, 0x3a, 0x75, 0xeb,
	0x94, 0xb9, 0xbc, 0x27, 0x68, 0x43, 0x72, 0x58, 0xca, 0xcb, 0xe0, 0xa9, 0xe0, 0x5e, 0x80, 0xd6,
	0x21, 0xca, 0x46, 0x24, 0x8b, 0x71, 0x32, 0xd4, 0x99, 0xc1, 0xc1, 0x82, 0x67, 0x3a, 0x26, 0xf4,
	0x3c, 0x91, 0x7e, 0xca, 0x86, 0xb1, 0x90, 0xe0, 0x2b, 0x1d, 0x0f, 0x1a, 0x13, 0x91, 0xf4, 0x99,
	0x13, 0x49, 0x9e, 0x89, 0x24, 0xcd, 0xa5, 0xa2, 0xe9, 0x04, 0x7d, 0xe4, 0xe2, 0xb6, 0xa5, 0x44,
	0x3c, 0x73, 0x92, 0x16, 0x72, 0x15, 0x05, 0xa7, 0x0a, 0xbe, 0xac, 0xfc, 0xaa, 0xc8, 0x60, 0x8c,
	0x76, 0x6e, 0x5e, 0x4f, 0x68, 0xf6, 0xdc, 0xd1, 0x6c, 0xa7, 0xaa, 0x99, 0x3d, 0xe3, 0x26, 0x2d,
	0x6d, 0x3f, 0xfc, 0x3f, 0xb4, 0xb4, 0xd7, 0x7b, 0x3f, 0x2d, 0xed, 0x19, 0x4a, 0xcb, 0x9f, 0xa0,
	0x07, 0x92, 0xe7, 0x84, 0xf1, 0xf8, 0x62, 0x29, 0x0e, 0x39, 0xb8, 0xef, 0x98, 0x45, 0x8b, 0x84,
	0x8c, 0x97, 0x73, 0xa2, 0xdd, 0x67, 0x90, 0xe0, 0x25, 0x7a, 0x58, 0x99, 0x24, 0x34, 0xf8, 0xa1,
	0xa3, 0xc1, 0x43, 0xa3, 0x81, 0xc5, 0xa8, 0x04, 0x9f, 0xeb, 0x73, 0x7e, 0x8c, 0xe3, 0x44, 0x1d,
	0xab, 0x2d, 0xb4, 0x0a, 0xa7, 0xc7, 0x18, 0x45, 0x52, 0xde, 0x97, 0x68, 0x0b, 0x82, 0x79, 0x44,
	0x68, 0x64, 0xe6, 0x58, 0x07, 0xe7, 0x86, 0xd1, 0xe0, 0x9f, 0x45, 0xe1, 0x04, 0xa8, 0x92, 0x67,
	0x3d, 0xb4, 0x22, 0x36, 0x28, 0x17, 0x11, 0xdf, 0x90, 0xf5, 0xc6, 0x31, 0x4f, 0xe4, 0x51, 0x5a,
	0x0b, 0x25, 0x01, 0x5e, 0xe9, 0x33, 0xca, 0x09, 0xe5, 0xaa, 0xca, 0x6b, 0xd2, 0xfb, 0x08, 0xdd,
	0x06, 0xc1, 0xa2, 0xcc, 0xca, 0xb3, 0x51, 0xd0, 0x45, 0xda, 0xba, 0x94, 0xbe, 0xcd, 0x55, 0xde,
	0x75, 0x41, 0x48, 0x5b, 0x06, 0x38, 0x59, 0xa4, 0xb9, 0x7f, 0x4b, 0xa6, 0x2d, 0x17, 0x95, 0x79,
	0x3a, 0x84, 0x52, 0x77, 0x5b, 0xe7, 0x69, 0xa0, 0x40, 0xca, 0x30, 0x3f, 0x20, 0x5c, 0xb2, 0x93,
	0xc8, 0xbf, 0x23, 0x8b, 0x9b, 0x03, 0x6a, 0x3d, 0x09, 0x18, 0x77, 0xdd, 0xe8, 0x09, 0x34, 0xb8,
	0x5b, 0x7e, 0x8b, 0x36, 0xe6, 0xae, 0xd8, 0xa0, 0x85, 0x98, 0x9c, 0x0f, 0x56, 0x6c, 0xce, 0xf9,
	0xc0, 0xa1, 0x1c, 0x1c, 0xba, 0x89, 0x7c, 0x84, 0xaf, 0x48, 0x9d, 0x07, 0x46, 0x71, 0x54, 0x78,
	0x00, 0xbe, 0x85, 0xa6, 0xf8, 0xca, 0xce, 0x67, 0x05, 0x1d, 0xfc, 0x46, 0xe7, 0x63, 0xb3, 0xa6,
	0xd0, 0x67, 0xcf, 0xd1, 0x67, 0xd3, 0xe8, 0x63, 0xf8, 0x94, 0x56, 0x45, 0x6b, 0x30, 0xc6, 0x09,
	0xf8, 0xaf, 0xa6, 0xcc, 0xcb, 0x6a, 0xda, 0xb6, 0xaa, 0x69, 0xf0, 0x73, 0xbd, 0x17, 0x39, 0x4b,
	0xc8, 0x7c, 0xec, 0xc8, 0xdc, 0x30, 0x32, 0x25, 0x8f, 0x92, 0x97, 0xea, 0xf3, 0x35, 0x66, 0xd7,
	0x24, 0x7b, 0x47, 0x9c, 0x7b, 0x68, 0xe5, 0x35, 0x59, 0xe6, 0xda, 0x1c, 0xf0, 0x0d, 0xa5, 0x06,
	0xa2, 0xfb, 0x80, 0xf0, 0x13, 0x72, 0xfd, 0x9a, 0x2c, 0x2d, 0xbb, 0x54, 0x07, 0x82, 0x4f, 0xd0,
	0x1d, 0x4b, 0x5c, 0x79, 0x77, 0xc1, 0x97, 0xe8, 0xbe, 0x35, 0x2c, 0xb6, 0xf1, 0x3d, 0x67, 0x1b,
	0xf7, 0xad, 0x6d, 0x00, 0x8b, 0xda, 0xc5, 0x40, 0x9f, 0xa3, 0x41, 0x86, 0xaf, 0x8b, 0x73, 0xd3,
	0xb2, 0xce, 0x4d, 0x80, 0xd6, 0x65, 0xbd, 0xc1, 0xd7, 0xd6, 0xc1, 0x74, 0x30, 0x13, 0x47, 0x80,
	0x34, 0xc7, 0x11, 0x70, 0x28, 0xd9, 0x63, 0x3d, 0x0b, 0x9a, 0x54, 0xe8, 0x1d, 0xa0, 0x80, 0xc3,
	0xba, 0x21, 0xb9, 0xc8, 0x48, 0x7e, 0x29, 0xc4, 0x49, 0x55, 0xca, 0xb0, 0xdb, 0x53, 0x77, 0xec,
	0x9e, 0xfa, 0xaf, 0x45, 0x0b, 0x06, 0x2d, 0x7a, 0x25, 0x0c, 0x54, 0xc7, 0xbb, 0x9f, 0x11, 0x62,
	0x8b, 0x69, 0x9b, 0x8e, 0xb7, 0x34, 0xa4, 0x67, 0xf4, 0x16, 0x9c, 0xd9, 0x33, 0x3a, 0x66, 0x46,
	0x69, 0x48, 0x14, 0xc9, 0x45, 0x96, 0x01, 0x5c, 0x14, 0x60, 0x0b, 0x31, 0xe6, 0x02, 0x0d, 0x9b,
	0xcd, 0x05, 0x1c, 0xca, 0x5c, 0x99, 0x3d, 0xab, 0xb6, 0x93, 0x85, 0xe3, 0xae, 0xc6, 0x8a, 0x0e,
	0xd3, 0x42, 0x6c, 0xa3, 0x75, 0x9c, 0x8b, 0x08, 0xc4, 0xad, 0xe0, 0xd3, 0xda, 0x2a, 0xca, 0x94,
	0x73, 0xbd, 0x4a, 0x73, 0x39, 0xd7, 0x5c, 0x4a, 0xe3, 0xff, 0xb6, 0x75, 0xd0, 0xf6, 0x32, 0x42,
	0x31, 0x24, 0xc4, 0x90, 0xcc, 0xe1, 0xaa, 0x12, 0x7d, 0x1d, 0x53, 0x50, 0x43, 0xea, 0x5e, 0x42,
	0x21, 0x0c, 0x34, 0x72, 0xc4, 0x72, 0x62, 0x4a, 0x66, 0x19, 0x16, 0xad, 0xec, 0x84, 0x65, 0xda,
	0x1b, 0x92, 0x80, 0xf9, 0x67, 0xf3, 0x08, 0x73, 0x22, 0x48, 0xe1, 0x2d, 0xb9, 0xad, 0x32, 0x0c,
	0x9c, 0xc7, 0x98, 0x43, 0x1e, 0x55, 0xad, 0xbc, 0xee, 0x83, 0xca, 0x30, 0xe8, 0x7e, 0x18, 0xe7,
	0x9c, 0x65, 0xcb, 0xb1, 0x68, 0xbc, 0x66, 0xea, 0x92, 0x54, 0x42, 0x81, 0x6f, 0x3f, 0xce, 0xc4,
	0xe9, 0x1d, 0xc7, 0x93, 0x19, 0xe1, 0xaa, 0xf9, 0x2e, 0xa1, 0xba, 0xf2, 0x49, 0x2a, 0xb7, 0x03,
	0xeb, 0xb6, 0xa9, 0x7c, 0xd5, 0x51, 0x99, 0xee, 0x55, 0xcb, 0xb6, 0xa6, 0xd3, 0xbd, 0x6a, 0xd7,
	0xbe, 0xd5, 0xe6, 0x96, 0xfd, 0xff, 0x0b, 0xf4, 0x70, 0x9c, 0xce, 0x45, 0x2a, 0x25, 0x17, 0x7c,
	0x94, 0x30, 0xf7, 0x92, 0x54, 0x3f, 0x08, 0x69, 0x69, 0x9c, 0xce, 0x35, 0xe8, 0xc4, 0x52, 0x75,
	0x20, 0x98, 0xa2, 0x47, 0xca, 0xc3, 0x13, 0x1e, 0x5f, 0x91, 0x11, 0xc7, 0x53, 0xa2, 0x72, 0xe1,
	0xfb, 0x1f, 0xe6, 0x00, 0xad, 0x1f, 0x10, 0x7e, 0xca, 0x62, 0xca, 0xf3, 0x01, 0x5e, 0xea, 0x14,
	0x63, 0x63, 0xc1, 0x42, 0xa7, 0x5b, 0x4b, 0x50, 0x6d, 0xbe, 0x12, 0x97, 0x00, 0xda, 0xbf, 0xc4,
	0x49, 0x42, 0xe8, 0xd4, 0x0e, 0x9e, 0x12, 0x0c, 0x62, 0x4f, 0x17, 0xd9, 0xe4, 0x12, 0xe7, 0x24,
	0x32, 0x67, 0xc2, 0xc1, 0x4c, 0x43, 0x64, 0x89, 0x6d, 0x6e, 0x88, 0x2c, 0x46, 0x75, 0x0c, 0xfe,
	0xd3, 0xd6, 0xa7, 0x68, 0x3f, 0x8b, 0x09, 0x8d, 0xcc, 0x55, 0x43, 0x1a, 0x62, 0xc2, 0xd2, 0x94,
	0xd0, 0xc8, 0xb2, 0x50, 0x75, 0x40, 0x67, 0xa1, 0x97, 0x2c, 0xcf, 0x6f, 0xc8, 0x5b, 0xa5, 0x21,
	0x58, 0x5f, 0xca, 0x83, 0x01, 0x7d, 0xed, 0x54, 0xf5, 0xa5, 0x32, 0x00, 0xeb, 0x1b, 0xf0, 0x70,
	0x7e, 0x4a, 0xb2, 0x89, 0x6e, 0x8a, 0xba, 0x61, 0xdd, 0x90, 0xf7, 0x1c, 0x6d, 0xca, 0x6b, 0x1a,
	0xc0, 0x72, 0x7f, 0xc2, 0x22, 0xf2, 0x62, 0x5a, 0x3b, 0xe6, 0x3d, 0x45, 0x9e, 0x2a, 0x6d, 0x23,
	0x8e, 0xd3, 0x98, 0x62, 0xb1, 0x09, 0x79, 0x92, 0x6a, 0x46, 0xc0, 0x45, 0xbd, 0x3c, 0x8f, 0x73,
	0x1d, 0xb9, 0xf2, 0x2c, 0x39, 0x58, 0xf0, 0x8d, 0x2e, 0xfc, 0x52, 0x49, 0x38, 0x21, 0xc5, 0x61,
	0x96, 0xe6, 0x2c, 0xe8, 0x42, 0x7e, 0x7c, 0x45, 0x64, 0x68, 0x59, 0x46, 0xac, 0x19, 0x31, 0xed,
	0x81, 0x5c, 0xbb, 0xb9, 0x3d, 0x90, 0x3c, 0x45, 0xfb, 0xfd, 0xd0, 0x41, 0xb5, 0x33, 0x9b, 0xd4,
	0x0b, 0x7e, 0x8b, 0x3e, 0xac, 0x9d, 0x24, 0xe4, 0x7e, 0xe1, 0xc8, 0xfd, 0xb0, 0x22, 0x57, 0x33,
	0x2b, 0x05, 0xbe, 0xd0, 0x1d, 0x81, 0x1c, 0xee, 0xe5, 0xb3, 0x46, 0xd1, 0xbf, 0x42, 0x1f, 0x94,
	0xd8, 0x85, 0xd0, 0x1f, 0x38, 0x42, 0x3f, 0x28, 0x0b, 0xed, 0xe5, 0x33, 0x25, 0x8e, 0xba, 0x96,
	0x02, 0xbf, 0xcb, 0xdb, 0x06, 0xcd, 0x39, 0xc9, 0x4e, 0x59, 0x6e, 0x6e, 0x1b, 0x1a, 0xf1, 0xb6,
	0xd1, 0x9a, 0xa2, 0x8a, 0x14, 0x63, 0x00, 0x6b, 0xf4, 0x70, 0xae, 0xe2, 0xd6, 0x00, 0xa6, 0x61,
	0x34, 0xf2, 0x9a, 0x1b, 0x46, 0xc3, 0xa7, 0x34, 0xfe, 0xca, 0xb4, 0x7e, 0xf9, 0xec, 0xbb, 0xe6,
	0xac, 0xe0, 0x50, 0x77, 0x19, 0x30, 0xbb, 0xae, 0xd9, 0x7c, 0x83, 0x93, 0x85, 0x0e, 0x2d, 0x49,
	0x98, 0x87, 0x97, 0x4e, 0xed, 0xc3, 0x0b, 0xac, 0xd4, 0xdc, 0x0d, 0x00, 0x87, 0xd2, 0xfe, 0x71,
	0x91, 0x53, 0x62, 0x1a, 0xe7, 0x97, 0x24, 0xaa, 0xd3, 0x23, 0x18, 0xa0, 0xad, 0x2a, 0x97, 0x90,
	0xf1, 0xc4, 0x91, 0xb1, 0x65, 0xd9, 0xc9, 0xe2, 0x54, 0xb2, 0x7a, 0x3a, 0xc9, 0x0f, 0x70, 0x2c,
	0x1f, 0x03, 0x7b, 0x49, 0x22, 0xbe, 0xa1, 0xdc, 0xf5, 0x59, 0x3a, 0x4f, 0x08, 0x27, 0x80, 0x17,
	0xc2, 0x4b, 0x68, 0x70, 0x82, 0x3e, 0xbe, 0x61, 0x09, 0xa1, 0xcd, 0x8f, 0x1d, 0x6d, 0x3e, 0xb6,
	0xda, 0xc5, 0x32, 0xbb, 0x52, 0xe9, 0xf7, 0x3a, 0x5c, 0x5f, 0xbd, 0x9d, 0x27, 0x2c, 0xfb, 0xee,
	0x35, 0x67, 0x1b, 0xad, 0xa9, 0xf7, 0x1c, 0x13, 0x7b, 0x05, 0x10, 0xfc, 0xab, 0x8d, 0xee, 0x3a,
	0xeb, 0x57, 0x3c, 0xbc, 0x85, 0x56, 0xd5, 0x86, 0xe5, 0x64, 0x45, 0xd5, 0xfb, 0x58, 0x74, 0x34,
	0x2c, 0x21, 0x70, 0x5d, 0xcf, 0xfb, 0x98, 0x8e, 0xc4, 0xa3, 0x9e, 0x78, 0x99, 0x2a, 0xc1, 0x9a,
	0x13, 0x4a, 0x99, 0xe6, 0xec, 0x1a, 0x4e, 0x0b, 0xf6, 0x9e, 0xa0, 0x0d, 0x99, 0x01, 0x5f, 0x80,
	0x68, 0x79, 0xb7, 0x95, 0x99, 0xb4, 0x82, 0x03, 0x2f, 0x5c, 0xf8, 0x1c, 0x5e, 0x99, 0x4b, 0x2b,
	0x38, 0x58, 0x66, 0xc4, 0x71, 0xc6, 0xad, 0x66, 0xc4, 0x00, 0xd0, 0x43, 0xca, 0xd5, 0x73, 0x7f,
	0x4d, 0x36, 0xde, 0x8a, 0xb4, 0x9e, 0x1b, 0x91, 0xfd, 0xdc, 0x18, 0xfc, 0x42, 0x57, 0x6e, 0x65,
	0x4a, 0xe1, 0xf0, 0xef, 0x3b, 0x0e, 0x7f, 0x60, 0x1c, 0xae, 0x98, 0x94, 0x9b, 0xff, 0xdd, 0xd2,
	0x61, 0xae, 0xf0, 0x11, 0xf4, 0x5a, 0x96, 0xf1, 0x5b, 0xf5, 0xc6, 0x6f, 0xbf, 0xc3, 0xf8, 0x9d,
	0xf7, 0x36, 0xfe, 0x4a, 0xbd, 0xf1, 0x1d, 0x23, 0x75, 0x1b, 0x8c, 0xb4, 0xea, 0x18, 0xc9, 0x1c,
	0x48, 0x7b, 0x3f, 0xcd, 0x07, 0xd2, 0xe6, 0x54, 0x66, 0x99, 0xe9, 0xe8, 0x1f, 0x91, 0x2b, 0x42,
	0x45, 0xc7, 0x11, 0xf3, 0x25, 0xe4, 0x5b, 0xfd, 0x6d, 0x1e, 0xe7, 0x0c, 0x72, 0x43, 0x56, 0xda,
	0x41, 0x28, 0x24, 0xd7, 0x38, 0x8b, 0xec, 0x7f, 0x14, 0x0c, 0x12, 0xec, 0xeb, 0xd3, 0xef, 0x08,
	0x13, 0x3a, 0x7f, 0xee, 0xe8, 0xfc, 0xc8, 0xba, 0x08, 0xd8, 0xac, 0x4a, 0xe9, 0x97, 0xc5, 0xdb,
	0xfd, 0x22, 0x8e, 0x48, 0x0e, 0x46, 0x12, 0x5f, 0x85, 0xaa, 0x9a, 0x84, 0x91, 0x11, 0xe1, 0x42,
	0x1d, 0xf5, 0x54, 0xa6, 0x48, 0x53, 0x8f, 0xe5, 0x1a, 0xcd, 0xf5, 0x58, 0xf2, 0x28, 0xe9, 0x7f,
	0x44, 0xbe, 0xd3, 0x83, 0x5d, 0x62, 0x7e, 0x46, 0x33, 0x82, 0xa3, 0xa1, 0x28, 0xc9, 0x12, 0x35,
	0x75, 0x51, 0xd3, 0xa2, 0x86, 0x91, 0x3c, 0xc7, 0x53, 0xe1, 0x4d, 0x79, 0xd7, 0xb4, 0x10, 0xfd,
	0x0f, 0x44, 0x81, 0x28, 0x03, 0xba, 0x60, 0x70, 0x8a, 0xb6, 0x6f, 0x92, 0x2e, 0xf6, 0xf0, 0xcc,
	0xd9, 0xc3, 0x76, 0xb9, 0x6a, 0xd9, 0xfc, 0x6a, 0x3f, 0x7f, 0x69, 0xa1, 0x4f, 0xea, 0x59, 0x94,
	0x54, 0x08, 0x66, 0xf5, 0x74, 0x53, 0xe8, 0x06, 0x9b, 0xeb, 0x84, 0x65, 0x18, 0xec, 0xad, 0x08,
	0x61, 0xef, 0xf5, 0x50, 0x93, 0xfa, 0x71, 0xc9, 0x79, 0xb2, 0xd1, 0x1d, 0xa9, 0x79, 0xb6, 0x5a,
	0xb1, 0x9f, 0xad, 0x82, 0x6f, 0xd0, 0xa7, 0x8d, 0x8a, 0x89, 0x0d, 0xff, 0xd4, 0xd9, 0xf0, 0xa7,
	0x37, 0x6f, 0x58, 0x4d, 0x52, 0xbb, 0xde, 0xd5, 0xb5, 0xf2, 0x10, 0x6c, 0x51, 0x73, 0x07, 0x36,
	0x37, 0x56, 0xcd, 0xd1, 0x7c, 0x63, 0xd5, 0x5c, 0x6a, 0xfd, 0x5f, 0x6b, 0x9b, 0x8d, 0x16, 0x31,
	0xef, 0xc1, 0x11, 0xa8, 0x24, 0xfe, 0x6d, 0xb4, 0x26, 0x06, 0xac, 0xce, 0xd1, 0x00, 0xa6, 0x8d,
	0x2a, 0x16, 0x68, 0x6e, 0xa3, 0x0a, 0x36, 0xa5, 0xc0, 0x9f, 0xb4, 0x02, 0x5f, 0xb3, 0x2c, 0x11,
	0x66, 0xd0, 0x0f, 0x30, 0xf0, 0x6d, 0x15, 0x34, 0x07, 0xd3, 0x3c, 0xa7, 0x8b, 0x24, 0x29, 0x3f,
	0xd2, 0x68, 0x4c, 0xf3, 0x1c, 0xe7, 0xd3, 0x21, 0x8d, 0x88, 0x3e, 0xe9, 0x0e, 0x16, 0xfc, 0xac,
	0xb8, 0x65, 0x51, 0xb6, 0xa0, 0x13, 0x92, 0x42, 0xa3, 0xaf, 0x26, 0x8e, 0xdc, 0x3b, 0x8a, 0x83,
	0x05, 0xbf, 0x2c, 0xda, 0x47, 0xb8, 0xe6, 0x0e, 0x32, 0x7c, 0xdd, 0xaf, 0x33, 0xde, 0x16, 0x5a,
	0x85, 0x31, 0x52, 0x54, 0x4d, 0x49, 0x99, 0x1c, 0xe3, 0x4c, 0x6f, 0xce, 0x31, 0x0e, 0x6b, 0xd1,
	0x15, 0xdd, 0x33, 0x0f, 0x83, 0x03, 0xcc, 0x31, 0x5c, 0x11, 0xe1, 0x57, 0xe8, 0xb0, 0x1e, 0x8a,
	0xef, 0x60, 0x0f, 0x79, 0xe2, 0x0d, 0x6c, 0x3f, 0x9e, 0x5e, 0xf2, 0x46, 0xce, 0xcf, 0xd1, 0x23,
	0xf9, 0x5a, 0x86, 0xe9, 0x2c, 0xa6, 0x53, 0x90, 0x21, 0x85, 0xe7, 0xde, 0x06, 0xea, 0x40, 0x46,
	0x90, 0x7f, 0x58, 0xc1, 0x67, 0xc0, 0xd0, 0x7d, 0xf1, 0xce, 0x31, 0x22, 0x38, 0x67, 0x54, 0xac,
	0xf9, 0x04, 0x6d, 0x88, 0x87, 0x32, 0xbc, 0x0c, 0x49, 0x4e, 0x6c, 0xff, 0x55, 0x70, 0x7d, 0xc3,
	0x93, 0xb3, 0x0d, 0xbb, 0x75, 0xc3, 0x2b, 0x0d, 0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x96, 0x52,
	0x85, 0xcb, 0xff, 0x1e, 0x00, 0x00,
}
