// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db_hallsvr.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db_hallsvr.proto

It has these top-level messages:
	SmallRankRecord
	LimitShopItem
	PlayerInfo
	PlayerGlobal
	PlayerItem
	PlayerItemList
	PlayerRole
	PlayerRoleList
	PlayerBattleTeam
	PlayerCampaignCommon
	PlayerCampaign
	PlayerCampaignList
	PlayerCampaignStaticIncome
	PlayerCampaignStaticIncomeList
	PlayerCampaignRandomIncome
	PlayerCampaignRandomIncomeList
	PlayerNotifyState
	PlayerNotifyStateList
	PlayerShopItem
	PlayerShopItemList
	PlayerShopLimitedInfo
	PlayerShopLimitedInfoList
	PlayerMailCommon
	PlayerMail
	PlayerMailList
	PlayerBattleSave
	PlayerBattleSaveList
	PlayerDialyTask
	PlayerDialyTaskList
	PlayerAchieve
	PlayerAchieveList
	PlayerFinishedAchieve
	PlayerFinishedAchieveList
	PlayerDailyTaskWholeDaily
	PlayerDailyTaskWholeDailyList
	PlayerSevenActivity
	PlayerSevenActivityList
	PlayerGuides
	PlayerGuidesList
	PlayerFriendRelative
	PlayerFriend
	PlayerFriendList
	PlayerFriendReq
	PlayerFriendReqList
	PlayerFriendPoint
	PlayerFriendPointList
	PlayerFriendChatUnreadId
	PlayerFriendChatUnreadIdList
	PlayerFriendChatUnreadMessage
	PlayerFriendChatUnreadMessageList
	PlayerChaterOpenRequest
	PlayerHandbookItem
	PlayerHandbookItemList
	PlayerHeadItem
	PlayerHeadItemList
	PlayerSuitAward
	PlayerSuitAwardList
	PlayerWorldChat
	PlayerAnouncement
	PlayerFirstDrawCard
	PlayerFirstDrawCardList
	BattleSaveData
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SmallRankRecord struct {
	Rank             *int32  `protobuf:"varint,1,opt,name=Rank" json:"Rank,omitempty"`
	Id               *int32  `protobuf:"varint,2,opt,name=Id" json:"Id,omitempty"`
	Val              *int32  `protobuf:"varint,3,opt,name=Val" json:"Val,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SmallRankRecord) Reset()                    { *m = SmallRankRecord{} }
func (m *SmallRankRecord) String() string            { return proto.CompactTextString(m) }
func (*SmallRankRecord) ProtoMessage()               {}
func (*SmallRankRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SmallRankRecord) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *SmallRankRecord) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SmallRankRecord) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

func (m *SmallRankRecord) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type LimitShopItem struct {
	CommodityId      *int32 `protobuf:"varint,1,opt,name=CommodityId" json:"CommodityId,omitempty"`
	LeftNum          *int32 `protobuf:"varint,2,opt,name=LeftNum" json:"LeftNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LimitShopItem) Reset()                    { *m = LimitShopItem{} }
func (m *LimitShopItem) String() string            { return proto.CompactTextString(m) }
func (*LimitShopItem) ProtoMessage()               {}
func (*LimitShopItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LimitShopItem) GetCommodityId() int32 {
	if m != nil && m.CommodityId != nil {
		return *m.CommodityId
	}
	return 0
}

func (m *LimitShopItem) GetLeftNum() int32 {
	if m != nil && m.LeftNum != nil {
		return *m.LeftNum
	}
	return 0
}

type PlayerInfo struct {
	Lvl                 *int32  `protobuf:"varint,1,opt,name=Lvl" json:"Lvl,omitempty"`
	Exp                 *int32  `protobuf:"varint,2,opt,name=Exp" json:"Exp,omitempty"`
	CreateUnix          *int32  `protobuf:"varint,3,opt,name=CreateUnix" json:"CreateUnix,omitempty"`
	Gold                *int32  `protobuf:"varint,4,opt,name=Gold" json:"Gold,omitempty"`
	Diamond             *int32  `protobuf:"varint,5,opt,name=Diamond" json:"Diamond,omitempty"`
	LastDialyTaskUpUinx *int32  `protobuf:"varint,6,opt,name=LastDialyTaskUpUinx" json:"LastDialyTaskUpUinx,omitempty"`
	Icon                *string `protobuf:"bytes,7,opt,name=Icon" json:"Icon,omitempty"`
	LastLogout          *int32  `protobuf:"varint,9,opt,name=LastLogout" json:"LastLogout,omitempty"`
	LastLogin           *int32  `protobuf:"varint,10,opt,name=LastLogin" json:"LastLogin,omitempty"`
	VipLvl              *int32  `protobuf:"varint,16,opt,name=VipLvl" json:"VipLvl,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerInfo) GetLvl() int32 {
	if m != nil && m.Lvl != nil {
		return *m.Lvl
	}
	return 0
}

func (m *PlayerInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *PlayerInfo) GetCreateUnix() int32 {
	if m != nil && m.CreateUnix != nil {
		return *m.CreateUnix
	}
	return 0
}

func (m *PlayerInfo) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *PlayerInfo) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *PlayerInfo) GetLastDialyTaskUpUinx() int32 {
	if m != nil && m.LastDialyTaskUpUinx != nil {
		return *m.LastDialyTaskUpUinx
	}
	return 0
}

func (m *PlayerInfo) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *PlayerInfo) GetLastLogout() int32 {
	if m != nil && m.LastLogout != nil {
		return *m.LastLogout
	}
	return 0
}

func (m *PlayerInfo) GetLastLogin() int32 {
	if m != nil && m.LastLogin != nil {
		return *m.LastLogin
	}
	return 0
}

func (m *PlayerInfo) GetVipLvl() int32 {
	if m != nil && m.VipLvl != nil {
		return *m.VipLvl
	}
	return 0
}

type PlayerGlobal struct {
	CurrentRoleId    *int32 `protobuf:"varint,1,opt,name=CurrentRoleId" json:"CurrentRoleId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerGlobal) Reset()                    { *m = PlayerGlobal{} }
func (m *PlayerGlobal) String() string            { return proto.CompactTextString(m) }
func (*PlayerGlobal) ProtoMessage()               {}
func (*PlayerGlobal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PlayerGlobal) GetCurrentRoleId() int32 {
	if m != nil && m.CurrentRoleId != nil {
		return *m.CurrentRoleId
	}
	return 0
}

type PlayerItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Count            *int32 `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerItem) Reset()                    { *m = PlayerItem{} }
func (m *PlayerItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerItem) ProtoMessage()               {}
func (*PlayerItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerItem) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type PlayerItemList struct {
	List             []*PlayerItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerItemList) Reset()                    { *m = PlayerItemList{} }
func (m *PlayerItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerItemList) ProtoMessage()               {}
func (*PlayerItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerItemList) GetList() []*PlayerItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerRole struct {
	Id               *int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	TableId          *int32  `protobuf:"varint,2,opt,name=TableId" json:"TableId,omitempty"`
	Rank             *int32  `protobuf:"varint,3,opt,name=Rank" json:"Rank,omitempty"`
	Level            *int32  `protobuf:"varint,4,opt,name=Level" json:"Level,omitempty"`
	Attr             []int32 `protobuf:"varint,5,rep,name=Attr" json:"Attr,omitempty"`
	Equip            []int32 `protobuf:"varint,6,rep,name=Equip" json:"Equip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerRole) Reset()                    { *m = PlayerRole{} }
func (m *PlayerRole) String() string            { return proto.CompactTextString(m) }
func (*PlayerRole) ProtoMessage()               {}
func (*PlayerRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlayerRole) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerRole) GetTableId() int32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *PlayerRole) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *PlayerRole) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerRole) GetAttr() []int32 {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *PlayerRole) GetEquip() []int32 {
	if m != nil {
		return m.Equip
	}
	return nil
}

type PlayerRoleList struct {
	List             []*PlayerRole `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerRoleList) Reset()                    { *m = PlayerRoleList{} }
func (m *PlayerRoleList) String() string            { return proto.CompactTextString(m) }
func (*PlayerRoleList) ProtoMessage()               {}
func (*PlayerRoleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PlayerRoleList) GetList() []*PlayerRole {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerBattleTeam struct {
	AttackMembers    []int32 `protobuf:"varint,1,rep,name=AttackMembers" json:"AttackMembers,omitempty"`
	DefenseMembers   []int32 `protobuf:"varint,2,rep,name=DefenseMembers" json:"DefenseMembers,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerBattleTeam) Reset()                    { *m = PlayerBattleTeam{} }
func (m *PlayerBattleTeam) String() string            { return proto.CompactTextString(m) }
func (*PlayerBattleTeam) ProtoMessage()               {}
func (*PlayerBattleTeam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PlayerBattleTeam) GetAttackMembers() []int32 {
	if m != nil {
		return m.AttackMembers
	}
	return nil
}

func (m *PlayerBattleTeam) GetDefenseMembers() []int32 {
	if m != nil {
		return m.DefenseMembers
	}
	return nil
}

type PlayerCampaignCommon struct {
	CurrentCampaignId              *int32 `protobuf:"varint,1,opt,name=CurrentCampaignId" json:"CurrentCampaignId,omitempty"`
	HangupLastDropStaticIncomeTime *int32 `protobuf:"varint,2,opt,name=HangupLastDropStaticIncomeTime" json:"HangupLastDropStaticIncomeTime,omitempty"`
	HangupLastDropRandomIncomeTime *int32 `protobuf:"varint,3,opt,name=HangupLastDropRandomIncomeTime" json:"HangupLastDropRandomIncomeTime,omitempty"`
	HangupCampaignId               *int32 `protobuf:"varint,4,opt,name=HangupCampaignId" json:"HangupCampaignId,omitempty"`
	XXX_unrecognized               []byte `json:"-"`
}

func (m *PlayerCampaignCommon) Reset()                    { *m = PlayerCampaignCommon{} }
func (m *PlayerCampaignCommon) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignCommon) ProtoMessage()               {}
func (*PlayerCampaignCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PlayerCampaignCommon) GetCurrentCampaignId() int32 {
	if m != nil && m.CurrentCampaignId != nil {
		return *m.CurrentCampaignId
	}
	return 0
}

func (m *PlayerCampaignCommon) GetHangupLastDropStaticIncomeTime() int32 {
	if m != nil && m.HangupLastDropStaticIncomeTime != nil {
		return *m.HangupLastDropStaticIncomeTime
	}
	return 0
}

func (m *PlayerCampaignCommon) GetHangupLastDropRandomIncomeTime() int32 {
	if m != nil && m.HangupLastDropRandomIncomeTime != nil {
		return *m.HangupLastDropRandomIncomeTime
	}
	return 0
}

func (m *PlayerCampaignCommon) GetHangupCampaignId() int32 {
	if m != nil && m.HangupCampaignId != nil {
		return *m.HangupCampaignId
	}
	return 0
}

type PlayerCampaign struct {
	CampaignId       *int32 `protobuf:"varint,1,opt,name=CampaignId" json:"CampaignId,omitempty"`
	Stars            *int32 `protobuf:"varint,2,opt,name=Stars" json:"Stars,omitempty"`
	LastFinishedTime *int32 `protobuf:"varint,3,opt,name=LastFinishedTime" json:"LastFinishedTime,omitempty"`
	TopScore         *int32 `protobuf:"varint,4,opt,name=TopScore" json:"TopScore,omitempty"`
	PlayedCount      *int32 `protobuf:"varint,6,opt,name=PlayedCount" json:"PlayedCount,omitempty"`
	PassCount        *int32 `protobuf:"varint,7,opt,name=PassCount" json:"PassCount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerCampaign) Reset()                    { *m = PlayerCampaign{} }
func (m *PlayerCampaign) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaign) ProtoMessage()               {}
func (*PlayerCampaign) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PlayerCampaign) GetCampaignId() int32 {
	if m != nil && m.CampaignId != nil {
		return *m.CampaignId
	}
	return 0
}

func (m *PlayerCampaign) GetStars() int32 {
	if m != nil && m.Stars != nil {
		return *m.Stars
	}
	return 0
}

func (m *PlayerCampaign) GetLastFinishedTime() int32 {
	if m != nil && m.LastFinishedTime != nil {
		return *m.LastFinishedTime
	}
	return 0
}

func (m *PlayerCampaign) GetTopScore() int32 {
	if m != nil && m.TopScore != nil {
		return *m.TopScore
	}
	return 0
}

func (m *PlayerCampaign) GetPlayedCount() int32 {
	if m != nil && m.PlayedCount != nil {
		return *m.PlayedCount
	}
	return 0
}

func (m *PlayerCampaign) GetPassCount() int32 {
	if m != nil && m.PassCount != nil {
		return *m.PassCount
	}
	return 0
}

type PlayerCampaignList struct {
	List             []*PlayerCampaign `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PlayerCampaignList) Reset()                    { *m = PlayerCampaignList{} }
func (m *PlayerCampaignList) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignList) ProtoMessage()               {}
func (*PlayerCampaignList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PlayerCampaignList) GetList() []*PlayerCampaign {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerCampaignStaticIncome struct {
	ItemId           *int32 `protobuf:"varint,1,opt,name=ItemId" json:"ItemId,omitempty"`
	ItemNum          *int32 `protobuf:"varint,2,opt,name=ItemNum" json:"ItemNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerCampaignStaticIncome) Reset()                    { *m = PlayerCampaignStaticIncome{} }
func (m *PlayerCampaignStaticIncome) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignStaticIncome) ProtoMessage()               {}
func (*PlayerCampaignStaticIncome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PlayerCampaignStaticIncome) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *PlayerCampaignStaticIncome) GetItemNum() int32 {
	if m != nil && m.ItemNum != nil {
		return *m.ItemNum
	}
	return 0
}

type PlayerCampaignStaticIncomeList struct {
	List             []*PlayerCampaignStaticIncome `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *PlayerCampaignStaticIncomeList) Reset()                    { *m = PlayerCampaignStaticIncomeList{} }
func (m *PlayerCampaignStaticIncomeList) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignStaticIncomeList) ProtoMessage()               {}
func (*PlayerCampaignStaticIncomeList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PlayerCampaignStaticIncomeList) GetList() []*PlayerCampaignStaticIncome {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerCampaignRandomIncome struct {
	ItemId           *int32 `protobuf:"varint,1,opt,name=ItemId" json:"ItemId,omitempty"`
	ItemNum          *int32 `protobuf:"varint,2,opt,name=ItemNum" json:"ItemNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerCampaignRandomIncome) Reset()                    { *m = PlayerCampaignRandomIncome{} }
func (m *PlayerCampaignRandomIncome) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignRandomIncome) ProtoMessage()               {}
func (*PlayerCampaignRandomIncome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PlayerCampaignRandomIncome) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *PlayerCampaignRandomIncome) GetItemNum() int32 {
	if m != nil && m.ItemNum != nil {
		return *m.ItemNum
	}
	return 0
}

type PlayerCampaignRandomIncomeList struct {
	List             []*PlayerCampaignRandomIncome `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *PlayerCampaignRandomIncomeList) Reset()                    { *m = PlayerCampaignRandomIncomeList{} }
func (m *PlayerCampaignRandomIncomeList) String() string            { return proto.CompactTextString(m) }
func (*PlayerCampaignRandomIncomeList) ProtoMessage()               {}
func (*PlayerCampaignRandomIncomeList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PlayerCampaignRandomIncomeList) GetList() []*PlayerCampaignRandomIncome {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerNotifyState struct {
	ModuleType       *int32 `protobuf:"varint,1,opt,name=ModuleType" json:"ModuleType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerNotifyState) Reset()                    { *m = PlayerNotifyState{} }
func (m *PlayerNotifyState) String() string            { return proto.CompactTextString(m) }
func (*PlayerNotifyState) ProtoMessage()               {}
func (*PlayerNotifyState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PlayerNotifyState) GetModuleType() int32 {
	if m != nil && m.ModuleType != nil {
		return *m.ModuleType
	}
	return 0
}

type PlayerNotifyStateList struct {
	List             []*PlayerNotifyState `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *PlayerNotifyStateList) Reset()                    { *m = PlayerNotifyStateList{} }
func (m *PlayerNotifyStateList) String() string            { return proto.CompactTextString(m) }
func (*PlayerNotifyStateList) ProtoMessage()               {}
func (*PlayerNotifyStateList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PlayerNotifyStateList) GetList() []*PlayerNotifyState {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerShopItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	LeftNum          *int32 `protobuf:"varint,2,opt,name=LeftNum" json:"LeftNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerShopItem) Reset()                    { *m = PlayerShopItem{} }
func (m *PlayerShopItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopItem) ProtoMessage()               {}
func (*PlayerShopItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PlayerShopItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerShopItem) GetLeftNum() int32 {
	if m != nil && m.LeftNum != nil {
		return *m.LeftNum
	}
	return 0
}

type PlayerShopItemList struct {
	List             []*PlayerShopItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PlayerShopItemList) Reset()                    { *m = PlayerShopItemList{} }
func (m *PlayerShopItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopItemList) ProtoMessage()               {}
func (*PlayerShopItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PlayerShopItemList) GetList() []*PlayerShopItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerShopLimitedInfo struct {
	LimitedDays      *int32 `protobuf:"varint,1,opt,name=LimitedDays" json:"LimitedDays,omitempty"`
	LastSaveTime     *int32 `protobuf:"varint,2,opt,name=LastSaveTime" json:"LastSaveTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerShopLimitedInfo) Reset()                    { *m = PlayerShopLimitedInfo{} }
func (m *PlayerShopLimitedInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopLimitedInfo) ProtoMessage()               {}
func (*PlayerShopLimitedInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *PlayerShopLimitedInfo) GetLimitedDays() int32 {
	if m != nil && m.LimitedDays != nil {
		return *m.LimitedDays
	}
	return 0
}

func (m *PlayerShopLimitedInfo) GetLastSaveTime() int32 {
	if m != nil && m.LastSaveTime != nil {
		return *m.LastSaveTime
	}
	return 0
}

type PlayerShopLimitedInfoList struct {
	List             []*PlayerShopLimitedInfo `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *PlayerShopLimitedInfoList) Reset()                    { *m = PlayerShopLimitedInfoList{} }
func (m *PlayerShopLimitedInfoList) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopLimitedInfoList) ProtoMessage()               {}
func (*PlayerShopLimitedInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PlayerShopLimitedInfoList) GetList() []*PlayerShopLimitedInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerMailCommon struct {
	CurrId                *int32 `protobuf:"varint,1,opt,name=CurrId" json:"CurrId,omitempty"`
	FirstId               *int32 `protobuf:"varint,2,opt,name=FirstId" json:"FirstId,omitempty"`
	LastSendTribeMailTime *int32 `protobuf:"varint,3,opt,name=LastSendTribeMailTime" json:"LastSendTribeMailTime,omitempty"`
	XXX_unrecognized      []byte `json:"-"`
}

func (m *PlayerMailCommon) Reset()                    { *m = PlayerMailCommon{} }
func (m *PlayerMailCommon) String() string            { return proto.CompactTextString(m) }
func (*PlayerMailCommon) ProtoMessage()               {}
func (*PlayerMailCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *PlayerMailCommon) GetCurrId() int32 {
	if m != nil && m.CurrId != nil {
		return *m.CurrId
	}
	return 0
}

func (m *PlayerMailCommon) GetFirstId() int32 {
	if m != nil && m.FirstId != nil {
		return *m.FirstId
	}
	return 0
}

func (m *PlayerMailCommon) GetLastSendTribeMailTime() int32 {
	if m != nil && m.LastSendTribeMailTime != nil {
		return *m.LastSendTribeMailTime
	}
	return 0
}

type PlayerMail struct {
	Id               *int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Type             *int32  `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	Title            *string `protobuf:"bytes,3,opt,name=Title" json:"Title,omitempty"`
	Content          *string `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
	SendUnix         *int32  `protobuf:"varint,5,opt,name=SendUnix" json:"SendUnix,omitempty"`
	AttachItemIds    []int32 `protobuf:"varint,6,rep,name=AttachItemIds" json:"AttachItemIds,omitempty"`
	AttachItemNums   []int32 `protobuf:"varint,7,rep,name=AttachItemNums" json:"AttachItemNums,omitempty"`
	IsRead           *int32  `protobuf:"varint,8,opt,name=IsRead" json:"IsRead,omitempty"`
	PrevId           *int32  `protobuf:"varint,9,opt,name=PrevId" json:"PrevId,omitempty"`
	NextId           *int32  `protobuf:"varint,10,opt,name=NextId" json:"NextId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerMail) Reset()                    { *m = PlayerMail{} }
func (m *PlayerMail) String() string            { return proto.CompactTextString(m) }
func (*PlayerMail) ProtoMessage()               {}
func (*PlayerMail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *PlayerMail) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerMail) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *PlayerMail) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *PlayerMail) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *PlayerMail) GetSendUnix() int32 {
	if m != nil && m.SendUnix != nil {
		return *m.SendUnix
	}
	return 0
}

func (m *PlayerMail) GetAttachItemIds() []int32 {
	if m != nil {
		return m.AttachItemIds
	}
	return nil
}

func (m *PlayerMail) GetAttachItemNums() []int32 {
	if m != nil {
		return m.AttachItemNums
	}
	return nil
}

func (m *PlayerMail) GetIsRead() int32 {
	if m != nil && m.IsRead != nil {
		return *m.IsRead
	}
	return 0
}

func (m *PlayerMail) GetPrevId() int32 {
	if m != nil && m.PrevId != nil {
		return *m.PrevId
	}
	return 0
}

func (m *PlayerMail) GetNextId() int32 {
	if m != nil && m.NextId != nil {
		return *m.NextId
	}
	return 0
}

type PlayerMailList struct {
	List             []*PlayerMail `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerMailList) Reset()                    { *m = PlayerMailList{} }
func (m *PlayerMailList) String() string            { return proto.CompactTextString(m) }
func (*PlayerMailList) ProtoMessage()               {}
func (*PlayerMailList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *PlayerMailList) GetList() []*PlayerMail {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerBattleSave struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerBattleSave) Reset()                    { *m = PlayerBattleSave{} }
func (m *PlayerBattleSave) String() string            { return proto.CompactTextString(m) }
func (*PlayerBattleSave) ProtoMessage()               {}
func (*PlayerBattleSave) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *PlayerBattleSave) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type PlayerBattleSaveList struct {
	List             []*PlayerBattleSave `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PlayerBattleSaveList) Reset()                    { *m = PlayerBattleSaveList{} }
func (m *PlayerBattleSaveList) String() string            { return proto.CompactTextString(m) }
func (*PlayerBattleSaveList) ProtoMessage()               {}
func (*PlayerBattleSaveList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *PlayerBattleSaveList) GetList() []*PlayerBattleSave {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerDialyTask struct {
	TaskId           *int32 `protobuf:"varint,1,opt,name=TaskId" json:"TaskId,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	RewardUnix       *int32 `protobuf:"varint,3,opt,name=RewardUnix" json:"RewardUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerDialyTask) Reset()                    { *m = PlayerDialyTask{} }
func (m *PlayerDialyTask) String() string            { return proto.CompactTextString(m) }
func (*PlayerDialyTask) ProtoMessage()               {}
func (*PlayerDialyTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *PlayerDialyTask) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *PlayerDialyTask) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *PlayerDialyTask) GetRewardUnix() int32 {
	if m != nil && m.RewardUnix != nil {
		return *m.RewardUnix
	}
	return 0
}

type PlayerDialyTaskList struct {
	List             []*PlayerDialyTask `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PlayerDialyTaskList) Reset()                    { *m = PlayerDialyTaskList{} }
func (m *PlayerDialyTaskList) String() string            { return proto.CompactTextString(m) }
func (*PlayerDialyTaskList) ProtoMessage()               {}
func (*PlayerDialyTaskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *PlayerDialyTaskList) GetList() []*PlayerDialyTask {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerAchieve struct {
	AchieveId        *int32 `protobuf:"varint,1,opt,name=AchieveId" json:"AchieveId,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	RewardUnix       *int32 `protobuf:"varint,3,opt,name=RewardUnix" json:"RewardUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerAchieve) Reset()                    { *m = PlayerAchieve{} }
func (m *PlayerAchieve) String() string            { return proto.CompactTextString(m) }
func (*PlayerAchieve) ProtoMessage()               {}
func (*PlayerAchieve) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *PlayerAchieve) GetAchieveId() int32 {
	if m != nil && m.AchieveId != nil {
		return *m.AchieveId
	}
	return 0
}

func (m *PlayerAchieve) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *PlayerAchieve) GetRewardUnix() int32 {
	if m != nil && m.RewardUnix != nil {
		return *m.RewardUnix
	}
	return 0
}

type PlayerAchieveList struct {
	List             []*PlayerAchieve `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PlayerAchieveList) Reset()                    { *m = PlayerAchieveList{} }
func (m *PlayerAchieveList) String() string            { return proto.CompactTextString(m) }
func (*PlayerAchieveList) ProtoMessage()               {}
func (*PlayerAchieveList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *PlayerAchieveList) GetList() []*PlayerAchieve {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFinishedAchieve struct {
	AchieveId        *int32 `protobuf:"varint,1,opt,name=AchieveId" json:"AchieveId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFinishedAchieve) Reset()                    { *m = PlayerFinishedAchieve{} }
func (m *PlayerFinishedAchieve) String() string            { return proto.CompactTextString(m) }
func (*PlayerFinishedAchieve) ProtoMessage()               {}
func (*PlayerFinishedAchieve) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *PlayerFinishedAchieve) GetAchieveId() int32 {
	if m != nil && m.AchieveId != nil {
		return *m.AchieveId
	}
	return 0
}

type PlayerFinishedAchieveList struct {
	List             []*PlayerFinishedAchieve `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *PlayerFinishedAchieveList) Reset()                    { *m = PlayerFinishedAchieveList{} }
func (m *PlayerFinishedAchieveList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFinishedAchieveList) ProtoMessage()               {}
func (*PlayerFinishedAchieveList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *PlayerFinishedAchieveList) GetList() []*PlayerFinishedAchieve {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerDailyTaskWholeDaily struct {
	CompleteTaskId   *int32 `protobuf:"varint,1,opt,name=CompleteTaskId" json:"CompleteTaskId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerDailyTaskWholeDaily) Reset()                    { *m = PlayerDailyTaskWholeDaily{} }
func (m *PlayerDailyTaskWholeDaily) String() string            { return proto.CompactTextString(m) }
func (*PlayerDailyTaskWholeDaily) ProtoMessage()               {}
func (*PlayerDailyTaskWholeDaily) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *PlayerDailyTaskWholeDaily) GetCompleteTaskId() int32 {
	if m != nil && m.CompleteTaskId != nil {
		return *m.CompleteTaskId
	}
	return 0
}

type PlayerDailyTaskWholeDailyList struct {
	List             []*PlayerDailyTaskWholeDaily `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PlayerDailyTaskWholeDailyList) Reset()                    { *m = PlayerDailyTaskWholeDailyList{} }
func (m *PlayerDailyTaskWholeDailyList) String() string            { return proto.CompactTextString(m) }
func (*PlayerDailyTaskWholeDailyList) ProtoMessage()               {}
func (*PlayerDailyTaskWholeDailyList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PlayerDailyTaskWholeDailyList) GetList() []*PlayerDailyTaskWholeDaily {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerSevenActivity struct {
	ActivityId       *int32 `protobuf:"varint,1,opt,name=ActivityId" json:"ActivityId,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	RewardUnix       *int32 `protobuf:"varint,3,opt,name=RewardUnix" json:"RewardUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerSevenActivity) Reset()                    { *m = PlayerSevenActivity{} }
func (m *PlayerSevenActivity) String() string            { return proto.CompactTextString(m) }
func (*PlayerSevenActivity) ProtoMessage()               {}
func (*PlayerSevenActivity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *PlayerSevenActivity) GetActivityId() int32 {
	if m != nil && m.ActivityId != nil {
		return *m.ActivityId
	}
	return 0
}

func (m *PlayerSevenActivity) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *PlayerSevenActivity) GetRewardUnix() int32 {
	if m != nil && m.RewardUnix != nil {
		return *m.RewardUnix
	}
	return 0
}

type PlayerSevenActivityList struct {
	List             []*PlayerSevenActivity `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PlayerSevenActivityList) Reset()                    { *m = PlayerSevenActivityList{} }
func (m *PlayerSevenActivityList) String() string            { return proto.CompactTextString(m) }
func (*PlayerSevenActivityList) ProtoMessage()               {}
func (*PlayerSevenActivityList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *PlayerSevenActivityList) GetList() []*PlayerSevenActivity {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerGuides struct {
	GuideId          *int32 `protobuf:"varint,1,opt,name=GuideId" json:"GuideId,omitempty"`
	SetUnix          *int32 `protobuf:"varint,2,opt,name=SetUnix" json:"SetUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerGuides) Reset()                    { *m = PlayerGuides{} }
func (m *PlayerGuides) String() string            { return proto.CompactTextString(m) }
func (*PlayerGuides) ProtoMessage()               {}
func (*PlayerGuides) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *PlayerGuides) GetGuideId() int32 {
	if m != nil && m.GuideId != nil {
		return *m.GuideId
	}
	return 0
}

func (m *PlayerGuides) GetSetUnix() int32 {
	if m != nil && m.SetUnix != nil {
		return *m.SetUnix
	}
	return 0
}

type PlayerGuidesList struct {
	List             []*PlayerGuides `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PlayerGuidesList) Reset()                    { *m = PlayerGuidesList{} }
func (m *PlayerGuidesList) String() string            { return proto.CompactTextString(m) }
func (*PlayerGuidesList) ProtoMessage()               {}
func (*PlayerGuidesList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *PlayerGuidesList) GetList() []*PlayerGuides {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendRelative struct {
	LastGiveFriendPointsTime *int32 `protobuf:"varint,1,opt,name=LastGiveFriendPointsTime" json:"LastGiveFriendPointsTime,omitempty"`
	GiveNumToday             *int32 `protobuf:"varint,2,opt,name=GiveNumToday" json:"GiveNumToday,omitempty"`
	LastRefreshTime          *int32 `protobuf:"varint,3,opt,name=LastRefreshTime" json:"LastRefreshTime,omitempty"`
	XXX_unrecognized         []byte `json:"-"`
}

func (m *PlayerFriendRelative) Reset()                    { *m = PlayerFriendRelative{} }
func (m *PlayerFriendRelative) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendRelative) ProtoMessage()               {}
func (*PlayerFriendRelative) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *PlayerFriendRelative) GetLastGiveFriendPointsTime() int32 {
	if m != nil && m.LastGiveFriendPointsTime != nil {
		return *m.LastGiveFriendPointsTime
	}
	return 0
}

func (m *PlayerFriendRelative) GetGiveNumToday() int32 {
	if m != nil && m.GiveNumToday != nil {
		return *m.GiveNumToday
	}
	return 0
}

func (m *PlayerFriendRelative) GetLastRefreshTime() int32 {
	if m != nil && m.LastRefreshTime != nil {
		return *m.LastRefreshTime
	}
	return 0
}

type PlayerFriend struct {
	FriendId           *int32  `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	FriendName         *string `protobuf:"bytes,2,opt,name=FriendName" json:"FriendName,omitempty"`
	Head               *string `protobuf:"bytes,3,opt,name=Head" json:"Head,omitempty"`
	Level              *int32  `protobuf:"varint,4,opt,name=Level" json:"Level,omitempty"`
	VipLevel           *int32  `protobuf:"varint,5,opt,name=VipLevel" json:"VipLevel,omitempty"`
	LastLogin          *int32  `protobuf:"varint,6,opt,name=LastLogin" json:"LastLogin,omitempty"`
	LastGivePointsTime *int32  `protobuf:"varint,7,opt,name=LastGivePointsTime" json:"LastGivePointsTime,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *PlayerFriend) Reset()                    { *m = PlayerFriend{} }
func (m *PlayerFriend) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriend) ProtoMessage()               {}
func (*PlayerFriend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *PlayerFriend) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

func (m *PlayerFriend) GetFriendName() string {
	if m != nil && m.FriendName != nil {
		return *m.FriendName
	}
	return ""
}

func (m *PlayerFriend) GetHead() string {
	if m != nil && m.Head != nil {
		return *m.Head
	}
	return ""
}

func (m *PlayerFriend) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerFriend) GetVipLevel() int32 {
	if m != nil && m.VipLevel != nil {
		return *m.VipLevel
	}
	return 0
}

func (m *PlayerFriend) GetLastLogin() int32 {
	if m != nil && m.LastLogin != nil {
		return *m.LastLogin
	}
	return 0
}

func (m *PlayerFriend) GetLastGivePointsTime() int32 {
	if m != nil && m.LastGivePointsTime != nil {
		return *m.LastGivePointsTime
	}
	return 0
}

type PlayerFriendList struct {
	List             []*PlayerFriend `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PlayerFriendList) Reset()                    { *m = PlayerFriendList{} }
func (m *PlayerFriendList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendList) ProtoMessage()               {}
func (*PlayerFriendList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *PlayerFriendList) GetList() []*PlayerFriend {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendReq struct {
	PlayerId         *int32  `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	PlayerName       *string `protobuf:"bytes,2,opt,name=PlayerName" json:"PlayerName,omitempty"`
	ReqUnix          *int32  `protobuf:"varint,3,opt,name=ReqUnix" json:"ReqUnix,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerFriendReq) Reset()                    { *m = PlayerFriendReq{} }
func (m *PlayerFriendReq) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendReq) ProtoMessage()               {}
func (*PlayerFriendReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *PlayerFriendReq) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *PlayerFriendReq) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *PlayerFriendReq) GetReqUnix() int32 {
	if m != nil && m.ReqUnix != nil {
		return *m.ReqUnix
	}
	return 0
}

type PlayerFriendReqList struct {
	List             []*PlayerFriendReq `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PlayerFriendReqList) Reset()                    { *m = PlayerFriendReqList{} }
func (m *PlayerFriendReqList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendReqList) ProtoMessage()               {}
func (*PlayerFriendReqList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *PlayerFriendReqList) GetList() []*PlayerFriendReq {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendPoint struct {
	FromPlayerId     *int32 `protobuf:"varint,1,opt,name=FromPlayerId" json:"FromPlayerId,omitempty"`
	GivePoints       *int32 `protobuf:"varint,2,opt,name=GivePoints" json:"GivePoints,omitempty"`
	LastGiveTime     *int32 `protobuf:"varint,3,opt,name=LastGiveTime" json:"LastGiveTime,omitempty"`
	IsTodayGive      *int32 `protobuf:"varint,4,opt,name=IsTodayGive" json:"IsTodayGive,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFriendPoint) Reset()                    { *m = PlayerFriendPoint{} }
func (m *PlayerFriendPoint) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendPoint) ProtoMessage()               {}
func (*PlayerFriendPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *PlayerFriendPoint) GetFromPlayerId() int32 {
	if m != nil && m.FromPlayerId != nil {
		return *m.FromPlayerId
	}
	return 0
}

func (m *PlayerFriendPoint) GetGivePoints() int32 {
	if m != nil && m.GivePoints != nil {
		return *m.GivePoints
	}
	return 0
}

func (m *PlayerFriendPoint) GetLastGiveTime() int32 {
	if m != nil && m.LastGiveTime != nil {
		return *m.LastGiveTime
	}
	return 0
}

func (m *PlayerFriendPoint) GetIsTodayGive() int32 {
	if m != nil && m.IsTodayGive != nil {
		return *m.IsTodayGive
	}
	return 0
}

type PlayerFriendPointList struct {
	List             []*PlayerFriendPoint `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *PlayerFriendPointList) Reset()                    { *m = PlayerFriendPointList{} }
func (m *PlayerFriendPointList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendPointList) ProtoMessage()               {}
func (*PlayerFriendPointList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *PlayerFriendPointList) GetList() []*PlayerFriendPoint {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendChatUnreadId struct {
	FriendId         *int32  `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	MessageIds       []int32 `protobuf:"varint,2,rep,name=MessageIds" json:"MessageIds,omitempty"`
	CurrMessageId    *int32  `protobuf:"varint,3,opt,name=CurrMessageId" json:"CurrMessageId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerFriendChatUnreadId) Reset()                    { *m = PlayerFriendChatUnreadId{} }
func (m *PlayerFriendChatUnreadId) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadId) ProtoMessage()               {}
func (*PlayerFriendChatUnreadId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *PlayerFriendChatUnreadId) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

func (m *PlayerFriendChatUnreadId) GetMessageIds() []int32 {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *PlayerFriendChatUnreadId) GetCurrMessageId() int32 {
	if m != nil && m.CurrMessageId != nil {
		return *m.CurrMessageId
	}
	return 0
}

type PlayerFriendChatUnreadIdList struct {
	List             []*PlayerFriendChatUnreadId `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *PlayerFriendChatUnreadIdList) Reset()                    { *m = PlayerFriendChatUnreadIdList{} }
func (m *PlayerFriendChatUnreadIdList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadIdList) ProtoMessage()               {}
func (*PlayerFriendChatUnreadIdList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *PlayerFriendChatUnreadIdList) GetList() []*PlayerFriendChatUnreadId {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendChatUnreadMessage struct {
	PlayerMessageId  *int64 `protobuf:"varint,1,opt,name=PlayerMessageId" json:"PlayerMessageId,omitempty"`
	Message          []byte `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	SendTime         *int32 `protobuf:"varint,3,opt,name=SendTime" json:"SendTime,omitempty"`
	IsRead           *int32 `protobuf:"varint,4,opt,name=IsRead" json:"IsRead,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFriendChatUnreadMessage) Reset()                    { *m = PlayerFriendChatUnreadMessage{} }
func (m *PlayerFriendChatUnreadMessage) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadMessage) ProtoMessage()               {}
func (*PlayerFriendChatUnreadMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *PlayerFriendChatUnreadMessage) GetPlayerMessageId() int64 {
	if m != nil && m.PlayerMessageId != nil {
		return *m.PlayerMessageId
	}
	return 0
}

func (m *PlayerFriendChatUnreadMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PlayerFriendChatUnreadMessage) GetSendTime() int32 {
	if m != nil && m.SendTime != nil {
		return *m.SendTime
	}
	return 0
}

func (m *PlayerFriendChatUnreadMessage) GetIsRead() int32 {
	if m != nil && m.IsRead != nil {
		return *m.IsRead
	}
	return 0
}

type PlayerFriendChatUnreadMessageList struct {
	List             []*PlayerFriendChatUnreadMessage `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *PlayerFriendChatUnreadMessageList) Reset()         { *m = PlayerFriendChatUnreadMessageList{} }
func (m *PlayerFriendChatUnreadMessageList) String() string { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadMessageList) ProtoMessage()    {}
func (*PlayerFriendChatUnreadMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{49}
}

func (m *PlayerFriendChatUnreadMessageList) GetList() []*PlayerFriendChatUnreadMessage {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerChaterOpenRequest struct {
	CustomData       []byte `protobuf:"bytes,1,opt,name=CustomData" json:"CustomData,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerChaterOpenRequest) Reset()                    { *m = PlayerChaterOpenRequest{} }
func (m *PlayerChaterOpenRequest) String() string            { return proto.CompactTextString(m) }
func (*PlayerChaterOpenRequest) ProtoMessage()               {}
func (*PlayerChaterOpenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *PlayerChaterOpenRequest) GetCustomData() []byte {
	if m != nil {
		return m.CustomData
	}
	return nil
}

type PlayerHandbookItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerHandbookItem) Reset()                    { *m = PlayerHandbookItem{} }
func (m *PlayerHandbookItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerHandbookItem) ProtoMessage()               {}
func (*PlayerHandbookItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *PlayerHandbookItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type PlayerHandbookItemList struct {
	List             []*PlayerHandbookItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PlayerHandbookItemList) Reset()                    { *m = PlayerHandbookItemList{} }
func (m *PlayerHandbookItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerHandbookItemList) ProtoMessage()               {}
func (*PlayerHandbookItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

func (m *PlayerHandbookItemList) GetList() []*PlayerHandbookItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerHeadItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerHeadItem) Reset()                    { *m = PlayerHeadItem{} }
func (m *PlayerHeadItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerHeadItem) ProtoMessage()               {}
func (*PlayerHeadItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

func (m *PlayerHeadItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type PlayerHeadItemList struct {
	List             []*PlayerHeadItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PlayerHeadItemList) Reset()                    { *m = PlayerHeadItemList{} }
func (m *PlayerHeadItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerHeadItemList) ProtoMessage()               {}
func (*PlayerHeadItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{54} }

func (m *PlayerHeadItemList) GetList() []*PlayerHeadItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerSuitAward struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	AwardTime        *int32 `protobuf:"varint,2,opt,name=AwardTime" json:"AwardTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerSuitAward) Reset()                    { *m = PlayerSuitAward{} }
func (m *PlayerSuitAward) String() string            { return proto.CompactTextString(m) }
func (*PlayerSuitAward) ProtoMessage()               {}
func (*PlayerSuitAward) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{55} }

func (m *PlayerSuitAward) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerSuitAward) GetAwardTime() int32 {
	if m != nil && m.AwardTime != nil {
		return *m.AwardTime
	}
	return 0
}

type PlayerSuitAwardList struct {
	List             []*PlayerSuitAward `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PlayerSuitAwardList) Reset()                    { *m = PlayerSuitAwardList{} }
func (m *PlayerSuitAwardList) String() string            { return proto.CompactTextString(m) }
func (*PlayerSuitAwardList) ProtoMessage()               {}
func (*PlayerSuitAwardList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{56} }

func (m *PlayerSuitAwardList) GetList() []*PlayerSuitAward {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerWorldChat struct {
	LastChatTime     *int32 `protobuf:"varint,1,opt,name=LastChatTime" json:"LastChatTime,omitempty"`
	LastPullTime     *int32 `protobuf:"varint,2,opt,name=LastPullTime" json:"LastPullTime,omitempty"`
	LastMsgIndex     *int32 `protobuf:"varint,3,opt,name=LastMsgIndex" json:"LastMsgIndex,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerWorldChat) Reset()                    { *m = PlayerWorldChat{} }
func (m *PlayerWorldChat) String() string            { return proto.CompactTextString(m) }
func (*PlayerWorldChat) ProtoMessage()               {}
func (*PlayerWorldChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{57} }

func (m *PlayerWorldChat) GetLastChatTime() int32 {
	if m != nil && m.LastChatTime != nil {
		return *m.LastChatTime
	}
	return 0
}

func (m *PlayerWorldChat) GetLastPullTime() int32 {
	if m != nil && m.LastPullTime != nil {
		return *m.LastPullTime
	}
	return 0
}

func (m *PlayerWorldChat) GetLastMsgIndex() int32 {
	if m != nil && m.LastMsgIndex != nil {
		return *m.LastMsgIndex
	}
	return 0
}

type PlayerAnouncement struct {
	LastSendTime     *int32 `protobuf:"varint,1,opt,name=LastSendTime" json:"LastSendTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerAnouncement) Reset()                    { *m = PlayerAnouncement{} }
func (m *PlayerAnouncement) String() string            { return proto.CompactTextString(m) }
func (*PlayerAnouncement) ProtoMessage()               {}
func (*PlayerAnouncement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{58} }

func (m *PlayerAnouncement) GetLastSendTime() int32 {
	if m != nil && m.LastSendTime != nil {
		return *m.LastSendTime
	}
	return 0
}

type PlayerFirstDrawCard struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Drawed           *int32 `protobuf:"varint,2,opt,name=Drawed" json:"Drawed,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFirstDrawCard) Reset()                    { *m = PlayerFirstDrawCard{} }
func (m *PlayerFirstDrawCard) String() string            { return proto.CompactTextString(m) }
func (*PlayerFirstDrawCard) ProtoMessage()               {}
func (*PlayerFirstDrawCard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{59} }

func (m *PlayerFirstDrawCard) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerFirstDrawCard) GetDrawed() int32 {
	if m != nil && m.Drawed != nil {
		return *m.Drawed
	}
	return 0
}

type PlayerFirstDrawCardList struct {
	List             []*PlayerFirstDrawCard `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PlayerFirstDrawCardList) Reset()                    { *m = PlayerFirstDrawCardList{} }
func (m *PlayerFirstDrawCardList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFirstDrawCardList) ProtoMessage()               {}
func (*PlayerFirstDrawCardList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{60} }

func (m *PlayerFirstDrawCardList) GetList() []*PlayerFirstDrawCard {
	if m != nil {
		return m.List
	}
	return nil
}

type BattleSaveData struct {
	Data             []byte `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BattleSaveData) Reset()                    { *m = BattleSaveData{} }
func (m *BattleSaveData) String() string            { return proto.CompactTextString(m) }
func (*BattleSaveData) ProtoMessage()               {}
func (*BattleSaveData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{61} }

func (m *BattleSaveData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SmallRankRecord)(nil), "db.SmallRankRecord")
	proto.RegisterType((*LimitShopItem)(nil), "db.LimitShopItem")
	proto.RegisterType((*PlayerInfo)(nil), "db.PlayerInfo")
	proto.RegisterType((*PlayerGlobal)(nil), "db.PlayerGlobal")
	proto.RegisterType((*PlayerItem)(nil), "db.PlayerItem")
	proto.RegisterType((*PlayerItemList)(nil), "db.PlayerItemList")
	proto.RegisterType((*PlayerRole)(nil), "db.PlayerRole")
	proto.RegisterType((*PlayerRoleList)(nil), "db.PlayerRoleList")
	proto.RegisterType((*PlayerBattleTeam)(nil), "db.PlayerBattleTeam")
	proto.RegisterType((*PlayerCampaignCommon)(nil), "db.PlayerCampaignCommon")
	proto.RegisterType((*PlayerCampaign)(nil), "db.PlayerCampaign")
	proto.RegisterType((*PlayerCampaignList)(nil), "db.PlayerCampaignList")
	proto.RegisterType((*PlayerCampaignStaticIncome)(nil), "db.PlayerCampaignStaticIncome")
	proto.RegisterType((*PlayerCampaignStaticIncomeList)(nil), "db.PlayerCampaignStaticIncomeList")
	proto.RegisterType((*PlayerCampaignRandomIncome)(nil), "db.PlayerCampaignRandomIncome")
	proto.RegisterType((*PlayerCampaignRandomIncomeList)(nil), "db.PlayerCampaignRandomIncomeList")
	proto.RegisterType((*PlayerNotifyState)(nil), "db.PlayerNotifyState")
	proto.RegisterType((*PlayerNotifyStateList)(nil), "db.PlayerNotifyStateList")
	proto.RegisterType((*PlayerShopItem)(nil), "db.PlayerShopItem")
	proto.RegisterType((*PlayerShopItemList)(nil), "db.PlayerShopItemList")
	proto.RegisterType((*PlayerShopLimitedInfo)(nil), "db.PlayerShopLimitedInfo")
	proto.RegisterType((*PlayerShopLimitedInfoList)(nil), "db.PlayerShopLimitedInfoList")
	proto.RegisterType((*PlayerMailCommon)(nil), "db.PlayerMailCommon")
	proto.RegisterType((*PlayerMail)(nil), "db.PlayerMail")
	proto.RegisterType((*PlayerMailList)(nil), "db.PlayerMailList")
	proto.RegisterType((*PlayerBattleSave)(nil), "db.PlayerBattleSave")
	proto.RegisterType((*PlayerBattleSaveList)(nil), "db.PlayerBattleSaveList")
	proto.RegisterType((*PlayerDialyTask)(nil), "db.PlayerDialyTask")
	proto.RegisterType((*PlayerDialyTaskList)(nil), "db.PlayerDialyTaskList")
	proto.RegisterType((*PlayerAchieve)(nil), "db.PlayerAchieve")
	proto.RegisterType((*PlayerAchieveList)(nil), "db.PlayerAchieveList")
	proto.RegisterType((*PlayerFinishedAchieve)(nil), "db.PlayerFinishedAchieve")
	proto.RegisterType((*PlayerFinishedAchieveList)(nil), "db.PlayerFinishedAchieveList")
	proto.RegisterType((*PlayerDailyTaskWholeDaily)(nil), "db.PlayerDailyTaskWholeDaily")
	proto.RegisterType((*PlayerDailyTaskWholeDailyList)(nil), "db.PlayerDailyTaskWholeDailyList")
	proto.RegisterType((*PlayerSevenActivity)(nil), "db.PlayerSevenActivity")
	proto.RegisterType((*PlayerSevenActivityList)(nil), "db.PlayerSevenActivityList")
	proto.RegisterType((*PlayerGuides)(nil), "db.PlayerGuides")
	proto.RegisterType((*PlayerGuidesList)(nil), "db.PlayerGuidesList")
	proto.RegisterType((*PlayerFriendRelative)(nil), "db.PlayerFriendRelative")
	proto.RegisterType((*PlayerFriend)(nil), "db.PlayerFriend")
	proto.RegisterType((*PlayerFriendList)(nil), "db.PlayerFriendList")
	proto.RegisterType((*PlayerFriendReq)(nil), "db.PlayerFriendReq")
	proto.RegisterType((*PlayerFriendReqList)(nil), "db.PlayerFriendReqList")
	proto.RegisterType((*PlayerFriendPoint)(nil), "db.PlayerFriendPoint")
	proto.RegisterType((*PlayerFriendPointList)(nil), "db.PlayerFriendPointList")
	proto.RegisterType((*PlayerFriendChatUnreadId)(nil), "db.PlayerFriendChatUnreadId")
	proto.RegisterType((*PlayerFriendChatUnreadIdList)(nil), "db.PlayerFriendChatUnreadIdList")
	proto.RegisterType((*PlayerFriendChatUnreadMessage)(nil), "db.PlayerFriendChatUnreadMessage")
	proto.RegisterType((*PlayerFriendChatUnreadMessageList)(nil), "db.PlayerFriendChatUnreadMessageList")
	proto.RegisterType((*PlayerChaterOpenRequest)(nil), "db.PlayerChaterOpenRequest")
	proto.RegisterType((*PlayerHandbookItem)(nil), "db.PlayerHandbookItem")
	proto.RegisterType((*PlayerHandbookItemList)(nil), "db.PlayerHandbookItemList")
	proto.RegisterType((*PlayerHeadItem)(nil), "db.PlayerHeadItem")
	proto.RegisterType((*PlayerHeadItemList)(nil), "db.PlayerHeadItemList")
	proto.RegisterType((*PlayerSuitAward)(nil), "db.PlayerSuitAward")
	proto.RegisterType((*PlayerSuitAwardList)(nil), "db.PlayerSuitAwardList")
	proto.RegisterType((*PlayerWorldChat)(nil), "db.PlayerWorldChat")
	proto.RegisterType((*PlayerAnouncement)(nil), "db.PlayerAnouncement")
	proto.RegisterType((*PlayerFirstDrawCard)(nil), "db.PlayerFirstDrawCard")
	proto.RegisterType((*PlayerFirstDrawCardList)(nil), "db.PlayerFirstDrawCardList")
	proto.RegisterType((*BattleSaveData)(nil), "db.BattleSaveData")
}

func init() { proto.RegisterFile("db_hallsvr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1836 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x58, 0x6d, 0x6f, 0x1b, 0x4f,
	0x11, 0x97, 0x9d, 0xa7, 0x66, 0x9b, 0xa6, 0xe9, 0x35, 0xcd, 0xff, 0x5a, 0xb5, 0x51, 0x7a, 0x0a,
	0x25, 0x14, 0x88, 0x4a, 0x69, 0x05, 0x54, 0x3c, 0xa5, 0x76, 0xd3, 0x1a, 0x92, 0x10, 0x9d, 0x9d,
	0x56, 0x02, 0xa1, 0xb2, 0xf6, 0x6d, 0xe2, 0x53, 0xee, 0x6e, 0x9d, 0xbb, 0x3d, 0x37, 0x46, 0x20,
	0xf1, 0x9a, 0x97, 0xbc, 0x41, 0x42, 0x42, 0xe2, 0x13, 0xf1, 0x11, 0xf8, 0x2c, 0x68, 0x76, 0x67,
	0x1f, 0xce, 0x4f, 0xad, 0xaa, 0xff, 0x2b, 0xef, 0xfc, 0x76, 0x6e, 0xf7, 0xb7, 0x33, 0xb3, 0x33,
	0xb3, 0x26, 0x1b, 0x51, 0xf7, 0x63, 0x9f, 0x26, 0x49, 0x31, 0xcc, 0xf7, 0x07, 0x39, 0x17, 0xdc,
	0xab, 0x47, 0xdd, 0xe0, 0x0f, 0xe4, 0x76, 0x3b, 0xa5, 0x49, 0x12, 0xd2, 0xec, 0x32, 0x64, 0x3d,
	0x9e, 0x47, 0x9e, 0x47, 0x16, 0x41, 0xf2, 0x6b, 0x3b, 0xb5, 0xbd, 0xa5, 0x50, 0x8e, 0xbd, 0x75,
	0x52, 0x6f, 0x45, 0x7e, 0x5d, 0x22, 0xf5, 0x56, 0xe4, 0x6d, 0x90, 0x85, 0xf7, 0x34, 0xf1, 0x17,
	0x24, 0x00, 0x43, 0xf8, 0xea, 0x84, 0xa6, 0xcc, 0x5f, 0xdc, 0xa9, 0xed, 0xad, 0x86, 0x72, 0x1c,
	0xfc, 0x96, 0xdc, 0x3a, 0x8a, 0xd3, 0x58, 0xb4, 0xfb, 0x7c, 0xd0, 0x12, 0x2c, 0xf5, 0x76, 0xc8,
	0xcd, 0x06, 0x4f, 0x53, 0x1e, 0xc5, 0x62, 0xd4, 0x8a, 0x70, 0x07, 0x17, 0xf2, 0x7c, 0xb2, 0x72,
	0xc4, 0xce, 0xc5, 0x49, 0x99, 0xe2, 0x6e, 0x5a, 0x0c, 0xfe, 0x55, 0x27, 0xe4, 0x34, 0xa1, 0x23,
	0x96, 0xb7, 0xb2, 0x73, 0x0e, 0x0c, 0x8e, 0x86, 0x09, 0x2e, 0x01, 0x43, 0x40, 0xde, 0x5c, 0x0f,
	0xf0, 0x33, 0x18, 0x7a, 0xdb, 0x84, 0x34, 0x72, 0x46, 0x05, 0x3b, 0xcb, 0xe2, 0x6b, 0x24, 0xeb,
	0x20, 0xc0, 0xf9, 0x2d, 0x4f, 0x22, 0xc9, 0x79, 0x29, 0x94, 0x63, 0x20, 0xd0, 0x8c, 0x69, 0xca,
	0xb3, 0xc8, 0x5f, 0x52, 0x04, 0x50, 0xf4, 0x9e, 0x91, 0xbb, 0x47, 0xb4, 0x10, 0xcd, 0x98, 0x26,
	0xa3, 0x0e, 0x2d, 0x2e, 0xcf, 0x06, 0x67, 0x71, 0x76, 0xed, 0x2f, 0x4b, 0xad, 0x69, 0x53, 0xb0,
	0x7e, 0xab, 0xc7, 0x33, 0x7f, 0x45, 0xd9, 0x04, 0xc6, 0xc0, 0x09, 0x54, 0x8f, 0xf8, 0x05, 0x2f,
	0x85, 0xbf, 0xaa, 0x38, 0x59, 0xc4, 0x7b, 0x48, 0x56, 0x51, 0x8a, 0x33, 0x9f, 0xc8, 0x69, 0x0b,
	0x78, 0x5b, 0x64, 0xf9, 0x7d, 0x3c, 0x80, 0x83, 0x6f, 0xc8, 0x29, 0x94, 0x82, 0x17, 0x64, 0x4d,
	0xd9, 0xe6, 0x6d, 0xc2, 0xbb, 0x34, 0xf1, 0x76, 0xc9, 0xad, 0x46, 0x99, 0xe7, 0x2c, 0x13, 0x21,
	0x4f, 0x98, 0x31, 0x75, 0x15, 0x0c, 0x9e, 0x1b, 0x8b, 0x82, 0x73, 0x94, 0x8f, 0x6b, 0xc6, 0xc7,
	0x9b, 0x64, 0xa9, 0xc1, 0xcb, 0x4c, 0xa0, 0x45, 0x95, 0x10, 0xbc, 0x20, 0xeb, 0xf6, 0x9b, 0xa3,
	0xb8, 0x10, 0x5e, 0x40, 0x16, 0xe1, 0xd7, 0xaf, 0xed, 0x2c, 0xec, 0xdd, 0x7c, 0xbe, 0xbe, 0x1f,
	0x75, 0xf7, 0xad, 0x46, 0x28, 0xe7, 0x82, 0xbf, 0xd7, 0xf4, 0x56, 0xb0, 0xf5, 0xc4, 0x56, 0x3e,
	0x59, 0xe9, 0xd0, 0xae, 0x24, 0x8a, 0x5e, 0x47, 0xd1, 0x04, 0xe3, 0x82, 0x13, 0x8c, 0x9b, 0x64,
	0xe9, 0x88, 0x0d, 0x59, 0x82, 0x7e, 0x53, 0x02, 0x68, 0x1e, 0x08, 0x91, 0xfb, 0x4b, 0x3b, 0x0b,
	0xa0, 0x09, 0x63, 0xd0, 0x7c, 0x73, 0x55, 0xc6, 0x03, 0x7f, 0x59, 0x82, 0x4a, 0xb0, 0x47, 0x00,
	0x2e, 0xf3, 0x8f, 0x00, 0x1a, 0x78, 0x84, 0x3f, 0x91, 0x0d, 0x85, 0xbd, 0xa6, 0x42, 0x24, 0xac,
	0xc3, 0x68, 0x0a, 0x66, 0x3e, 0x10, 0x82, 0xf6, 0x2e, 0x8f, 0x59, 0xda, 0x65, 0x79, 0x21, 0x17,
	0x58, 0x0a, 0xab, 0xa0, 0xf7, 0x84, 0xac, 0x37, 0xd9, 0x39, 0xcb, 0x0a, 0xa6, 0xd5, 0xea, 0x52,
	0x6d, 0x0c, 0x0d, 0xfe, 0x56, 0x27, 0x9b, 0x6a, 0x8b, 0x06, 0x4d, 0x07, 0x34, 0xbe, 0xc8, 0xe4,
	0xcd, 0xc8, 0xbc, 0x1f, 0x90, 0x3b, 0xe8, 0x38, 0x3d, 0x61, 0xac, 0x37, 0x39, 0xe1, 0x1d, 0x92,
	0xed, 0x77, 0x34, 0xbb, 0x28, 0x07, 0x32, 0x24, 0x73, 0x3e, 0x68, 0x0b, 0x2a, 0xe2, 0x5e, 0x2b,
	0xeb, 0xf1, 0x94, 0x75, 0xe2, 0x94, 0xa1, 0x8d, 0x3f, 0xa3, 0x35, 0xb9, 0x4e, 0x48, 0xb3, 0x88,
	0xa7, 0xce, 0x3a, 0x0b, 0xd3, 0xd6, 0x19, 0xd7, 0xf2, 0x9e, 0x92, 0x0d, 0xa5, 0xe1, 0x90, 0x57,
	0x9e, 0x9b, 0xc0, 0x83, 0xff, 0xd6, 0xb4, 0x6f, 0x34, 0x28, 0x2f, 0xf1, 0xf8, 0xa9, 0x1d, 0x04,
	0x7c, 0xdc, 0x16, 0x54, 0x1a, 0x55, 0x46, 0x83, 0x14, 0x60, 0x53, 0x20, 0x74, 0x18, 0x67, 0x71,
	0xd1, 0x67, 0x91, 0x43, 0x77, 0x02, 0xf7, 0x1e, 0x90, 0x1b, 0x1d, 0x3e, 0x68, 0xf7, 0x78, 0xce,
	0x90, 0x98, 0x91, 0x21, 0x63, 0x49, 0x3e, 0x91, 0xba, 0x0a, 0xea, 0xb2, 0xbb, 0x10, 0x5c, 0xd8,
	0x53, 0x5a, 0x14, 0x6a, 0x7e, 0x45, 0x5d, 0x58, 0x03, 0x04, 0x3f, 0x27, 0x5e, 0xf5, 0x3c, 0x32,
	0xde, 0x9e, 0x54, 0xe2, 0xcd, 0xb3, 0xf1, 0xa6, 0xb5, 0x30, 0xe6, 0x4e, 0xc8, 0x83, 0x2a, 0xee,
	0x3a, 0x09, 0x92, 0x01, 0x5c, 0x31, 0x63, 0x15, 0x94, 0xe0, 0x36, 0xc1, 0xc8, 0xc9, 0xa1, 0x28,
	0x06, 0x1d, 0xb2, 0x3d, 0x7b, 0x3d, 0xc9, 0xec, 0x79, 0x85, 0xd9, 0xf6, 0x24, 0x33, 0xf7, 0x8b,
	0x59, 0x2c, 0xdd, 0x10, 0xf8, 0x36, 0x58, 0xba, 0xeb, 0x7d, 0x19, 0x4b, 0xf7, 0x0b, 0x64, 0xf9,
	0x63, 0x72, 0x47, 0xe9, 0x9c, 0x70, 0x11, 0x9f, 0x8f, 0xe0, 0x1c, 0x0c, 0x82, 0xeb, 0x98, 0x47,
	0x65, 0xc2, 0x3a, 0xa3, 0x01, 0xd3, 0xc1, 0x65, 0x91, 0xe0, 0x35, 0xb9, 0x37, 0xf1, 0x91, 0x64,
	0xf0, 0xbd, 0x0a, 0x83, 0x7b, 0x96, 0x81, 0xa3, 0x88, 0x1b, 0xbf, 0xd2, 0x21, 0x6d, 0xca, 0xe0,
	0x94, 0xf4, 0x37, 0xa3, 0xe8, 0x99, 0xf0, 0xd1, 0xdf, 0xce, 0x0f, 0x1f, 0xad, 0x85, 0x3b, 0xff,
	0x51, 0xb3, 0x07, 0x5c, 0x56, 0x62, 0x16, 0xc9, 0xe2, 0xb9, 0x43, 0x6e, 0xa2, 0xd8, 0xa4, 0xa3,
	0x42, 0xd7, 0x61, 0x07, 0xf2, 0x02, 0xb2, 0x06, 0xf7, 0xa4, 0x4d, 0x87, 0x6e, 0xca, 0xa8, 0x60,
	0xc1, 0x6f, 0xc8, 0xfd, 0xa9, 0xcb, 0x4b, 0x8e, 0x3f, 0xac, 0x70, 0xbc, 0x5f, 0xe5, 0xe8, 0x28,
	0x23, 0xd5, 0x3f, 0xeb, 0xec, 0x7a, 0x4c, 0xe3, 0x04, 0xd3, 0xde, 0x16, 0x59, 0x86, 0xec, 0x66,
	0x23, 0x47, 0x49, 0x60, 0xae, 0xc3, 0x38, 0x2f, 0x84, 0xad, 0x16, 0x28, 0x7a, 0x2f, 0xc8, 0x3d,
	0xc9, 0x90, 0x65, 0x51, 0x27, 0x8f, 0xbb, 0x0c, 0x16, 0x73, 0xae, 0xfe, 0xf4, 0xc9, 0xe0, 0x1f,
	0xa6, 0xb3, 0x00, 0x68, 0xc2, 0x3b, 0x1e, 0x59, 0x94, 0xd1, 0xa1, 0xf6, 0x92, 0x63, 0x48, 0x3a,
	0x9d, 0x58, 0x24, 0x6a, 0xe1, 0xd5, 0x50, 0x09, 0x40, 0xac, 0xc1, 0x33, 0xc1, 0x32, 0x81, 0x6d,
	0x90, 0x16, 0x21, 0xc5, 0xc0, 0xbe, 0xb2, 0x0f, 0x51, 0x6d, 0x85, 0x91, 0x4d, 0x11, 0xe9, 0xab,
	0x8b, 0x51, 0x60, 0xb1, 0xaa, 0x82, 0x50, 0x44, 0x2c, 0x70, 0x52, 0xa6, 0x85, 0xbf, 0xa2, 0x8a,
	0x48, 0x15, 0x95, 0xd7, 0xad, 0x08, 0x19, 0x8d, 0xfc, 0x1b, 0x78, 0xdd, 0xa4, 0x04, 0xf8, 0x69,
	0xce, 0x86, 0xad, 0x08, 0x7b, 0x0e, 0x94, 0x00, 0x3f, 0x61, 0xd7, 0x60, 0x4b, 0xd5, 0x6c, 0xa0,
	0x64, 0x8b, 0x24, 0xd8, 0x64, 0x7e, 0x91, 0x04, 0x0d, 0x74, 0x63, 0x50, 0x2d, 0x92, 0x10, 0x2a,
	0xe3, 0xf6, 0x0c, 0x7e, 0xad, 0xab, 0x9c, 0xd5, 0x91, 0xeb, 0xef, 0x55, 0xd6, 0xdf, 0xb4, 0xeb,
	0x5b, 0x3d, 0xdc, 0xe5, 0x23, 0xb9, 0xad, 0x66, 0x4c, 0xc3, 0x05, 0xc7, 0x80, 0x5f, 0x1b, 0x2b,
	0x4a, 0x02, 0x47, 0xbd, 0xa7, 0x49, 0xa9, 0xbd, 0xa7, 0x04, 0xb8, 0xf6, 0x21, 0xfb, 0x44, 0xf3,
	0xc8, 0x6d, 0x0c, 0x2d, 0x12, 0xfc, 0x92, 0xdc, 0x1d, 0xdb, 0x40, 0x32, 0xfc, 0x6e, 0x85, 0xe1,
	0x5d, 0xcb, 0xd0, 0xa8, 0x21, 0xc1, 0x1e, 0xb9, 0xa5, 0x26, 0x0e, 0x7a, 0xfd, 0x98, 0x0d, 0x19,
	0x14, 0x09, 0x1c, 0x1a, 0x86, 0x16, 0xf8, 0x4a, 0x92, 0xaf, 0x74, 0x42, 0xc3, 0x85, 0x24, 0xc5,
	0xef, 0x54, 0x28, 0xde, 0xb1, 0x14, 0x51, 0x09, 0x09, 0xbe, 0xd4, 0x99, 0x41, 0x17, 0xc2, 0x2f,
	0x22, 0x6a, 0x6f, 0xfc, 0xd8, 0x67, 0xf3, 0x6f, 0xfc, 0x98, 0x32, 0x52, 0x68, 0xe8, 0xb5, 0x9a,
	0x34, 0x56, 0xc6, 0xfb, 0xd0, 0xe7, 0x09, 0x93, 0x12, 0x44, 0x7b, 0x83, 0xa7, 0x83, 0x84, 0x09,
	0x56, 0x71, 0xeb, 0x18, 0x1a, 0x84, 0xe4, 0xd1, 0xcc, 0x45, 0x24, 0xa9, 0x1f, 0x55, 0x48, 0x3d,
	0x72, 0x5c, 0x36, 0xf9, 0x01, 0x12, 0xbb, 0xd4, 0xce, 0x6f, 0xb3, 0x21, 0xcb, 0x0e, 0x7a, 0x22,
	0x1e, 0xc6, 0x62, 0x04, 0xee, 0xd0, 0x63, 0xdb, 0x87, 0x58, 0xe4, 0x2b, 0x9d, 0x78, 0x48, 0xbe,
	0x99, 0xb2, 0x99, 0xa4, 0xfe, 0xfd, 0x0a, 0xf5, 0x6f, 0x9c, 0x0c, 0xea, 0xaa, 0x22, 0xe9, 0xd7,
	0xe6, 0x01, 0x50, 0xc6, 0x11, 0x2b, 0x20, 0x15, 0xc9, 0x91, 0xa1, 0xaa, 0x45, 0x98, 0x69, 0x33,
	0x21, 0xe9, 0x60, 0xf6, 0x44, 0x31, 0xf8, 0xa9, 0xbe, 0xbc, 0x6a, 0x0d, 0x49, 0x62, 0xb7, 0x42,
	0x62, 0xc3, 0x92, 0x50, 0x3a, 0xb8, 0xfb, 0x7f, 0x6a, 0xfa, 0x4e, 0x1f, 0xe6, 0x31, 0xcb, 0xa2,
	0x90, 0x25, 0x54, 0xc4, 0x43, 0xe6, 0xbd, 0x22, 0x3e, 0xe4, 0xdc, 0xb7, 0xf1, 0x90, 0xa9, 0x99,
	0x53, 0x1e, 0x67, 0xa2, 0x90, 0x39, 0x59, 0xf1, 0x9a, 0x39, 0x0f, 0x25, 0x08, 0xf0, 0x93, 0x32,
	0xed, 0xf0, 0x88, 0x8e, 0x74, 0x09, 0x72, 0x31, 0x6f, 0x8f, 0xdc, 0x86, 0xef, 0x43, 0x76, 0x9e,
	0xb3, 0xa2, 0xef, 0xa4, 0xfa, 0x71, 0x38, 0xf8, 0x5f, 0x4d, 0x5b, 0x48, 0x6d, 0x04, 0x29, 0x59,
	0x8d, 0x8c, 0x89, 0x8c, 0x0c, 0x5e, 0x53, 0x63, 0xf9, 0xa4, 0xad, 0xcb, 0x5c, 0xee, 0x20, 0x50,
	0x12, 0xde, 0x41, 0x8a, 0x55, 0xd9, 0x5f, 0x8e, 0x67, 0xbc, 0x4a, 0x1e, 0x90, 0x1b, 0xf0, 0x44,
	0x93, 0x13, 0x98, 0xf8, 0xb5, 0x5c, 0x7d, 0xea, 0x2d, 0x8f, 0x3f, 0xf5, 0xf6, 0x89, 0xa7, 0x4d,
	0xe3, 0x18, 0x4d, 0x35, 0x98, 0x53, 0x66, 0xac, 0xf7, 0x14, 0xcf, 0xf9, 0xde, 0x43, 0x37, 0x29,
	0xef, 0x5d, 0xe8, 0x74, 0xaa, 0x9d, 0x77, 0x05, 0xb4, 0xf1, 0x0d, 0x67, 0x8c, 0xa3, 0x65, 0x30,
	0x0e, 0xb6, 0x3a, 0x8e, 0x71, 0x2c, 0x02, 0x01, 0x16, 0xb2, 0x2b, 0x27, 0xde, 0xb5, 0x68, 0xd3,
	0xaa, 0xd9, 0x68, 0x7e, 0x5a, 0x35, 0x6a, 0x48, 0xf4, 0xdf, 0x35, 0x9d, 0xf2, 0x9c, 0x60, 0x81,
	0x38, 0x39, 0xcc, 0x79, 0x3a, 0xc6, 0xb7, 0x82, 0x01, 0x67, 0x6b, 0x2e, 0x8c, 0x24, 0x07, 0xd1,
	0xed, 0x0e, 0x20, 0x4e, 0x10, 0x55, 0x30, 0x68, 0x9a, 0x5a, 0x85, 0x0c, 0x3b, 0x80, 0xd0, 0xcd,
	0x2e, 0x64, 0xbb, 0x45, 0x87, 0xde, 0xfc, 0x6e, 0xd1, 0x51, 0xc4, 0x33, 0xfe, 0x85, 0xf8, 0xee,
	0x54, 0xa3, 0x4f, 0xc5, 0x59, 0x96, 0x33, 0x0a, 0x61, 0xf9, 0x99, 0x90, 0x3d, 0x66, 0x45, 0x41,
	0x2f, 0x18, 0xb4, 0x10, 0xea, 0x81, 0xe9, 0x20, 0xfa, 0x1f, 0x01, 0x83, 0xe0, 0x11, 0xab, 0x60,
	0x70, 0x4a, 0x1e, 0xce, 0xda, 0x5d, 0x1e, 0xe4, 0x59, 0xe5, 0x20, 0x0f, 0xc7, 0x0f, 0xe2, 0xea,
	0xe3, 0x79, 0xfe, 0x59, 0xd3, 0x29, 0x7a, 0x5c, 0x05, 0x77, 0x85, 0x3b, 0x8c, 0x7d, 0x84, 0xe1,
	0x06, 0x87, 0x5b, 0x08, 0xc7, 0x61, 0x88, 0x2c, 0x14, 0xa4, 0x0b, 0xd7, 0x42, 0x2d, 0xea, 0xfe,
	0xca, 0xf1, 0x9d, 0x91, 0x9d, 0x8e, 0x68, 0xd1, 0xed, 0x88, 0x82, 0xdf, 0x93, 0xc7, 0x73, 0x89,
	0xc9, 0x03, 0xbf, 0xac, 0x1c, 0xf8, 0xf1, 0xec, 0x03, 0xe3, 0x47, 0x78, 0xea, 0x9f, 0xe9, 0xb4,
	0x0e, 0x0a, 0x2c, 0xff, 0xdd, 0x80, 0x65, 0x21, 0xbb, 0x2a, 0x59, 0x21, 0xe4, 0x7b, 0xb6, 0x2c,
	0x04, 0x4f, 0x9b, 0x54, 0x50, 0x79, 0xd2, 0xb5, 0xd0, 0x41, 0x82, 0x5d, 0xdd, 0xf2, 0xbf, 0xa3,
	0x59, 0xd4, 0xe5, 0xfc, 0x72, 0xda, 0x93, 0x21, 0x68, 0x92, 0xad, 0x49, 0x2d, 0xc9, 0xf8, 0x69,
	0x85, 0xf1, 0x96, 0x65, 0xec, 0x6a, 0x22, 0xcd, 0x1d, 0xdd, 0xe4, 0x41, 0x06, 0x9b, 0xba, 0x8f,
	0x79, 0x80, 0x68, 0x8d, 0xf9, 0x0f, 0x10, 0xad, 0x85, 0xeb, 0xff, 0x4a, 0xbb, 0xb6, 0x5d, 0xc6,
	0xe2, 0x00, 0x8a, 0xde, 0x44, 0x77, 0x0d, 0x0d, 0x07, 0x4c, 0x38, 0xaf, 0x0c, 0x0b, 0xd8, 0x8c,
	0x61, 0x16, 0x98, 0x9f, 0x31, 0x8c, 0x1a, 0x12, 0xf8, 0xab, 0x26, 0xf0, 0x81, 0xe7, 0x89, 0xf4,
	0x96, 0xbe, 0xea, 0x30, 0x76, 0xca, 0x50, 0x05, 0xd3, 0x3a, 0xa7, 0x65, 0x92, 0x8c, 0xbf, 0x7e,
	0x34, 0xa6, 0x75, 0x8e, 0x8b, 0x8b, 0x56, 0x16, 0xb1, 0x6b, 0x37, 0x65, 0x68, 0x2c, 0xf8, 0x89,
	0x69, 0xd1, 0x32, 0x5e, 0x66, 0x3d, 0x96, 0xb2, 0xcc, 0x10, 0x30, 0xf1, 0xea, 0x10, 0xd0, 0x58,
	0xf0, 0x0b, 0x93, 0x29, 0xe1, 0x65, 0xd3, 0xcc, 0xe9, 0xa7, 0xc6, 0x34, 0xe3, 0x6d, 0x91, 0x65,
	0x98, 0x63, 0xfa, 0x21, 0x84, 0x92, 0xed, 0x2a, 0x2a, 0x9f, 0xcf, 0xef, 0x2a, 0x2a, 0xaa, 0x68,
	0xbe, 0x5d, 0xb2, 0x6e, 0x9b, 0x6f, 0x88, 0x4e, 0xa8, 0x7c, 0x4e, 0xdc, 0xca, 0xf1, 0xff, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xab, 0x36, 0x3c, 0x49, 0x5a, 0x16, 0x00, 0x00,
}
