// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db_hallsvr.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db_hallsvr.proto

It has these top-level messages:
	SmallRankRecord
	LimitShopItem
	PlayerInfo
	PlayerGlobal
	PlayerRole
	PlayerRoleList
	PlayerBattleTeam
	PlayerStage
	PlayerStageList
	PlayerChapterUnLock
	PlayerItem
	PlayerItemList
	PlayerShopItem
	PlayerShopItemList
	PlayerShopLimitedInfo
	PlayerShopLimitedInfoList
	PlayerChest
	PlayerChestList
	PlayerMail
	PlayerMailList
	PlayerDialyTask
	PlayerDialyTaskList
	PlayerAchieve
	PlayerAchieveList
	PlayerFinishedAchieve
	PlayerFinishedAchieveList
	PlayerDailyTaskWholeDaily
	PlayerDailyTaskWholeDailyList
	PlayerSevenActivity
	PlayerSevenActivityList
	PlayerGuides
	PlayerGuidesList
	PlayerFriendRelative
	PlayerFriend
	PlayerFriendList
	PlayerFriendReq
	PlayerFriendReqList
	PlayerFriendPoint
	PlayerFriendPointList
	PlayerFriendChatUnreadId
	PlayerFriendChatUnreadIdList
	PlayerFriendChatUnreadMessage
	PlayerFriendChatUnreadMessageList
	PlayerChaterOpenRequest
	PlayerHandbookItem
	PlayerHandbookItemList
	PlayerHeadItem
	PlayerHeadItemList
	PlayerSuitAward
	PlayerSuitAwardList
	PlayerWorldChat
	PlayerAnouncement
	PlayerFirstDrawCard
	PlayerFirstDrawCardList
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SmallRankRecord struct {
	Rank             *int32  `protobuf:"varint,1,opt,name=Rank" json:"Rank,omitempty"`
	Id               *int32  `protobuf:"varint,2,opt,name=Id" json:"Id,omitempty"`
	Val              *int32  `protobuf:"varint,3,opt,name=Val" json:"Val,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SmallRankRecord) Reset()                    { *m = SmallRankRecord{} }
func (m *SmallRankRecord) String() string            { return proto.CompactTextString(m) }
func (*SmallRankRecord) ProtoMessage()               {}
func (*SmallRankRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SmallRankRecord) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *SmallRankRecord) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SmallRankRecord) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

func (m *SmallRankRecord) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type LimitShopItem struct {
	CommodityId      *int32 `protobuf:"varint,1,opt,name=CommodityId" json:"CommodityId,omitempty"`
	LeftNum          *int32 `protobuf:"varint,2,opt,name=LeftNum" json:"LeftNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LimitShopItem) Reset()                    { *m = LimitShopItem{} }
func (m *LimitShopItem) String() string            { return proto.CompactTextString(m) }
func (*LimitShopItem) ProtoMessage()               {}
func (*LimitShopItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LimitShopItem) GetCommodityId() int32 {
	if m != nil && m.CommodityId != nil {
		return *m.CommodityId
	}
	return 0
}

func (m *LimitShopItem) GetLeftNum() int32 {
	if m != nil && m.LeftNum != nil {
		return *m.LeftNum
	}
	return 0
}

type PlayerInfo struct {
	Lvl                       *int32  `protobuf:"varint,1,opt,name=Lvl" json:"Lvl,omitempty"`
	Exp                       *int32  `protobuf:"varint,2,opt,name=Exp" json:"Exp,omitempty"`
	CreateUnix                *int32  `protobuf:"varint,3,opt,name=CreateUnix" json:"CreateUnix,omitempty"`
	FirstPayState             *int32  `protobuf:"varint,4,opt,name=FirstPayState" json:"FirstPayState,omitempty"`
	ChangeNameCount           *int32  `protobuf:"varint,5,opt,name=ChangeNameCount" json:"ChangeNameCount,omitempty"`
	LastDialyTaskUpUinx       *int32  `protobuf:"varint,6,opt,name=LastDialyTaskUpUinx" json:"LastDialyTaskUpUinx,omitempty"`
	Icon                      *string `protobuf:"bytes,7,opt,name=Icon" json:"Icon,omitempty"`
	CustomIcon                *string `protobuf:"bytes,8,opt,name=CustomIcon" json:"CustomIcon,omitempty"`
	CharmVal                  *int32  `protobuf:"varint,9,opt,name=CharmVal" json:"CharmVal,omitempty"`
	LastLogin                 *int32  `protobuf:"varint,10,opt,name=LastLogin" json:"LastLogin,omitempty"`
	Zan                       *int32  `protobuf:"varint,11,opt,name=Zan" json:"Zan,omitempty"`
	Spirit                    *int32  `protobuf:"varint,12,opt,name=Spirit" json:"Spirit,omitempty"`
	FriendPoints              *int32  `protobuf:"varint,13,opt,name=FriendPoints" json:"FriendPoints,omitempty"`
	SaveLastSpiritPointTime   *int32  `protobuf:"varint,14,opt,name=SaveLastSpiritPointTime" json:"SaveLastSpiritPointTime,omitempty"`
	LastRefreshShopTime       *int32  `protobuf:"varint,15,opt,name=LastRefreshShopTime" json:"LastRefreshShopTime,omitempty"`
	VipLvl                    *int32  `protobuf:"varint,16,opt,name=VipLvl" json:"VipLvl,omitempty"`
	FriendMessageUnreadCurrId *int32  `protobuf:"varint,17,opt,name=FriendMessageUnreadCurrId" json:"FriendMessageUnreadCurrId,omitempty"`
	XXX_unrecognized          []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerInfo) GetLvl() int32 {
	if m != nil && m.Lvl != nil {
		return *m.Lvl
	}
	return 0
}

func (m *PlayerInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *PlayerInfo) GetCreateUnix() int32 {
	if m != nil && m.CreateUnix != nil {
		return *m.CreateUnix
	}
	return 0
}

func (m *PlayerInfo) GetFirstPayState() int32 {
	if m != nil && m.FirstPayState != nil {
		return *m.FirstPayState
	}
	return 0
}

func (m *PlayerInfo) GetChangeNameCount() int32 {
	if m != nil && m.ChangeNameCount != nil {
		return *m.ChangeNameCount
	}
	return 0
}

func (m *PlayerInfo) GetLastDialyTaskUpUinx() int32 {
	if m != nil && m.LastDialyTaskUpUinx != nil {
		return *m.LastDialyTaskUpUinx
	}
	return 0
}

func (m *PlayerInfo) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *PlayerInfo) GetCustomIcon() string {
	if m != nil && m.CustomIcon != nil {
		return *m.CustomIcon
	}
	return ""
}

func (m *PlayerInfo) GetCharmVal() int32 {
	if m != nil && m.CharmVal != nil {
		return *m.CharmVal
	}
	return 0
}

func (m *PlayerInfo) GetLastLogin() int32 {
	if m != nil && m.LastLogin != nil {
		return *m.LastLogin
	}
	return 0
}

func (m *PlayerInfo) GetZan() int32 {
	if m != nil && m.Zan != nil {
		return *m.Zan
	}
	return 0
}

func (m *PlayerInfo) GetSpirit() int32 {
	if m != nil && m.Spirit != nil {
		return *m.Spirit
	}
	return 0
}

func (m *PlayerInfo) GetFriendPoints() int32 {
	if m != nil && m.FriendPoints != nil {
		return *m.FriendPoints
	}
	return 0
}

func (m *PlayerInfo) GetSaveLastSpiritPointTime() int32 {
	if m != nil && m.SaveLastSpiritPointTime != nil {
		return *m.SaveLastSpiritPointTime
	}
	return 0
}

func (m *PlayerInfo) GetLastRefreshShopTime() int32 {
	if m != nil && m.LastRefreshShopTime != nil {
		return *m.LastRefreshShopTime
	}
	return 0
}

func (m *PlayerInfo) GetVipLvl() int32 {
	if m != nil && m.VipLvl != nil {
		return *m.VipLvl
	}
	return 0
}

func (m *PlayerInfo) GetFriendMessageUnreadCurrId() int32 {
	if m != nil && m.FriendMessageUnreadCurrId != nil {
		return *m.FriendMessageUnreadCurrId
	}
	return 0
}

type PlayerGlobal struct {
	CurrentRoleId    *int32 `protobuf:"varint,1,opt,name=CurrentRoleId" json:"CurrentRoleId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerGlobal) Reset()                    { *m = PlayerGlobal{} }
func (m *PlayerGlobal) String() string            { return proto.CompactTextString(m) }
func (*PlayerGlobal) ProtoMessage()               {}
func (*PlayerGlobal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PlayerGlobal) GetCurrentRoleId() int32 {
	if m != nil && m.CurrentRoleId != nil {
		return *m.CurrentRoleId
	}
	return 0
}

type PlayerRole struct {
	Id               *int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	TableId          *int32  `protobuf:"varint,2,opt,name=TableId" json:"TableId,omitempty"`
	Rank             *int32  `protobuf:"varint,3,opt,name=Rank" json:"Rank,omitempty"`
	Level            *int32  `protobuf:"varint,4,opt,name=Level" json:"Level,omitempty"`
	Attr             []int32 `protobuf:"varint,5,rep,name=Attr" json:"Attr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerRole) Reset()                    { *m = PlayerRole{} }
func (m *PlayerRole) String() string            { return proto.CompactTextString(m) }
func (*PlayerRole) ProtoMessage()               {}
func (*PlayerRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerRole) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerRole) GetTableId() int32 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *PlayerRole) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *PlayerRole) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerRole) GetAttr() []int32 {
	if m != nil {
		return m.Attr
	}
	return nil
}

type PlayerRoleList struct {
	List             []*PlayerRole `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerRoleList) Reset()                    { *m = PlayerRoleList{} }
func (m *PlayerRoleList) String() string            { return proto.CompactTextString(m) }
func (*PlayerRoleList) ProtoMessage()               {}
func (*PlayerRoleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerRoleList) GetList() []*PlayerRole {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerBattleTeam struct {
	AttackMembers    []int32 `protobuf:"varint,1,rep,name=AttackMembers" json:"AttackMembers,omitempty"`
	DefenseMembers   []int32 `protobuf:"varint,2,rep,name=DefenseMembers" json:"DefenseMembers,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerBattleTeam) Reset()                    { *m = PlayerBattleTeam{} }
func (m *PlayerBattleTeam) String() string            { return proto.CompactTextString(m) }
func (*PlayerBattleTeam) ProtoMessage()               {}
func (*PlayerBattleTeam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlayerBattleTeam) GetAttackMembers() []int32 {
	if m != nil {
		return m.AttackMembers
	}
	return nil
}

func (m *PlayerBattleTeam) GetDefenseMembers() []int32 {
	if m != nil {
		return m.DefenseMembers
	}
	return nil
}

type PlayerStage struct {
	StageId          *int32 `protobuf:"varint,1,opt,name=StageId" json:"StageId,omitempty"`
	Stars            *int32 `protobuf:"varint,2,opt,name=Stars" json:"Stars,omitempty"`
	LastFinishedUnix *int32 `protobuf:"varint,3,opt,name=LastFinishedUnix" json:"LastFinishedUnix,omitempty"`
	TopScore         *int32 `protobuf:"varint,4,opt,name=TopScore" json:"TopScore,omitempty"`
	CatId            *int32 `protobuf:"varint,5,opt,name=CatId" json:"CatId,omitempty"`
	PlayedCount      *int32 `protobuf:"varint,6,opt,name=PlayedCount" json:"PlayedCount,omitempty"`
	PassCount        *int32 `protobuf:"varint,7,opt,name=PassCount" json:"PassCount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerStage) Reset()                    { *m = PlayerStage{} }
func (m *PlayerStage) String() string            { return proto.CompactTextString(m) }
func (*PlayerStage) ProtoMessage()               {}
func (*PlayerStage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PlayerStage) GetStageId() int32 {
	if m != nil && m.StageId != nil {
		return *m.StageId
	}
	return 0
}

func (m *PlayerStage) GetStars() int32 {
	if m != nil && m.Stars != nil {
		return *m.Stars
	}
	return 0
}

func (m *PlayerStage) GetLastFinishedUnix() int32 {
	if m != nil && m.LastFinishedUnix != nil {
		return *m.LastFinishedUnix
	}
	return 0
}

func (m *PlayerStage) GetTopScore() int32 {
	if m != nil && m.TopScore != nil {
		return *m.TopScore
	}
	return 0
}

func (m *PlayerStage) GetCatId() int32 {
	if m != nil && m.CatId != nil {
		return *m.CatId
	}
	return 0
}

func (m *PlayerStage) GetPlayedCount() int32 {
	if m != nil && m.PlayedCount != nil {
		return *m.PlayedCount
	}
	return 0
}

func (m *PlayerStage) GetPassCount() int32 {
	if m != nil && m.PassCount != nil {
		return *m.PassCount
	}
	return 0
}

type PlayerStageList struct {
	List             []*PlayerStage `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PlayerStageList) Reset()                    { *m = PlayerStageList{} }
func (m *PlayerStageList) String() string            { return proto.CompactTextString(m) }
func (*PlayerStageList) ProtoMessage()               {}
func (*PlayerStageList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PlayerStageList) GetList() []*PlayerStage {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerChapterUnLock struct {
	ChapterId        *int32  `protobuf:"varint,1,opt,name=ChapterId" json:"ChapterId,omitempty"`
	PlayerIds        []int32 `protobuf:"varint,2,rep,name=PlayerIds" json:"PlayerIds,omitempty"`
	CurHelpIds       []int32 `protobuf:"varint,3,rep,name=CurHelpIds" json:"CurHelpIds,omitempty"`
	StartUnix        *int32  `protobuf:"varint,4,opt,name=StartUnix" json:"StartUnix,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerChapterUnLock) Reset()                    { *m = PlayerChapterUnLock{} }
func (m *PlayerChapterUnLock) String() string            { return proto.CompactTextString(m) }
func (*PlayerChapterUnLock) ProtoMessage()               {}
func (*PlayerChapterUnLock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PlayerChapterUnLock) GetChapterId() int32 {
	if m != nil && m.ChapterId != nil {
		return *m.ChapterId
	}
	return 0
}

func (m *PlayerChapterUnLock) GetPlayerIds() []int32 {
	if m != nil {
		return m.PlayerIds
	}
	return nil
}

func (m *PlayerChapterUnLock) GetCurHelpIds() []int32 {
	if m != nil {
		return m.CurHelpIds
	}
	return nil
}

func (m *PlayerChapterUnLock) GetStartUnix() int32 {
	if m != nil && m.StartUnix != nil {
		return *m.StartUnix
	}
	return 0
}

type PlayerItem struct {
	ItemCfgId        *int32 `protobuf:"varint,1,opt,name=ItemCfgId" json:"ItemCfgId,omitempty"`
	ItemNum          *int32 `protobuf:"varint,2,opt,name=ItemNum" json:"ItemNum,omitempty"`
	StartTimeUnix    *int32 `protobuf:"varint,3,opt,name=StartTimeUnix" json:"StartTimeUnix,omitempty"`
	RemainSeconds    *int32 `protobuf:"varint,4,opt,name=RemainSeconds" json:"RemainSeconds,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerItem) Reset()                    { *m = PlayerItem{} }
func (m *PlayerItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerItem) ProtoMessage()               {}
func (*PlayerItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PlayerItem) GetItemCfgId() int32 {
	if m != nil && m.ItemCfgId != nil {
		return *m.ItemCfgId
	}
	return 0
}

func (m *PlayerItem) GetItemNum() int32 {
	if m != nil && m.ItemNum != nil {
		return *m.ItemNum
	}
	return 0
}

func (m *PlayerItem) GetStartTimeUnix() int32 {
	if m != nil && m.StartTimeUnix != nil {
		return *m.StartTimeUnix
	}
	return 0
}

func (m *PlayerItem) GetRemainSeconds() int32 {
	if m != nil && m.RemainSeconds != nil {
		return *m.RemainSeconds
	}
	return 0
}

type PlayerItemList struct {
	List             []*PlayerItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerItemList) Reset()                    { *m = PlayerItemList{} }
func (m *PlayerItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerItemList) ProtoMessage()               {}
func (*PlayerItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PlayerItemList) GetList() []*PlayerItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerShopItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	LeftNum          *int32 `protobuf:"varint,2,opt,name=LeftNum" json:"LeftNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerShopItem) Reset()                    { *m = PlayerShopItem{} }
func (m *PlayerShopItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopItem) ProtoMessage()               {}
func (*PlayerShopItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PlayerShopItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerShopItem) GetLeftNum() int32 {
	if m != nil && m.LeftNum != nil {
		return *m.LeftNum
	}
	return 0
}

type PlayerShopItemList struct {
	List             []*PlayerShopItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PlayerShopItemList) Reset()                    { *m = PlayerShopItemList{} }
func (m *PlayerShopItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopItemList) ProtoMessage()               {}
func (*PlayerShopItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PlayerShopItemList) GetList() []*PlayerShopItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerShopLimitedInfo struct {
	LimitedDays      *int32 `protobuf:"varint,1,opt,name=LimitedDays" json:"LimitedDays,omitempty"`
	LastSaveTime     *int32 `protobuf:"varint,2,opt,name=LastSaveTime" json:"LastSaveTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerShopLimitedInfo) Reset()                    { *m = PlayerShopLimitedInfo{} }
func (m *PlayerShopLimitedInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopLimitedInfo) ProtoMessage()               {}
func (*PlayerShopLimitedInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PlayerShopLimitedInfo) GetLimitedDays() int32 {
	if m != nil && m.LimitedDays != nil {
		return *m.LimitedDays
	}
	return 0
}

func (m *PlayerShopLimitedInfo) GetLastSaveTime() int32 {
	if m != nil && m.LastSaveTime != nil {
		return *m.LastSaveTime
	}
	return 0
}

type PlayerShopLimitedInfoList struct {
	List             []*PlayerShopLimitedInfo `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *PlayerShopLimitedInfoList) Reset()                    { *m = PlayerShopLimitedInfoList{} }
func (m *PlayerShopLimitedInfoList) String() string            { return proto.CompactTextString(m) }
func (*PlayerShopLimitedInfoList) ProtoMessage()               {}
func (*PlayerShopLimitedInfoList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PlayerShopLimitedInfoList) GetList() []*PlayerShopLimitedInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerChest struct {
	Pos              *int32 `protobuf:"varint,1,opt,name=Pos" json:"Pos,omitempty"`
	ChestId          *int32 `protobuf:"varint,2,opt,name=ChestId" json:"ChestId,omitempty"`
	OpenSec          *int32 `protobuf:"varint,3,opt,name=OpenSec" json:"OpenSec,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerChest) Reset()                    { *m = PlayerChest{} }
func (m *PlayerChest) String() string            { return proto.CompactTextString(m) }
func (*PlayerChest) ProtoMessage()               {}
func (*PlayerChest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PlayerChest) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *PlayerChest) GetChestId() int32 {
	if m != nil && m.ChestId != nil {
		return *m.ChestId
	}
	return 0
}

func (m *PlayerChest) GetOpenSec() int32 {
	if m != nil && m.OpenSec != nil {
		return *m.OpenSec
	}
	return 0
}

type PlayerChestList struct {
	List             []*PlayerChest `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PlayerChestList) Reset()                    { *m = PlayerChestList{} }
func (m *PlayerChestList) String() string            { return proto.CompactTextString(m) }
func (*PlayerChestList) ProtoMessage()               {}
func (*PlayerChestList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PlayerChestList) GetList() []*PlayerChest {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerMail struct {
	MailId           *int32  `protobuf:"varint,1,opt,name=MailId" json:"MailId,omitempty"`
	MailType         *int32  `protobuf:"varint,2,opt,name=MailType" json:"MailType,omitempty"`
	MailTitle        *string `protobuf:"bytes,3,opt,name=MailTitle" json:"MailTitle,omitempty"`
	SenderId         *int32  `protobuf:"varint,4,opt,name=SenderId" json:"SenderId,omitempty"`
	SenderName       *string `protobuf:"bytes,5,opt,name=SenderName" json:"SenderName,omitempty"`
	Content          *string `protobuf:"bytes,6,opt,name=Content" json:"Content,omitempty"`
	SendUnix         *int32  `protobuf:"varint,7,opt,name=SendUnix" json:"SendUnix,omitempty"`
	OverUnix         *int32  `protobuf:"varint,8,opt,name=OverUnix" json:"OverUnix,omitempty"`
	ObjIds           []int32 `protobuf:"varint,9,rep,name=ObjIds" json:"ObjIds,omitempty"`
	ObjNums          []int32 `protobuf:"varint,10,rep,name=ObjNums" json:"ObjNums,omitempty"`
	State            *int32  `protobuf:"varint,11,opt,name=State" json:"State,omitempty"`
	ExtraDatas       []int32 `protobuf:"varint,12,rep,name=ExtraDatas" json:"ExtraDatas,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerMail) Reset()                    { *m = PlayerMail{} }
func (m *PlayerMail) String() string            { return proto.CompactTextString(m) }
func (*PlayerMail) ProtoMessage()               {}
func (*PlayerMail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PlayerMail) GetMailId() int32 {
	if m != nil && m.MailId != nil {
		return *m.MailId
	}
	return 0
}

func (m *PlayerMail) GetMailType() int32 {
	if m != nil && m.MailType != nil {
		return *m.MailType
	}
	return 0
}

func (m *PlayerMail) GetMailTitle() string {
	if m != nil && m.MailTitle != nil {
		return *m.MailTitle
	}
	return ""
}

func (m *PlayerMail) GetSenderId() int32 {
	if m != nil && m.SenderId != nil {
		return *m.SenderId
	}
	return 0
}

func (m *PlayerMail) GetSenderName() string {
	if m != nil && m.SenderName != nil {
		return *m.SenderName
	}
	return ""
}

func (m *PlayerMail) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *PlayerMail) GetSendUnix() int32 {
	if m != nil && m.SendUnix != nil {
		return *m.SendUnix
	}
	return 0
}

func (m *PlayerMail) GetOverUnix() int32 {
	if m != nil && m.OverUnix != nil {
		return *m.OverUnix
	}
	return 0
}

func (m *PlayerMail) GetObjIds() []int32 {
	if m != nil {
		return m.ObjIds
	}
	return nil
}

func (m *PlayerMail) GetObjNums() []int32 {
	if m != nil {
		return m.ObjNums
	}
	return nil
}

func (m *PlayerMail) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *PlayerMail) GetExtraDatas() []int32 {
	if m != nil {
		return m.ExtraDatas
	}
	return nil
}

type PlayerMailList struct {
	List             []*PlayerMail `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PlayerMailList) Reset()                    { *m = PlayerMailList{} }
func (m *PlayerMailList) String() string            { return proto.CompactTextString(m) }
func (*PlayerMailList) ProtoMessage()               {}
func (*PlayerMailList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PlayerMailList) GetList() []*PlayerMail {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerDialyTask struct {
	TaskId           *int32 `protobuf:"varint,1,opt,name=TaskId" json:"TaskId,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	RewardUnix       *int32 `protobuf:"varint,3,opt,name=RewardUnix" json:"RewardUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerDialyTask) Reset()                    { *m = PlayerDialyTask{} }
func (m *PlayerDialyTask) String() string            { return proto.CompactTextString(m) }
func (*PlayerDialyTask) ProtoMessage()               {}
func (*PlayerDialyTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *PlayerDialyTask) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *PlayerDialyTask) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *PlayerDialyTask) GetRewardUnix() int32 {
	if m != nil && m.RewardUnix != nil {
		return *m.RewardUnix
	}
	return 0
}

type PlayerDialyTaskList struct {
	List             []*PlayerDialyTask `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PlayerDialyTaskList) Reset()                    { *m = PlayerDialyTaskList{} }
func (m *PlayerDialyTaskList) String() string            { return proto.CompactTextString(m) }
func (*PlayerDialyTaskList) ProtoMessage()               {}
func (*PlayerDialyTaskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PlayerDialyTaskList) GetList() []*PlayerDialyTask {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerAchieve struct {
	AchieveId        *int32 `protobuf:"varint,1,opt,name=AchieveId" json:"AchieveId,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	RewardUnix       *int32 `protobuf:"varint,3,opt,name=RewardUnix" json:"RewardUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerAchieve) Reset()                    { *m = PlayerAchieve{} }
func (m *PlayerAchieve) String() string            { return proto.CompactTextString(m) }
func (*PlayerAchieve) ProtoMessage()               {}
func (*PlayerAchieve) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *PlayerAchieve) GetAchieveId() int32 {
	if m != nil && m.AchieveId != nil {
		return *m.AchieveId
	}
	return 0
}

func (m *PlayerAchieve) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *PlayerAchieve) GetRewardUnix() int32 {
	if m != nil && m.RewardUnix != nil {
		return *m.RewardUnix
	}
	return 0
}

type PlayerAchieveList struct {
	List             []*PlayerAchieve `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PlayerAchieveList) Reset()                    { *m = PlayerAchieveList{} }
func (m *PlayerAchieveList) String() string            { return proto.CompactTextString(m) }
func (*PlayerAchieveList) ProtoMessage()               {}
func (*PlayerAchieveList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *PlayerAchieveList) GetList() []*PlayerAchieve {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFinishedAchieve struct {
	AchieveId        *int32 `protobuf:"varint,1,opt,name=AchieveId" json:"AchieveId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFinishedAchieve) Reset()                    { *m = PlayerFinishedAchieve{} }
func (m *PlayerFinishedAchieve) String() string            { return proto.CompactTextString(m) }
func (*PlayerFinishedAchieve) ProtoMessage()               {}
func (*PlayerFinishedAchieve) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *PlayerFinishedAchieve) GetAchieveId() int32 {
	if m != nil && m.AchieveId != nil {
		return *m.AchieveId
	}
	return 0
}

type PlayerFinishedAchieveList struct {
	List             []*PlayerFinishedAchieve `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *PlayerFinishedAchieveList) Reset()                    { *m = PlayerFinishedAchieveList{} }
func (m *PlayerFinishedAchieveList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFinishedAchieveList) ProtoMessage()               {}
func (*PlayerFinishedAchieveList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *PlayerFinishedAchieveList) GetList() []*PlayerFinishedAchieve {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerDailyTaskWholeDaily struct {
	CompleteTaskId   *int32 `protobuf:"varint,1,opt,name=CompleteTaskId" json:"CompleteTaskId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerDailyTaskWholeDaily) Reset()                    { *m = PlayerDailyTaskWholeDaily{} }
func (m *PlayerDailyTaskWholeDaily) String() string            { return proto.CompactTextString(m) }
func (*PlayerDailyTaskWholeDaily) ProtoMessage()               {}
func (*PlayerDailyTaskWholeDaily) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *PlayerDailyTaskWholeDaily) GetCompleteTaskId() int32 {
	if m != nil && m.CompleteTaskId != nil {
		return *m.CompleteTaskId
	}
	return 0
}

type PlayerDailyTaskWholeDailyList struct {
	List             []*PlayerDailyTaskWholeDaily `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PlayerDailyTaskWholeDailyList) Reset()                    { *m = PlayerDailyTaskWholeDailyList{} }
func (m *PlayerDailyTaskWholeDailyList) String() string            { return proto.CompactTextString(m) }
func (*PlayerDailyTaskWholeDailyList) ProtoMessage()               {}
func (*PlayerDailyTaskWholeDailyList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *PlayerDailyTaskWholeDailyList) GetList() []*PlayerDailyTaskWholeDaily {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerSevenActivity struct {
	ActivityId       *int32 `protobuf:"varint,1,opt,name=ActivityId" json:"ActivityId,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	RewardUnix       *int32 `protobuf:"varint,3,opt,name=RewardUnix" json:"RewardUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerSevenActivity) Reset()                    { *m = PlayerSevenActivity{} }
func (m *PlayerSevenActivity) String() string            { return proto.CompactTextString(m) }
func (*PlayerSevenActivity) ProtoMessage()               {}
func (*PlayerSevenActivity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *PlayerSevenActivity) GetActivityId() int32 {
	if m != nil && m.ActivityId != nil {
		return *m.ActivityId
	}
	return 0
}

func (m *PlayerSevenActivity) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *PlayerSevenActivity) GetRewardUnix() int32 {
	if m != nil && m.RewardUnix != nil {
		return *m.RewardUnix
	}
	return 0
}

type PlayerSevenActivityList struct {
	List             []*PlayerSevenActivity `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PlayerSevenActivityList) Reset()                    { *m = PlayerSevenActivityList{} }
func (m *PlayerSevenActivityList) String() string            { return proto.CompactTextString(m) }
func (*PlayerSevenActivityList) ProtoMessage()               {}
func (*PlayerSevenActivityList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *PlayerSevenActivityList) GetList() []*PlayerSevenActivity {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerGuides struct {
	GuideId          *int32 `protobuf:"varint,1,opt,name=GuideId" json:"GuideId,omitempty"`
	SetUnix          *int32 `protobuf:"varint,2,opt,name=SetUnix" json:"SetUnix,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerGuides) Reset()                    { *m = PlayerGuides{} }
func (m *PlayerGuides) String() string            { return proto.CompactTextString(m) }
func (*PlayerGuides) ProtoMessage()               {}
func (*PlayerGuides) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *PlayerGuides) GetGuideId() int32 {
	if m != nil && m.GuideId != nil {
		return *m.GuideId
	}
	return 0
}

func (m *PlayerGuides) GetSetUnix() int32 {
	if m != nil && m.SetUnix != nil {
		return *m.SetUnix
	}
	return 0
}

type PlayerGuidesList struct {
	List             []*PlayerGuides `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PlayerGuidesList) Reset()                    { *m = PlayerGuidesList{} }
func (m *PlayerGuidesList) String() string            { return proto.CompactTextString(m) }
func (*PlayerGuidesList) ProtoMessage()               {}
func (*PlayerGuidesList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *PlayerGuidesList) GetList() []*PlayerGuides {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendRelative struct {
	LastGiveFriendPointsTime *int32 `protobuf:"varint,1,opt,name=LastGiveFriendPointsTime" json:"LastGiveFriendPointsTime,omitempty"`
	GiveNumToday             *int32 `protobuf:"varint,2,opt,name=GiveNumToday" json:"GiveNumToday,omitempty"`
	LastRefreshTime          *int32 `protobuf:"varint,3,opt,name=LastRefreshTime" json:"LastRefreshTime,omitempty"`
	XXX_unrecognized         []byte `json:"-"`
}

func (m *PlayerFriendRelative) Reset()                    { *m = PlayerFriendRelative{} }
func (m *PlayerFriendRelative) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendRelative) ProtoMessage()               {}
func (*PlayerFriendRelative) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *PlayerFriendRelative) GetLastGiveFriendPointsTime() int32 {
	if m != nil && m.LastGiveFriendPointsTime != nil {
		return *m.LastGiveFriendPointsTime
	}
	return 0
}

func (m *PlayerFriendRelative) GetGiveNumToday() int32 {
	if m != nil && m.GiveNumToday != nil {
		return *m.GiveNumToday
	}
	return 0
}

func (m *PlayerFriendRelative) GetLastRefreshTime() int32 {
	if m != nil && m.LastRefreshTime != nil {
		return *m.LastRefreshTime
	}
	return 0
}

type PlayerFriend struct {
	FriendId           *int32  `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	FriendName         *string `protobuf:"bytes,2,opt,name=FriendName" json:"FriendName,omitempty"`
	Head               *string `protobuf:"bytes,3,opt,name=Head" json:"Head,omitempty"`
	Level              *int32  `protobuf:"varint,4,opt,name=Level" json:"Level,omitempty"`
	VipLevel           *int32  `protobuf:"varint,5,opt,name=VipLevel" json:"VipLevel,omitempty"`
	LastLogin          *int32  `protobuf:"varint,6,opt,name=LastLogin" json:"LastLogin,omitempty"`
	LastGivePointsTime *int32  `protobuf:"varint,7,opt,name=LastGivePointsTime" json:"LastGivePointsTime,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *PlayerFriend) Reset()                    { *m = PlayerFriend{} }
func (m *PlayerFriend) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriend) ProtoMessage()               {}
func (*PlayerFriend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *PlayerFriend) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

func (m *PlayerFriend) GetFriendName() string {
	if m != nil && m.FriendName != nil {
		return *m.FriendName
	}
	return ""
}

func (m *PlayerFriend) GetHead() string {
	if m != nil && m.Head != nil {
		return *m.Head
	}
	return ""
}

func (m *PlayerFriend) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerFriend) GetVipLevel() int32 {
	if m != nil && m.VipLevel != nil {
		return *m.VipLevel
	}
	return 0
}

func (m *PlayerFriend) GetLastLogin() int32 {
	if m != nil && m.LastLogin != nil {
		return *m.LastLogin
	}
	return 0
}

func (m *PlayerFriend) GetLastGivePointsTime() int32 {
	if m != nil && m.LastGivePointsTime != nil {
		return *m.LastGivePointsTime
	}
	return 0
}

type PlayerFriendList struct {
	List             []*PlayerFriend `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PlayerFriendList) Reset()                    { *m = PlayerFriendList{} }
func (m *PlayerFriendList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendList) ProtoMessage()               {}
func (*PlayerFriendList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PlayerFriendList) GetList() []*PlayerFriend {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendReq struct {
	PlayerId         *int32  `protobuf:"varint,1,opt,name=PlayerId" json:"PlayerId,omitempty"`
	PlayerName       *string `protobuf:"bytes,2,opt,name=PlayerName" json:"PlayerName,omitempty"`
	ReqUnix          *int32  `protobuf:"varint,3,opt,name=ReqUnix" json:"ReqUnix,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerFriendReq) Reset()                    { *m = PlayerFriendReq{} }
func (m *PlayerFriendReq) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendReq) ProtoMessage()               {}
func (*PlayerFriendReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *PlayerFriendReq) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *PlayerFriendReq) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *PlayerFriendReq) GetReqUnix() int32 {
	if m != nil && m.ReqUnix != nil {
		return *m.ReqUnix
	}
	return 0
}

type PlayerFriendReqList struct {
	List             []*PlayerFriendReq `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PlayerFriendReqList) Reset()                    { *m = PlayerFriendReqList{} }
func (m *PlayerFriendReqList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendReqList) ProtoMessage()               {}
func (*PlayerFriendReqList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *PlayerFriendReqList) GetList() []*PlayerFriendReq {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendPoint struct {
	FromPlayerId     *int32 `protobuf:"varint,1,opt,name=FromPlayerId" json:"FromPlayerId,omitempty"`
	GivePoints       *int32 `protobuf:"varint,2,opt,name=GivePoints" json:"GivePoints,omitempty"`
	LastGiveTime     *int32 `protobuf:"varint,3,opt,name=LastGiveTime" json:"LastGiveTime,omitempty"`
	IsTodayGive      *int32 `protobuf:"varint,4,opt,name=IsTodayGive" json:"IsTodayGive,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFriendPoint) Reset()                    { *m = PlayerFriendPoint{} }
func (m *PlayerFriendPoint) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendPoint) ProtoMessage()               {}
func (*PlayerFriendPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *PlayerFriendPoint) GetFromPlayerId() int32 {
	if m != nil && m.FromPlayerId != nil {
		return *m.FromPlayerId
	}
	return 0
}

func (m *PlayerFriendPoint) GetGivePoints() int32 {
	if m != nil && m.GivePoints != nil {
		return *m.GivePoints
	}
	return 0
}

func (m *PlayerFriendPoint) GetLastGiveTime() int32 {
	if m != nil && m.LastGiveTime != nil {
		return *m.LastGiveTime
	}
	return 0
}

func (m *PlayerFriendPoint) GetIsTodayGive() int32 {
	if m != nil && m.IsTodayGive != nil {
		return *m.IsTodayGive
	}
	return 0
}

type PlayerFriendPointList struct {
	List             []*PlayerFriendPoint `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *PlayerFriendPointList) Reset()                    { *m = PlayerFriendPointList{} }
func (m *PlayerFriendPointList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendPointList) ProtoMessage()               {}
func (*PlayerFriendPointList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *PlayerFriendPointList) GetList() []*PlayerFriendPoint {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendChatUnreadId struct {
	FriendId         *int32  `protobuf:"varint,1,opt,name=FriendId" json:"FriendId,omitempty"`
	MessageIds       []int32 `protobuf:"varint,2,rep,name=MessageIds" json:"MessageIds,omitempty"`
	CurrMessageId    *int32  `protobuf:"varint,3,opt,name=CurrMessageId" json:"CurrMessageId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerFriendChatUnreadId) Reset()                    { *m = PlayerFriendChatUnreadId{} }
func (m *PlayerFriendChatUnreadId) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadId) ProtoMessage()               {}
func (*PlayerFriendChatUnreadId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *PlayerFriendChatUnreadId) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

func (m *PlayerFriendChatUnreadId) GetMessageIds() []int32 {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *PlayerFriendChatUnreadId) GetCurrMessageId() int32 {
	if m != nil && m.CurrMessageId != nil {
		return *m.CurrMessageId
	}
	return 0
}

type PlayerFriendChatUnreadIdList struct {
	List             []*PlayerFriendChatUnreadId `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *PlayerFriendChatUnreadIdList) Reset()                    { *m = PlayerFriendChatUnreadIdList{} }
func (m *PlayerFriendChatUnreadIdList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadIdList) ProtoMessage()               {}
func (*PlayerFriendChatUnreadIdList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *PlayerFriendChatUnreadIdList) GetList() []*PlayerFriendChatUnreadId {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerFriendChatUnreadMessage struct {
	PlayerMessageId  *int64 `protobuf:"varint,1,opt,name=PlayerMessageId" json:"PlayerMessageId,omitempty"`
	Message          []byte `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	SendTime         *int32 `protobuf:"varint,3,opt,name=SendTime" json:"SendTime,omitempty"`
	IsRead           *int32 `protobuf:"varint,4,opt,name=IsRead" json:"IsRead,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFriendChatUnreadMessage) Reset()                    { *m = PlayerFriendChatUnreadMessage{} }
func (m *PlayerFriendChatUnreadMessage) String() string            { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadMessage) ProtoMessage()               {}
func (*PlayerFriendChatUnreadMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *PlayerFriendChatUnreadMessage) GetPlayerMessageId() int64 {
	if m != nil && m.PlayerMessageId != nil {
		return *m.PlayerMessageId
	}
	return 0
}

func (m *PlayerFriendChatUnreadMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PlayerFriendChatUnreadMessage) GetSendTime() int32 {
	if m != nil && m.SendTime != nil {
		return *m.SendTime
	}
	return 0
}

func (m *PlayerFriendChatUnreadMessage) GetIsRead() int32 {
	if m != nil && m.IsRead != nil {
		return *m.IsRead
	}
	return 0
}

type PlayerFriendChatUnreadMessageList struct {
	List             []*PlayerFriendChatUnreadMessage `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *PlayerFriendChatUnreadMessageList) Reset()         { *m = PlayerFriendChatUnreadMessageList{} }
func (m *PlayerFriendChatUnreadMessageList) String() string { return proto.CompactTextString(m) }
func (*PlayerFriendChatUnreadMessageList) ProtoMessage()    {}
func (*PlayerFriendChatUnreadMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{42}
}

func (m *PlayerFriendChatUnreadMessageList) GetList() []*PlayerFriendChatUnreadMessage {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerChaterOpenRequest struct {
	CustomData       []byte `protobuf:"bytes,1,opt,name=CustomData" json:"CustomData,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerChaterOpenRequest) Reset()                    { *m = PlayerChaterOpenRequest{} }
func (m *PlayerChaterOpenRequest) String() string            { return proto.CompactTextString(m) }
func (*PlayerChaterOpenRequest) ProtoMessage()               {}
func (*PlayerChaterOpenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *PlayerChaterOpenRequest) GetCustomData() []byte {
	if m != nil {
		return m.CustomData
	}
	return nil
}

type PlayerHandbookItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerHandbookItem) Reset()                    { *m = PlayerHandbookItem{} }
func (m *PlayerHandbookItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerHandbookItem) ProtoMessage()               {}
func (*PlayerHandbookItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *PlayerHandbookItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type PlayerHandbookItemList struct {
	List             []*PlayerHandbookItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PlayerHandbookItemList) Reset()                    { *m = PlayerHandbookItemList{} }
func (m *PlayerHandbookItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerHandbookItemList) ProtoMessage()               {}
func (*PlayerHandbookItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *PlayerHandbookItemList) GetList() []*PlayerHandbookItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerHeadItem struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerHeadItem) Reset()                    { *m = PlayerHeadItem{} }
func (m *PlayerHeadItem) String() string            { return proto.CompactTextString(m) }
func (*PlayerHeadItem) ProtoMessage()               {}
func (*PlayerHeadItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *PlayerHeadItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type PlayerHeadItemList struct {
	List             []*PlayerHeadItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PlayerHeadItemList) Reset()                    { *m = PlayerHeadItemList{} }
func (m *PlayerHeadItemList) String() string            { return proto.CompactTextString(m) }
func (*PlayerHeadItemList) ProtoMessage()               {}
func (*PlayerHeadItemList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *PlayerHeadItemList) GetList() []*PlayerHeadItem {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerSuitAward struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	AwardTime        *int32 `protobuf:"varint,2,opt,name=AwardTime" json:"AwardTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerSuitAward) Reset()                    { *m = PlayerSuitAward{} }
func (m *PlayerSuitAward) String() string            { return proto.CompactTextString(m) }
func (*PlayerSuitAward) ProtoMessage()               {}
func (*PlayerSuitAward) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *PlayerSuitAward) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerSuitAward) GetAwardTime() int32 {
	if m != nil && m.AwardTime != nil {
		return *m.AwardTime
	}
	return 0
}

type PlayerSuitAwardList struct {
	List             []*PlayerSuitAward `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PlayerSuitAwardList) Reset()                    { *m = PlayerSuitAwardList{} }
func (m *PlayerSuitAwardList) String() string            { return proto.CompactTextString(m) }
func (*PlayerSuitAwardList) ProtoMessage()               {}
func (*PlayerSuitAwardList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *PlayerSuitAwardList) GetList() []*PlayerSuitAward {
	if m != nil {
		return m.List
	}
	return nil
}

type PlayerWorldChat struct {
	LastChatTime     *int32 `protobuf:"varint,1,opt,name=LastChatTime" json:"LastChatTime,omitempty"`
	LastPullTime     *int32 `protobuf:"varint,2,opt,name=LastPullTime" json:"LastPullTime,omitempty"`
	LastMsgIndex     *int32 `protobuf:"varint,3,opt,name=LastMsgIndex" json:"LastMsgIndex,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerWorldChat) Reset()                    { *m = PlayerWorldChat{} }
func (m *PlayerWorldChat) String() string            { return proto.CompactTextString(m) }
func (*PlayerWorldChat) ProtoMessage()               {}
func (*PlayerWorldChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *PlayerWorldChat) GetLastChatTime() int32 {
	if m != nil && m.LastChatTime != nil {
		return *m.LastChatTime
	}
	return 0
}

func (m *PlayerWorldChat) GetLastPullTime() int32 {
	if m != nil && m.LastPullTime != nil {
		return *m.LastPullTime
	}
	return 0
}

func (m *PlayerWorldChat) GetLastMsgIndex() int32 {
	if m != nil && m.LastMsgIndex != nil {
		return *m.LastMsgIndex
	}
	return 0
}

type PlayerAnouncement struct {
	LastSendTime     *int32 `protobuf:"varint,1,opt,name=LastSendTime" json:"LastSendTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerAnouncement) Reset()                    { *m = PlayerAnouncement{} }
func (m *PlayerAnouncement) String() string            { return proto.CompactTextString(m) }
func (*PlayerAnouncement) ProtoMessage()               {}
func (*PlayerAnouncement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *PlayerAnouncement) GetLastSendTime() int32 {
	if m != nil && m.LastSendTime != nil {
		return *m.LastSendTime
	}
	return 0
}

type PlayerFirstDrawCard struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Drawed           *int32 `protobuf:"varint,2,opt,name=Drawed" json:"Drawed,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerFirstDrawCard) Reset()                    { *m = PlayerFirstDrawCard{} }
func (m *PlayerFirstDrawCard) String() string            { return proto.CompactTextString(m) }
func (*PlayerFirstDrawCard) ProtoMessage()               {}
func (*PlayerFirstDrawCard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

func (m *PlayerFirstDrawCard) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerFirstDrawCard) GetDrawed() int32 {
	if m != nil && m.Drawed != nil {
		return *m.Drawed
	}
	return 0
}

type PlayerFirstDrawCardList struct {
	List             []*PlayerFirstDrawCard `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PlayerFirstDrawCardList) Reset()                    { *m = PlayerFirstDrawCardList{} }
func (m *PlayerFirstDrawCardList) String() string            { return proto.CompactTextString(m) }
func (*PlayerFirstDrawCardList) ProtoMessage()               {}
func (*PlayerFirstDrawCardList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

func (m *PlayerFirstDrawCardList) GetList() []*PlayerFirstDrawCard {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*SmallRankRecord)(nil), "db.SmallRankRecord")
	proto.RegisterType((*LimitShopItem)(nil), "db.LimitShopItem")
	proto.RegisterType((*PlayerInfo)(nil), "db.PlayerInfo")
	proto.RegisterType((*PlayerGlobal)(nil), "db.PlayerGlobal")
	proto.RegisterType((*PlayerRole)(nil), "db.PlayerRole")
	proto.RegisterType((*PlayerRoleList)(nil), "db.PlayerRoleList")
	proto.RegisterType((*PlayerBattleTeam)(nil), "db.PlayerBattleTeam")
	proto.RegisterType((*PlayerStage)(nil), "db.PlayerStage")
	proto.RegisterType((*PlayerStageList)(nil), "db.PlayerStageList")
	proto.RegisterType((*PlayerChapterUnLock)(nil), "db.PlayerChapterUnLock")
	proto.RegisterType((*PlayerItem)(nil), "db.PlayerItem")
	proto.RegisterType((*PlayerItemList)(nil), "db.PlayerItemList")
	proto.RegisterType((*PlayerShopItem)(nil), "db.PlayerShopItem")
	proto.RegisterType((*PlayerShopItemList)(nil), "db.PlayerShopItemList")
	proto.RegisterType((*PlayerShopLimitedInfo)(nil), "db.PlayerShopLimitedInfo")
	proto.RegisterType((*PlayerShopLimitedInfoList)(nil), "db.PlayerShopLimitedInfoList")
	proto.RegisterType((*PlayerChest)(nil), "db.PlayerChest")
	proto.RegisterType((*PlayerChestList)(nil), "db.PlayerChestList")
	proto.RegisterType((*PlayerMail)(nil), "db.PlayerMail")
	proto.RegisterType((*PlayerMailList)(nil), "db.PlayerMailList")
	proto.RegisterType((*PlayerDialyTask)(nil), "db.PlayerDialyTask")
	proto.RegisterType((*PlayerDialyTaskList)(nil), "db.PlayerDialyTaskList")
	proto.RegisterType((*PlayerAchieve)(nil), "db.PlayerAchieve")
	proto.RegisterType((*PlayerAchieveList)(nil), "db.PlayerAchieveList")
	proto.RegisterType((*PlayerFinishedAchieve)(nil), "db.PlayerFinishedAchieve")
	proto.RegisterType((*PlayerFinishedAchieveList)(nil), "db.PlayerFinishedAchieveList")
	proto.RegisterType((*PlayerDailyTaskWholeDaily)(nil), "db.PlayerDailyTaskWholeDaily")
	proto.RegisterType((*PlayerDailyTaskWholeDailyList)(nil), "db.PlayerDailyTaskWholeDailyList")
	proto.RegisterType((*PlayerSevenActivity)(nil), "db.PlayerSevenActivity")
	proto.RegisterType((*PlayerSevenActivityList)(nil), "db.PlayerSevenActivityList")
	proto.RegisterType((*PlayerGuides)(nil), "db.PlayerGuides")
	proto.RegisterType((*PlayerGuidesList)(nil), "db.PlayerGuidesList")
	proto.RegisterType((*PlayerFriendRelative)(nil), "db.PlayerFriendRelative")
	proto.RegisterType((*PlayerFriend)(nil), "db.PlayerFriend")
	proto.RegisterType((*PlayerFriendList)(nil), "db.PlayerFriendList")
	proto.RegisterType((*PlayerFriendReq)(nil), "db.PlayerFriendReq")
	proto.RegisterType((*PlayerFriendReqList)(nil), "db.PlayerFriendReqList")
	proto.RegisterType((*PlayerFriendPoint)(nil), "db.PlayerFriendPoint")
	proto.RegisterType((*PlayerFriendPointList)(nil), "db.PlayerFriendPointList")
	proto.RegisterType((*PlayerFriendChatUnreadId)(nil), "db.PlayerFriendChatUnreadId")
	proto.RegisterType((*PlayerFriendChatUnreadIdList)(nil), "db.PlayerFriendChatUnreadIdList")
	proto.RegisterType((*PlayerFriendChatUnreadMessage)(nil), "db.PlayerFriendChatUnreadMessage")
	proto.RegisterType((*PlayerFriendChatUnreadMessageList)(nil), "db.PlayerFriendChatUnreadMessageList")
	proto.RegisterType((*PlayerChaterOpenRequest)(nil), "db.PlayerChaterOpenRequest")
	proto.RegisterType((*PlayerHandbookItem)(nil), "db.PlayerHandbookItem")
	proto.RegisterType((*PlayerHandbookItemList)(nil), "db.PlayerHandbookItemList")
	proto.RegisterType((*PlayerHeadItem)(nil), "db.PlayerHeadItem")
	proto.RegisterType((*PlayerHeadItemList)(nil), "db.PlayerHeadItemList")
	proto.RegisterType((*PlayerSuitAward)(nil), "db.PlayerSuitAward")
	proto.RegisterType((*PlayerSuitAwardList)(nil), "db.PlayerSuitAwardList")
	proto.RegisterType((*PlayerWorldChat)(nil), "db.PlayerWorldChat")
	proto.RegisterType((*PlayerAnouncement)(nil), "db.PlayerAnouncement")
	proto.RegisterType((*PlayerFirstDrawCard)(nil), "db.PlayerFirstDrawCard")
	proto.RegisterType((*PlayerFirstDrawCardList)(nil), "db.PlayerFirstDrawCardList")
}

func init() { proto.RegisterFile("db_hallsvr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x58, 0x5d, 0x6f, 0x13, 0x47,
	0x17, 0x96, 0x93, 0x38, 0x21, 0x93, 0x4f, 0x16, 0x08, 0x0b, 0x0a, 0xaf, 0xc2, 0xbe, 0xbc, 0xbc,
	0x29, 0x55, 0x23, 0x5a, 0x41, 0x4b, 0x11, 0x6d, 0x15, 0x1c, 0x02, 0x6e, 0x9d, 0x10, 0xad, 0x13,
	0x90, 0xa8, 0x2a, 0x3a, 0xf6, 0x4e, 0xe2, 0x25, 0xfb, 0x61, 0x76, 0xc7, 0x26, 0x96, 0xda, 0xdf,
	0xd0, 0xde, 0xf5, 0xaa, 0x52, 0x7f, 0x52, 0x2f, 0x7a, 0x57, 0xa9, 0xbf, 0xa5, 0x3a, 0x67, 0xbe,
	0x1d, 0xdb, 0xad, 0xb8, 0xf2, 0x9c, 0x67, 0xce, 0xce, 0x3c, 0x73, 0xbe, 0xe6, 0x8c, 0xc9, 0x6a,
	0xd4, 0x7a, 0xdd, 0xa1, 0x49, 0x52, 0xf6, 0x8b, 0xad, 0x6e, 0x91, 0xf3, 0xdc, 0x9b, 0x8a, 0x5a,
	0xc1, 0xb7, 0x64, 0xa5, 0x99, 0xd2, 0x24, 0x09, 0x69, 0x76, 0x1a, 0xb2, 0x76, 0x5e, 0x44, 0x9e,
	0x47, 0x66, 0x40, 0xf2, 0x2b, 0x1b, 0x95, 0xcd, 0x6a, 0x88, 0x63, 0x6f, 0x99, 0x4c, 0xd5, 0x23,
	0x7f, 0x0a, 0x91, 0xa9, 0x7a, 0xe4, 0xad, 0x92, 0xe9, 0x17, 0x34, 0xf1, 0xa7, 0x11, 0x80, 0x21,
	0x7c, 0xb5, 0x4f, 0x53, 0xe6, 0xcf, 0x6c, 0x54, 0x36, 0xe7, 0x43, 0x1c, 0x07, 0xdf, 0x90, 0xa5,
	0x46, 0x9c, 0xc6, 0xbc, 0xd9, 0xc9, 0xbb, 0x75, 0xce, 0x52, 0x6f, 0x83, 0x2c, 0xd4, 0xf2, 0x34,
	0xcd, 0xa3, 0x98, 0x0f, 0xea, 0x91, 0xdc, 0xc1, 0x86, 0x3c, 0x9f, 0xcc, 0x35, 0xd8, 0x31, 0xdf,
	0xef, 0xa5, 0x72, 0x37, 0x25, 0x06, 0xbf, 0xcf, 0x10, 0x72, 0x90, 0xd0, 0x01, 0x2b, 0xea, 0xd9,
	0x71, 0x0e, 0x0c, 0x1a, 0xfd, 0x44, 0x2e, 0x01, 0x43, 0x40, 0x9e, 0x9c, 0x75, 0xe5, 0x67, 0x30,
	0xf4, 0xfe, 0x43, 0x48, 0xad, 0x60, 0x94, 0xb3, 0xa3, 0x2c, 0x3e, 0x93, 0x64, 0x2d, 0xc4, 0xbb,
	0x45, 0x96, 0x76, 0xe3, 0xa2, 0xe4, 0x07, 0x74, 0xd0, 0xe4, 0x94, 0x0b, 0xf2, 0xd5, 0xd0, 0x05,
	0xbd, 0x4d, 0xb2, 0x52, 0xeb, 0xd0, 0xec, 0x84, 0xc1, 0x99, 0x6a, 0x79, 0x2f, 0xe3, 0x7e, 0x15,
	0xf5, 0x86, 0x61, 0xef, 0x2e, 0xb9, 0xd4, 0xa0, 0x25, 0xdf, 0x89, 0x69, 0x32, 0x38, 0xa4, 0xe5,
	0xe9, 0x51, 0xf7, 0x28, 0xce, 0xce, 0xfc, 0x59, 0xd4, 0x1e, 0x35, 0x05, 0x56, 0xab, 0xb7, 0xf3,
	0xcc, 0x9f, 0x13, 0x56, 0x83, 0x31, 0xb2, 0xee, 0x95, 0x3c, 0x4f, 0x71, 0xe6, 0x02, 0xce, 0x58,
	0x88, 0x77, 0x9d, 0x5c, 0xa8, 0x75, 0x68, 0x91, 0x82, 0x03, 0xe6, 0x71, 0x69, 0x2d, 0x7b, 0xeb,
	0x64, 0x1e, 0xb6, 0x69, 0xe4, 0x27, 0x71, 0xe6, 0x13, 0x9c, 0x34, 0x00, 0x58, 0xe8, 0x15, 0xcd,
	0xfc, 0x05, 0x61, 0xa1, 0x57, 0x34, 0xf3, 0xd6, 0xc8, 0x6c, 0xb3, 0x1b, 0x17, 0x31, 0xf7, 0x17,
	0x11, 0x94, 0x92, 0x17, 0x90, 0xc5, 0xdd, 0x22, 0x66, 0x59, 0x74, 0x90, 0xc7, 0x19, 0x2f, 0xfd,
	0x25, 0x9c, 0x75, 0x30, 0xef, 0x01, 0xb9, 0xda, 0xa4, 0x7d, 0x06, 0xcb, 0x8b, 0xaf, 0x10, 0x3f,
	0x8c, 0x53, 0xe6, 0x2f, 0xa3, 0xfa, 0xb8, 0x69, 0x65, 0xa7, 0x90, 0x1d, 0x17, 0xac, 0xec, 0x40,
	0x74, 0xe0, 0x57, 0x2b, 0xc6, 0x4e, 0x43, 0x53, 0xc0, 0xf3, 0x45, 0xdc, 0x05, 0x87, 0xaf, 0x0a,
	0x9e, 0x42, 0xf2, 0x1e, 0x91, 0x6b, 0x82, 0xd3, 0x1e, 0x2b, 0x4b, 0x7a, 0xc2, 0x8e, 0xb2, 0x82,
	0xd1, 0xa8, 0xd6, 0x2b, 0x8a, 0x7a, 0xe4, 0x5f, 0x44, 0xd5, 0xf1, 0x0a, 0xc1, 0x3d, 0xb2, 0x28,
	0x22, 0xea, 0x69, 0x92, 0xb7, 0x68, 0x02, 0xf1, 0x00, 0x33, 0x2c, 0xe3, 0x61, 0x9e, 0x30, 0x1d,
	0xa0, 0x2e, 0x18, 0x70, 0x15, 0x87, 0x20, 0xcb, 0xcc, 0xa8, 0xe8, 0xcc, 0xf0, 0xc9, 0xdc, 0x21,
	0x6d, 0xe1, 0xd7, 0x32, 0x80, 0xa5, 0xa8, 0xf3, 0x6a, 0xda, 0xca, 0xab, 0xcb, 0xa4, 0xda, 0x60,
	0x7d, 0x96, 0xc8, 0xc8, 0x13, 0x02, 0x68, 0x6e, 0x73, 0x5e, 0xf8, 0xd5, 0x8d, 0x69, 0xd0, 0x84,
	0x71, 0x70, 0x8f, 0x2c, 0x9b, 0x5d, 0x1b, 0x71, 0x09, 0x3e, 0x9a, 0x81, 0x5f, 0xbf, 0xb2, 0x31,
	0xbd, 0xb9, 0xf0, 0xc9, 0xf2, 0x56, 0xd4, 0xda, 0x32, 0x1a, 0x21, 0xce, 0x05, 0xdf, 0x93, 0x55,
	0x81, 0x3d, 0xa6, 0x9c, 0x27, 0xec, 0x90, 0xd1, 0x14, 0x4e, 0xb9, 0xcd, 0x39, 0x6d, 0x9f, 0xee,
	0xb1, 0xb4, 0xc5, 0x8a, 0x12, 0x17, 0xa8, 0x86, 0x2e, 0xe8, 0xdd, 0x26, 0xcb, 0x3b, 0xec, 0x98,
	0x65, 0x25, 0x53, 0x6a, 0x53, 0xa8, 0x36, 0x84, 0x06, 0x7f, 0x56, 0xc8, 0x82, 0xd8, 0xa2, 0xc9,
	0xe9, 0x09, 0x83, 0xf3, 0xe3, 0x40, 0x1b, 0x45, 0x89, 0x70, 0xd6, 0x26, 0xa7, 0xb8, 0x10, 0x9e,
	0x15, 0x05, 0xef, 0x0e, 0x59, 0x05, 0x87, 0xef, 0xc6, 0x59, 0x5c, 0x76, 0x58, 0x64, 0x65, 0xea,
	0x39, 0x1c, 0x22, 0xff, 0x30, 0xef, 0x36, 0xdb, 0x79, 0xa1, 0x52, 0x55, 0xcb, 0xb0, 0x7a, 0x8d,
	0xf2, 0x7a, 0x24, 0x73, 0x53, 0x08, 0x50, 0x70, 0x90, 0x5c, 0x24, 0xf2, 0x56, 0x64, 0xa2, 0x0d,
	0x41, 0xc6, 0x1c, 0xd0, 0xb2, 0x14, 0xf3, 0x73, 0x22, 0x63, 0x34, 0x10, 0x7c, 0x4a, 0x56, 0xac,
	0xc3, 0xa1, 0xd9, 0xff, 0xeb, 0x98, 0x7d, 0xc5, 0x98, 0x1d, 0x55, 0xa4, 0xdd, 0x7f, 0xaa, 0x90,
	0x4b, 0x02, 0xad, 0x75, 0x68, 0x97, 0xb3, 0xe2, 0x28, 0x6b, 0xe4, 0xed, 0x53, 0xd8, 0x4d, 0x02,
	0xda, 0x3e, 0x06, 0x40, 0x2e, 0xa2, 0xc2, 0x45, 0xca, 0xdc, 0x06, 0x10, 0x75, 0xa1, 0x78, 0xc6,
	0x92, 0x2e, 0x4c, 0x4f, 0xe3, 0xb4, 0x85, 0xc0, 0xd7, 0x60, 0x52, 0x8e, 0x26, 0x14, 0xe6, 0x31,
	0x40, 0xf0, 0x73, 0x45, 0x97, 0x4f, 0xa8, 0xc4, 0xeb, 0x64, 0x1e, 0x7e, 0x6b, 0xc7, 0x27, 0x86,
	0x88, 0x06, 0xc0, 0x89, 0x20, 0x58, 0x55, 0x58, 0x8a, 0x10, 0x3c, 0xb8, 0x26, 0x64, 0xa5, 0xe5,
	0x2b, 0x17, 0x04, 0xad, 0x90, 0xa5, 0x34, 0xce, 0x9a, 0xac, 0x9d, 0x67, 0x51, 0xa9, 0x0a, 0xab,
	0x03, 0x9a, 0x90, 0x86, 0xc5, 0x27, 0x87, 0x34, 0x68, 0x48, 0xd3, 0x3e, 0x54, 0x5f, 0xe9, 0x5b,
	0x65, 0x44, 0x0a, 0x8e, 0xb9, 0x43, 0x1e, 0x11, 0xcf, 0xfd, 0x16, 0x77, 0xbd, 0xed, 0xec, 0xea,
	0x59, 0x1e, 0x95, 0x5a, 0x72, 0xe7, 0xef, 0xc8, 0x15, 0x83, 0xe3, 0xc5, 0xc6, 0x22, 0xbc, 0x8b,
	0x36, 0xc8, 0x82, 0x14, 0x77, 0xe8, 0xa0, 0x54, 0xd7, 0x9a, 0x05, 0x41, 0x3d, 0xc5, 0x42, 0x48,
	0xfb, 0x0c, 0x4b, 0x9d, 0xe0, 0xe5, 0x60, 0xc1, 0xd7, 0xe4, 0xda, 0xc8, 0xe5, 0x91, 0xe3, 0x47,
	0x0e, 0xc7, 0x6b, 0x2e, 0x47, 0x4b, 0x59, 0x52, 0x6d, 0xaa, 0xa4, 0xac, 0x75, 0x58, 0xc9, 0xa1,
	0xf0, 0x1f, 0xe4, 0x8a, 0x18, 0x0c, 0xc1, 0x46, 0x38, 0x65, 0xca, 0x94, 0x14, 0x61, 0xe6, 0x79,
	0x97, 0x81, 0x93, 0xa4, 0x6f, 0x95, 0x68, 0x92, 0x01, 0x55, 0x27, 0x27, 0x03, 0xaa, 0x48, 0x32,
	0x7f, 0x4c, 0xa9, 0xd0, 0xdb, 0xa3, 0x71, 0x02, 0xb5, 0x1c, 0x7e, 0xb5, 0xcb, 0xa4, 0x04, 0xd9,
	0x0d, 0xa3, 0xc3, 0x41, 0x57, 0xd9, 0x47, 0xcb, 0x10, 0xae, 0x38, 0x8e, 0x79, 0xc2, 0x90, 0xd6,
	0x7c, 0x68, 0x00, 0xf8, 0xb2, 0xc9, 0xb2, 0x08, 0x93, 0x4a, 0xd6, 0x05, 0x25, 0x43, 0xd6, 0x88,
	0x31, 0x76, 0x27, 0x55, 0x71, 0x9b, 0x1a, 0x04, 0x0d, 0x91, 0x67, 0x9c, 0xc9, 0xea, 0x30, 0x1f,
	0x2a, 0x51, 0xad, 0x8a, 0x51, 0x3e, 0x67, 0x56, 0x55, 0x95, 0xe8, 0x79, 0x1f, 0xb2, 0x3a, 0x3e,
	0xc3, 0x1b, 0xba, 0x1a, 0x6a, 0x19, 0xce, 0xf7, 0xbc, 0xf5, 0x06, 0x72, 0x74, 0x1e, 0x73, 0x54,
	0x4a, 0x68, 0xd8, 0xd6, 0x9b, 0xfd, 0x5e, 0x5a, 0xfa, 0x04, 0x27, 0x94, 0x28, 0x2b, 0x23, 0x67,
	0xf2, 0x66, 0x16, 0x02, 0x30, 0x7f, 0x72, 0xc6, 0x0b, 0xba, 0x43, 0x39, 0x2d, 0xfd, 0x45, 0x91,
	0xef, 0x06, 0x31, 0xe9, 0x03, 0x86, 0x98, 0x9c, 0x3e, 0xa0, 0x21, 0x9d, 0xf1, 0x5a, 0x39, 0x51,
	0xb7, 0x22, 0x40, 0x18, 0x7e, 0x8d, 0x43, 0x84, 0x04, 0xb4, 0x5e, 0xd0, 0xa4, 0xa7, 0xbc, 0x21,
	0x04, 0xa0, 0x15, 0xb2, 0x77, 0xb4, 0xb0, 0x4b, 0xb5, 0x85, 0x04, 0x5f, 0xaa, 0xca, 0xa7, 0x37,
	0x40, 0x6e, 0xff, 0x77, 0xb8, 0x5d, 0x32, 0xdc, 0xb4, 0x9a, 0x24, 0xd8, 0x26, 0x4b, 0x62, 0x62,
	0xbb, 0xdd, 0x89, 0x59, 0x1f, 0x7d, 0x2f, 0x87, 0xa6, 0x54, 0x69, 0xe0, 0x3d, 0x49, 0x3e, 0x24,
	0x17, 0x9d, 0x4d, 0x90, 0xe2, 0xff, 0x1c, 0x8a, 0x17, 0x0d, 0x45, 0xa9, 0x24, 0x09, 0xde, 0x57,
	0x65, 0x40, 0xdd, 0x4d, 0xff, 0x8a, 0xa8, 0x49, 0xef, 0xa1, 0xcf, 0x26, 0xa7, 0xf7, 0x90, 0xb2,
	0xa4, 0x50, 0x53, 0x6b, 0xed, 0xd0, 0x58, 0x18, 0xef, 0x65, 0x27, 0x4f, 0x18, 0x4a, 0x70, 0x73,
	0xd7, 0xf2, 0xb4, 0x9b, 0x30, 0xce, 0x1c, 0xb7, 0x0e, 0xa1, 0x41, 0x48, 0x6e, 0x8c, 0x5d, 0x04,
	0x49, 0x7d, 0xec, 0x90, 0xba, 0x61, 0xb9, 0xec, 0xfc, 0x07, 0x92, 0xd8, 0xa9, 0x72, 0x7e, 0x93,
	0xf5, 0x59, 0xb6, 0xdd, 0xe6, 0x71, 0x3f, 0xe6, 0x03, 0x70, 0x87, 0x1a, 0x6b, 0x3a, 0x16, 0xf2,
	0x9e, 0x4e, 0xdc, 0x25, 0x57, 0x47, 0x6c, 0x86, 0xd4, 0x3f, 0x74, 0xa8, 0x5f, 0xb5, 0xca, 0xa5,
	0xad, 0x2a, 0x49, 0x3f, 0xd6, 0x6d, 0x60, 0x2f, 0x8e, 0x18, 0x26, 0x2a, 0x8e, 0x4c, 0x0b, 0x23,
	0x45, 0x6c, 0x6e, 0x98, 0xb8, 0x60, 0x65, 0xd5, 0x94, 0x62, 0xf0, 0x40, 0x35, 0x5a, 0x62, 0x0d,
	0x24, 0x71, 0xcb, 0x21, 0xb1, 0x6a, 0x48, 0x08, 0x1d, 0xb9, 0xfb, 0x6f, 0x15, 0x72, 0x59, 0xfa,
	0x1a, 0x1b, 0xd5, 0x90, 0x25, 0x94, 0xc7, 0x7d, 0xe6, 0x3d, 0x24, 0x3e, 0xdc, 0x0f, 0x4f, 0xe3,
	0x3e, 0xb3, 0xfb, 0x6e, 0xbc, 0x3f, 0x04, 0xaf, 0xb1, 0xf3, 0x70, 0xdf, 0x00, 0xbe, 0xdf, 0x4b,
	0x0f, 0xf3, 0x88, 0x0e, 0xd4, 0x7d, 0x63, 0x63, 0xf0, 0xae, 0xb1, 0x5a, 0x6d, 0x5c, 0x56, 0xd8,
	0x78, 0x18, 0x0e, 0xfe, 0xaa, 0x28, 0x0b, 0x89, 0x8d, 0xa0, 0xfc, 0x89, 0x91, 0x36, 0x91, 0x96,
	0xc1, 0x6b, 0x62, 0x8c, 0x05, 0x77, 0x4a, 0x14, 0x5c, 0x83, 0x40, 0x73, 0xfb, 0x8c, 0xd1, 0x48,
	0x56, 0x71, 0x1c, 0x8f, 0x69, 0x83, 0xaf, 0x93, 0x0b, 0xd0, 0xe6, 0xe3, 0x84, 0xe8, 0xea, 0xb4,
	0xec, 0x3e, 0x74, 0x66, 0x87, 0x1f, 0x3a, 0x5b, 0xc4, 0x53, 0xa6, 0xb1, 0x8c, 0x26, 0x8a, 0xf8,
	0x88, 0x19, 0xe3, 0x3d, 0xc1, 0x73, 0xb2, 0xf7, 0xa4, 0x9b, 0x84, 0xf7, 0x4e, 0x54, 0x39, 0x55,
	0xce, 0x7b, 0x0b, 0xb4, 0x55, 0xd3, 0xa6, 0x8c, 0xa3, 0x64, 0x30, 0x8e, 0x18, 0xdb, 0xc6, 0x31,
	0x08, 0x04, 0x58, 0xc8, 0xde, 0x5a, 0xf1, 0xae, 0x44, 0x53, 0x56, 0xf5, 0x46, 0x93, 0xcb, 0xaa,
	0x56, 0x93, 0x44, 0x7f, 0xad, 0xa8, 0x92, 0x67, 0x05, 0x8b, 0x78, 0xe7, 0xe5, 0xe9, 0x10, 0x5f,
	0x07, 0x03, 0xce, 0xc6, 0x5c, 0x32, 0x92, 0x2c, 0x44, 0xf5, 0x36, 0x80, 0x58, 0x41, 0xe4, 0x60,
	0xd0, 0x21, 0xd5, 0x4b, 0x0c, 0x3b, 0x80, 0xa4, 0x9b, 0x6d, 0x28, 0x78, 0xac, 0xab, 0xaa, 0xa1,
	0x87, 0x27, 0xfc, 0xc0, 0x39, 0xe1, 0x95, 0xe1, 0x13, 0xa2, 0xa2, 0x3c, 0xe3, 0x0f, 0xc4, 0xb7,
	0xa7, 0x6a, 0x1d, 0xca, 0xc5, 0x7b, 0xaf, 0xfe, 0x8f, 0x21, 0x2b, 0x9f, 0x87, 0xa6, 0xf1, 0xb6,
	0x10, 0xf5, 0x2e, 0xd4, 0x88, 0x6a, 0x7a, 0x1d, 0x30, 0x38, 0x20, 0xeb, 0xe3, 0x76, 0xc7, 0x83,
	0xdc, 0x75, 0x0e, 0xb2, 0x3e, 0x7c, 0x10, 0x5b, 0x5f, 0x9e, 0xe7, 0x97, 0x8a, 0x2a, 0xd1, 0xc3,
	0x2a, 0x72, 0x57, 0xc8, 0x61, 0x79, 0xc3, 0x6b, 0x6e, 0x70, 0xb8, 0xe9, 0x70, 0x18, 0x86, 0xc8,
	0x92, 0x02, 0xba, 0x70, 0x31, 0x54, 0xa2, 0xea, 0x73, 0x2c, 0xdf, 0x69, 0x19, 0x5a, 0x83, 0x7a,
	0x19, 0x42, 0xba, 0x0a, 0x97, 0x49, 0x29, 0x78, 0x45, 0x6e, 0x4e, 0x24, 0x86, 0x07, 0xbe, 0xef,
	0x1c, 0xf8, 0xe6, 0xf8, 0x03, 0xcb, 0x8f, 0xe4, 0xa9, 0x3f, 0x57, 0x65, 0x1d, 0x14, 0x58, 0x01,
	0xdd, 0x67, 0xc8, 0xde, 0xf6, 0xa0, 0x8f, 0xd5, 0x7f, 0x8d, 0x40, 0x07, 0x84, 0x27, 0x5d, 0x0c,
	0x2d, 0x24, 0xb8, 0xa5, 0xfa, 0xfb, 0x67, 0x34, 0x8b, 0x5a, 0x79, 0x7e, 0x3a, 0xea, 0x7d, 0x10,
	0xec, 0x90, 0xb5, 0xf3, 0x5a, 0xc8, 0xf8, 0x8e, 0xc3, 0x78, 0xcd, 0x30, 0xb6, 0x35, 0x25, 0xcd,
	0x0d, 0xd5, 0x7e, 0x41, 0x05, 0x1b, 0xb9, 0x8f, 0x7e, 0x6d, 0x28, 0x8d, 0xc9, 0xaf, 0x0d, 0xa5,
	0x25, 0xd7, 0xff, 0x4a, 0x3f, 0x3d, 0x7b, 0x31, 0xdf, 0x86, 0x4b, 0xef, 0xdc, 0x43, 0x07, 0x1a,
	0x0e, 0x98, 0xb0, 0x9e, 0x14, 0x06, 0x30, 0x15, 0x43, 0x2f, 0x30, 0xb9, 0x62, 0x68, 0x35, 0x49,
	0xe0, 0x47, 0x45, 0xe0, 0x65, 0x5e, 0x24, 0xe8, 0x2d, 0x95, 0xea, 0x30, 0xb6, 0xae, 0x21, 0x07,
	0x53, 0x3a, 0x07, 0xbd, 0x24, 0x19, 0x7e, 0xea, 0x28, 0x4c, 0xe9, 0xec, 0x95, 0x27, 0xf5, 0x2c,
	0x62, 0x67, 0x76, 0xc9, 0x50, 0x58, 0xf0, 0x99, 0x6e, 0xd1, 0xb2, 0xbc, 0x97, 0xb5, 0x59, 0xca,
	0x32, 0x4d, 0x40, 0xc7, 0xab, 0x45, 0x40, 0x61, 0xc1, 0x17, 0xba, 0x52, 0xc6, 0x45, 0xc9, 0x77,
	0x0a, 0xfa, 0xae, 0x36, 0xca, 0x78, 0x6b, 0x64, 0x16, 0xe6, 0x98, 0x7a, 0x00, 0x49, 0xc9, 0x74,
	0x15, 0xce, 0xe7, 0x93, 0xbb, 0x0a, 0x47, 0x55, 0x98, 0xef, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x5f, 0x59, 0x50, 0xf6, 0x70, 0x15, 0x00, 0x00,
}
